## Pairwise grading

In order to assess the specificity of certain disclosures, we are going to perform pairwise grading. This means starting with the positively identified samples and then putting them up against one another in a grading schema (based on categories from Oppong-Tawiah and Webster 2023)

In [44]:
import sys
sys.path.append('..')
import utils
from path import Path
import openai
import os
from dotenv import load_dotenv
import pandas as pd

# Load environment variables from .env file
load_dotenv()

# Get OpenRouter API key from environment variables
OPENROUTER_API_KEY = os.getenv('OPENROUTER_API_KEY')
if not OPENROUTER_API_KEY:
    raise ValueError("Please set OPENROUTER_API_KEY in your .env file or environment variables")

In [45]:
results_path = '../results/SAO_RAG_RESULTS'
results_path = Path(results_path)

In [46]:
results = utils.load_company_data(results_path)

In [47]:
results

,company,original_index,year,text,climate_litigation,retrieval_similarity,num_examples_used
0,RCL,25,2014,We believe that the impact of ships on the glo...,climate_litigation: 0,0.564889,5
1,RCL,48,2014,To the extent the tonnage tax laws of these co...,climate_litigation: 0,0.531344,5
2,RCL,40,2014,"dollar, including, among others, the British p...",climate_litigation: 0,0.528860,5
3,RCL,24,2014,"The ISM Code is mandatory for all vessels, inc...",climate_litigation: 0,0.523801,5
4,RCL,41,2014,An increase in fuel prices not only impacts ou...,climate_litigation: 0,0.516437,5
...,...,...,...,...,...,...,...
52505,GLP,64,2016,"For example, our partnership agreement: ·\nper...",climate_litigation: 0,0.484702,5
52506,GLP,88,2016,We operate our business under three segments: ...,climate_litigation: 0,0.484497,5
52507,GLP,104,2016,Our gross profit for 2014 was negatively impac...,climate_litigation: 0,0.482937,5
52508,GLP,285,2016,"The fees, which are based upon an estimate of ...",climate_litigation: 0,0.482671,5
52509,GLP,38,2016,"As a result, we may experience declines in our...",climate_litigation: 0,0.481738,5

Extracting the binary number from the climate litigation assignment

In [48]:
trouble_indices = []

In [49]:
results['climate_litigation_binary'] = results.apply(
    lambda row: utils.extract_flag(row['climate_litigation'], row.name, trouble_indices), 
    axis=1
)

Subsetting to only the positively identified phrases

In [50]:
results_1 = results[results['climate_litigation_binary'] == 1]

In [51]:
len(results_1)

616

In [52]:
#calculate the number of pairwise comparisons we need to make; note this is mn(n−1) rather than mn(n−1)/2 because we always need to swap the presentation order of the responses si and sj
#reference: Gao 2025 

total_comparisons = len(results_1) * (len(results_1) - 1)
total_comparisons

378840

## Pairwise prompting

In [53]:
client = openai.OpenAI(
    api_key=OPENROUTER_API_KEY,
    base_url="https://openrouter.ai/api/v1"
)

In [ ]:
def get_pairwise_prompt(sentence_1, sentence_2):
    return (
        "You are comparing two sections to decide which is MORE SPECIFIC about CLIMATE CHANGE LITIGATION.\n"
        "\n"
        "Use the literature notion of specificity: level of detail and precision about place, time, numbers, or descriptive/sensory facts "
        "('spatio-temporal/descriptive' vs. generalized wording). Apply this ONLY to climate change litigation content.\n"
        "\n"
        "PROCESS\n"
        "1) Independently assess Section 1, then Section 2.\n"
        "2) For each section, judge specificity based on:\n"
        "   - PRECISION of anchors: named parties/case title/docket, forum or jurisdiction, statute/regulation/policy, procedural posture, dates/time frames, monetary/quantified remedies or thresholds.\n"
        "   - LINKAGE: whether those anchors are clearly tied to climate claims (not just generic legal or sustainability talk).\n"
        "   - FALSIFIABILITY: whether the details are concrete enough to be checked or challenged (e.g., exact court, filing date, cited rule).\n"
        "   - CONTEXTUAL CLARITY: whether the details fit together coherently (who did what, where, when, under which rule, seeking what outcome).\n"
        "Ignore specificity about non-climate topics.\n"
        "\n"
        "SCORING GUIDELINES (no counting—judge by presence, precision, and linkage strength):\n"
        "0: No climate litigation content at all.\n"
        "10: Climate issues mentioned but not litigation.\n"
        "20: Litigation is referenced but only in generic terms; no precise legal anchor or linkage to climate claims.\n"
        "40: At least one legal anchor appears (e.g., forum, party, statute) but is vague or only loosely tied to climate claims; timing/place/amounts are broad or implied.\n"
        "60: Clear, specific legal anchor(s) precisely linked to climate claims (e.g., named agency action, identifiable forum or statute, plausible timeframe or remedy), but some elements remain general or implicit.\n"
        "80: Multiple precise and well-linked anchors (e.g., named party or case title AND specific forum/jurisdiction AND concrete timeframe or remedy); coherent and checkable, minor gaps only.\n"
        "90–100: Highly specific and verifiable (e.g., case name or docket; exact court; specific date(s) or stage; cited rule/statute; defined remedy/amounts), tightly and explicitly tied to climate claims with strong internal coherence.\n"
        "Choose an integer score that best fits the description above.\n"
        "\n"
        "DECISION\n"
        "- After scoring both independently, choose the MORE SPECIFIC section.\n"
        "- If scores differ by ≥20, pick the higher score.\n"
        "- If |diff| ≤ 10, apply tie-breakers IN ORDER:\n"
        "  (i) Prefer the section that names a case, docket, or parties with a specific forum/jurisdiction.\n"
        "  (ii) Prefer the section with clearer procedural posture and explicit linkage to a climate rule/policy/statute.\n"
        "  (iii) Prefer the section with more precise spatio-temporal or monetary details that are checkable.\n"
        "  (iv) If still tied, output \"section 2\" (bias control).\n"
        "\n"
        "RULES\n"
        "- OUTPUT MUST BE VALID JSON ONLY (no extra text, no comments, no trailing commas).\n"
        "\n"
        "OUTPUT FORMAT (exact schema, do not provide any other text):\n"
        "[\n"
        "  {\n"
        "    \"binary result\": \"section 1\" or \"section 2\",\n"
        "    \"section_1\": <integer 0-100>,\n"
        "    \"section_2\": <integer 0-100>\n"
        "  }\n"
        "]\n"
        "\n"
        "SECTIONS\n"
        f"Section 1: {sentence_1}\n"
        f"Section 2: {sentence_2}\n"
    )

In [ ]:
sentence_1 = results_1.iloc[13]['text']
sentence_2 = results_1.iloc[16]['text']
message = get_pairwise_prompt(sentence_1, sentence_2)
from pprint import pprint
pprint(message)

('You are comparing two sections to decide which is MORE SPECIFIC about '
 'CLIMATE CHANGE LITIGATION.\n'
 '\n'
 'Use the literature notion of specificity: level of detail and precision '
 'about place, time, numbers, or descriptive/sensory facts '
 "('spatio-temporal/descriptive' vs. generalized wording). Apply this ONLY to "
 'climate change litigation content.\n'
 '\n'
 'PROCESS\n'
 '1) Independently assess Section 1, then Section 2.\n'
 '2) For each section, judge specificity based on:\n'
 '   - PRECISION of anchors: named parties/case title/docket, forum or '
 'jurisdiction, statute/regulation/policy, procedural posture, dates/time '
 'frames, monetary/quantified remedies or thresholds.\n'
 '   - LINKAGE: whether those anchors are clearly tied to climate claims (not '
 'just generic legal or sustainability talk).\n'
 '   - FALSIFIABILITY: whether the details are concrete enough to be checked '
 'or challenged (e.g., exact court, filing date, cited rule).\n'
 '   - CONTEXTUAL CLARITY: whether the details fit together coherently (who '
 'did what, where, when, under which rule, seeking what outcome).\n'
 'Ignore specificity about non-climate topics.\n'
 '\n'
 'SCORING GUIDELINES (no counting—judge by presence, precision, and linkage '
 'strength):\n'
 '0: No climate litigation content at all.\n'
 '10: Climate issues mentioned but not litigation.\n'
 '20: Litigation is referenced but only in generic terms; no precise legal '
 'anchor or linkage to climate claims.\n'
 '40: At least one legal anchor appears (e.g., forum, party, statute) but is '
 'vague or only loosely tied to climate claims; timing/place/amounts are broad '
 'or implied.\n'
 '60: Clear, specific legal anchor(s) precisely linked to climate claims '
 '(e.g., named agency action, identifiable forum or statute, plausible '
 'timeframe or remedy), but some elements remain general or implicit.\n'
 '80: Multiple precise and well-linked anchors (e.g., named party or case '
 'title AND specific forum/jurisdiction AND concrete timeframe or remedy); '
 'coherent and checkable, minor gaps only.\n'
 '90–100: Highly specific and verifiable (e.g., case name or docket; exact '
 'court; specific date(s) or stage; cited rule/statute; defined '
 'remedy/amounts), tightly and explicitly tied to climate claims with strong '
 'internal coherence.\n'
 'Choose an integer score that best fits the description above.\n'
 '\n'
 'DECISION\n'
 '- After scoring both independently, choose the MORE SPECIFIC section.\n'
 '- If scores differ by ≥20, pick the higher score.\n'
 '- If |diff| ≤ 10, apply tie-breakers IN ORDER:\n'
 '  (i) Prefer the section that names a case, docket, or parties with a '
 'specific forum/jurisdiction.\n'
 '  (ii) Prefer the section with clearer procedural posture and explicit '
 'linkage to a climate rule/policy/statute.\n'
 '  (iii) Prefer the section with more precise spatio-temporal or monetary '
 'details that are checkable.\n'
 '  (iv) If still tied, output "section 2" (bias control).\n'
 '\n'
 'RULES\n'
 '- OUTPUT MUST BE VALID JSON ONLY (no extra text, no comments, no trailing '
 'commas).\n'
 '\n'
 'OUTPUT FORMAT (exact schema, do not provide any other text):\n'
 '[\n'
 '  {\n'
 '    "binary result": "section 1" or "section 2",\n'
 '    "section_1": <integer 0-100>,\n'
 '    "section_2": <integer 0-100>\n'
 '  }\n'
 ']\n'
 '\n'
 'SECTIONS\n'
 'Section 1: For example, CNX is a party to four climate change lawsuits being '
 'pursued by communities against fossil fuel producers relating to climate '
 'change, which are beginning to gain prevalence in the courts. There is also '
 'the possibility that CNX may become involved in future investigations or '
 'suits regarding its business activities. There is the potential that the '
 'costs of defending litigation in an individual matter or the aggregation of '
 'many matters could have an adverse effect on our cash flows, results of '
 'operations or financial position. See Note\xa020\xa0– Commitments and '
 'Contingent Liabilities in the Notes to the Audited Consolidated Financial '
 'Statements in Item 8 of this Form 10-K for further discussion of pending '
 'legal proceedings.\n'
 'Financing, Investment and Indebtedness Risks\n'
 'Our current long-term debt obligations, and the terms of the agreements that '
 'govern that debt and the risks associated therewith, could adversely affect '
 'our business, financial condition, liquidity and results of operations.\n'
 'As of December\xa031, 2023, CNX’s total long-term indebtedness was '
 'approximately $2.2 billion, excluding unamortized debt issuance costs, of '
 'which approximately (i) $500 million was under our 7.375% Senior Notes due '
 '2031 less $5 million of unamortized discount, (ii) $500 million of 6.00% '
 'Senior Notes due 2029, (iii) $400 million of 4.75% Senior Notes due 2030 '
 'issued by our midstream business, less $4 million of unamortized bond '
 'discount (CNX is not a guarantor of these notes), (iv) $350 million of 7.25% '
 'Senior Notes due 2027 plus $2\xa0million of unamortized bond premium, (v) '
 '$331 million of 2.25% Convertible Senior Notes due 2026 less $5 million of '
 'unamortized discount and issuance cost, (vi) $105 million in outstanding '
 'borrowings under our midstream revolver (CNX is not a guarantor of this '
 'revolving credit facility), and (vii) $52 million in outstanding borrowings '
 'under our senior secured credit facility (the “Credit Facility”).\n'
 'Section 2: Additionally, any significant variance in our interpretation of '
 'current income tax laws, including as result of the release of any Treasury '
 'Regulations or other interpretive guidance or a challenge of one or more of '
 'our tax positions by the IRS or other tax authorities could affect our tax '
 'position. While CNX expects to be able to utilize our NOL carryforwards and '
 'generate deductions to offset our future taxable income, in the event that '
 'deductions are not generated as expected, one or more of our tax positions '
 'are successfully challenged by the IRS (in a tax audit or otherwise), or our '
 'NOL 34\n'
 'carryforwards are subject to future limitations, our future tax liability '
 'may be greater than expected.\n'
 'CNX and its subsidiaries are subject to various legal proceedings and '
 'investigations, which may have an adverse effect on our business.\n'
 'CNX is party to a number of legal proceedings and, from time to time, '
 'investigations, in the normal course of business activities. Responding to '
 'investigations or defending these actions, especially purported class '
 'actions, can be costly and can distract management. For example, CNX is a '
 'defendant in pending purported class action lawsuits dealing with claimants’ '
 'alleged entitlements to, and accounting for, natural gas royalties. '
 'Additionally, CNX is a party to four climate change lawsuits being pursued '
 'by communities against fossil fuel producers relating to climate change, '
 'which are beginning to gain prevalence in the courts. There is also the '
 'possibility that CNX may become involved in future investigations or suits '
 'regarding its business activities. There is the potential that the costs of '
 'defending litigation in an individual matter or the aggregation of many '
 'matters could have an adverse effect on our cash flows, results of '
 'operations or financial position.\n')

In [ ]:
SYSTEM_MESSAGE = (
    "You are a legal and environmental disclosure expert. Previously, someone else extracted all of the sentences from several companies' annual reports that related to climate litigation. Now, we are interested in assessing the specificity of these disclosures.\n\n"
    "Specificity captures the level of detail and precision, measured by the number of specific details related to place, time, numbers, or the five senses (i.e., “descriptive” and “spatio-temporal” words), as opposed to “generalized words”.\n\n"
    "The most important part of your job is choosing which section is more specific. So focus on that first and foremost. You only respond in the JSON format, no other text. EVER."
)

In [ ]:
response = client.chat.completions.create(
    model="meta-llama/llama-3.1-70b-instruct",
    messages=[
        {"role": "system", "content": SYSTEM_MESSAGE},
        {"role": "user", "content": message}
    ],
    temperature=0.0
)
print(response.choices[0].message.content)

[
  {
    "binary result": "section 1",
    "section_1": 60,
    "section_2": 40
  }
]

I'm having the problem that if I assess with the more powerful LLM it is more consistent but the one that proved most accurate in our other tasks is failing, always saying section 2 (mostly) and also struggling in consistency. Maybe it needs the guardrails of few shot learning to be effective? I wonder if I could justify a different model in the pairwise grading than in the original work.

We can justify from Gao et al. 2025 that the best open source model for pairwise grading is meta-llama/llama-3.1-70b-instruct. The problem is just then showing why we did what we did in the first task. I think that's doable, we just need to cast the original problem as it was, a more straightforward classification task that should be achievable for all LLMs.

## Running a small test against state of the art GPTo5

Think of this as our 'groundtruth' since it has been shown to be so successful on these types of tasks

## Concept-guided chain-of-thought

Start by including more than just the climate litigation sentences; we want to show that there are some that are not climate litigation at all. However, we will tell the LLM what it was graded before.

In [13]:
results_0 = results[results['climate_litigation_binary'] == 0]
results_0 = results_0.sample(n=308, random_state=42)

In [17]:
all_results = pd.concat([results_1, results_0])

## Setting the prompts

In [192]:
SYSTEM_PROMPT = """
You have been given a text. Please look at the text and respond in relation to that text at each step. 

You are a legal and environmental disclosure expert. 
"""

In [193]:
def get_prompt_1(text):
    return f"Summarize the following text: {text}"

def get_prompt_2(text, summary):
    return (
        "Please assess whether the following text is climate litigation.\n\n"
        "Previously, someone else extracted all of the sentences from several companies' annual reports that related to climate litigation. "
        "Now, we are interested in assessing the specificity of these disclosures.\n\n"
        "Now, we are just seeing if you agree with them.\n"
        "Climate litigation refers to legal actions that materially concern climate change science, policy, or law. These include, but are not limited to:\n"
        "- Lawsuits targeting false or misleading climate claims (e.g. greenwashing)\n"
        "- Legal actions over a company’s contribution to climate-related impacts\n"
        "- Efforts to force climate alignment through human rights or fiduciary duty arguments\n"
        "- Failure to disclose climate-related risks or impacts\n"
        "- Breaches of climate-related regulations\n"
        "- Litigation seeking damages for harms caused by climate change\n"
        "- Legal challenges to regulatory approvals on the basis of climate misalignment\n\n"
        "You will be given a summary of the text, as well as the original text.\n"
        f"Summary: {summary}\n\nOriginal text: {text}"
    )

def get_prompt_3(text, summary, classification):
    return (
        "For your knowledge, the text was previously classified as follows:\n"
        f"Summary: {summary}\n\nOriginal text: {text}\n\nClassification: {classification}\n"
        "Please only respond with an acknowledgement of this information."
    )

In [194]:
_BREAKDOWN_JSON_SCHEMA = r"""
Return ONLY valid JSON with this exact schema and keys (no code fences, no extra text):

{
  "parties": [string],
  "case_title_or_docket": string or null,
  "forum_or_jurisdiction": string or null,
  "statute_reg_policy": [string],
  "procedural_posture": string or null,
  "dates_or_timeframes": [string],
  "monetary_or_quantified": [string],
  "climate_linkage_summary": string,
  "climate_linkage_quotes": [string],
  "checkable_elements": [string],
  "who": string or null,
  "what": string or null,
  "where": string or null,
  "when": string or null,
  "under_which_rule": string or null,
  "sought_outcome": string or null,
  "evidence_quotes": [string]
}

Rules:
- Only consider these categories in relation to climate litigation. If there are dates, parties, monetary amounts, etc. that are not related to climate litigation, ignore them.
- Populate every key. Use [] for unknown lists, and null for unknown single values.
- Prefer short verbatim snippets from the text for any *quotes* arrays.
- Do NOT invent details not supported by the text. Ignore specificity about non-climate topics.
"""

def get_prompt_4(text, summary):
    return (
        "Build a concept-specific breakdown of SPECIFICITY for climate litigation.\n"
        "Focus on anchors (parties/case/docket, forum/jurisdiction, statute/reg/policy, posture, dates, monetary amounts), "
        "climate linkage, falsifiability (checkable details), and contextual clarity (who/what/where/when/under which rule/seeking what).\n\n"
        "It is very impotant that you only fill in the following schema with details that are DIRECTLY RELATED to climate litigation. Many text chunks will include details about other climate related regulations, monetary incentives, etc. but ONLY IF the text provides the following details about CLIMATE LITIGATION ITSELF, should you fill them in. Otherwise, they should be given null or empty lists."
        f"Summary: {summary}\n\nOriginal text:\n{text}\n\n"
        + _BREAKDOWN_JSON_SCHEMA
    )

In [196]:
_SPEC_LABEL_OPTIONS = [
    "not climate litigation",
    "mention only",           # acknowledges CL exists, zero specifics
    "vague disclosure",        # generic statements, no verifiable details
    "basic disclosure",        # some details but missing most anchors
    "detailed disclosure",     # multiple anchors, partially verifiable
    "highly specific",         # comprehensive, checkable information
]

def get_prompt_5(text, summary, classification, breakdown_json):
    return (
        "Given the summary, original text, CL classification, and the structured breakdown, choose ONE specificity label.\n"
        "Base your choice on:\n"
        " - PRECISION of anchors (parties/case/docket, forum, statute/reg/policy, posture, dates, monetary/quantified).\n"
        " - LINKAGE to climate claims (not generic legal/ESG talk).\n"
        " - FALSIFIABILITY (checkable details: exact court, date, cited rule, quantified remedy, etc.).\n"
        " - CONTEXTUAL CLARITY (who did what, where, when, under which rule, seeking what outcome).\n"
        "Ignore specificity about non-climate and non-litigation topics\n\n"
        f"Return ONLY one of: {', '.join(_SPEC_LABEL_OPTIONS)}\n\n"
        f"Summary: {summary}\n"
        f"Original text: {text}\n"
        f"Previously classified as climate litigation? {classification}\n"
        f"Breakdown JSON: {breakdown_json}"
    )

In [ ]:
def get_prompt_6(full_message_1, full_message_2):
    return (
        "You will compare two climate litigation assessments for SPECIFICITY.\n\n"
        
        "TASK: Determine which assessment provides MORE SPECIFIC details about climate litigation.\n"
        "Consider: precision of anchors (parties/case/forum/statute/dates/amounts), "
        "climate linkage strength, falsifiability (checkable details), and contextual clarity.\n\n"
        
        "CRITICAL: Do not favor an assessment based on its position (Text 1 vs Text 2). "
        "Base your judgment solely on content quality.\n\n"
        
        "SPECIAL CASES:\n"
        "- If exactly one assessment identifies climate litigation content, choose that one.\n"
        "- If BOTH assessments find NO climate litigation content, return 'neither'.\n"
        "- If both find climate litigation but one is clearly more specific, choose the more specific one.\n"
        "- Only use 'neither' when BOTH texts contain zero climate litigation content.\n\n"
        
        "EVALUATION PROCESS:\n"
        "1. First, analyze Text 1 independently:\n"
        f"   {full_message_1}\n\n"
        
        "2. Second, analyze Text 2 independently:\n"
        f"   {full_message_2}\n\n"
        
        "3. Direct comparison: Which provides more specific, verifiable climate litigation details?\n\n"
        
        "FORMAT:\n"
        "Provide your reasoning, then end with exactly one of these on a new line:\n"
        "FINAL: text 1\n"
        "FINAL: text 2\n"
        "FINAL: neither"
    )

In [198]:
def get_prompt_7(results):
    return (
        f"In the following content, extract the final decision. "
        f"Return ONLY 'text 1' or 'text 2' or 'neither' (no other text). "
        f"If absent, infer from the last explicit choice.\n\n{results}"
    )

## Testing calling the LLM for single sample

In [233]:
def call_llm(system_prompt, conversation_history, model):
    response = client.chat.completions.create(
        model=model,
        messages=[
            {"role": "system", "content": system_prompt},
            *conversation_history  
        ],
        temperature=0.0
    )
    return response.choices[0].message.content

In [232]:
import json
def run_single_text_pipeline(
    text: str,
    previous_classification: str,
    model = "meta-llama/llama-3.1-70b-instruct",
    verbose=True,
):
    """
    Run a multi-step pipeline where each LLM call sees the full conversation history.
    
    Each step appends to the conversation, so later steps have context from earlier ones.
    """
    conversation_history = []
    
    # ============================================================================
    # STEP 1: Generate Summary
    # ============================================================================
    p1 = get_prompt_1(text)
    conversation_history.append({"role": "user", "content": p1})
    print(f"conversation history: {conversation_history}")
    
    summary = call_llm(SYSTEM_PROMPT, conversation_history, model)
    conversation_history.append({"role": "assistant", "content": summary})
    
    if verbose:
        print(f"\n{'='*60}")
        print("STEP 1: SUMMARY")
        print(f"{'='*60}")
        print(summary)
    
    # ============================================================================
    # STEP 2: Climate Litigation Classification
    # ============================================================================
    p2 = get_prompt_2(text, summary)
    conversation_history.append({"role": "user", "content": p2})
    
    cls_raw = call_llm(SYSTEM_PROMPT, conversation_history, model)
    conversation_history.append({"role": "assistant", "content": cls_raw})
    
    if verbose:
        print(f"\n{'='*60}")
        print("STEP 2: CLASSIFICATION")
        print(f"{'='*60}")
        print(cls_raw)
    
    # ============================================================================
    # STEP 3: Verification/Explanation
    # ============================================================================
    p3 = get_prompt_3(text, summary, previous_classification)
    conversation_history.append({"role": "user", "content": p3})
    
    verification = call_llm(SYSTEM_PROMPT, conversation_history, model)
    conversation_history.append({"role": "assistant", "content": verification})
    
    if verbose:
        print(f"\n{'='*60}")
        print("STEP 3: VERIFICATION")
        print(f"{'='*60}")
        print(verification)
    
    # ============================================================================
    # STEP 4: Detailed Breakdown (JSON)
    # ============================================================================
    p4 = get_prompt_4(text, summary)
    conversation_history.append({"role": "user", "content": p4})
    
    raw_breakdown = call_llm(SYSTEM_PROMPT, conversation_history, model)
    conversation_history.append({"role": "assistant", "content": raw_breakdown})
    
    if verbose:
        print(f"\n{'='*60}")
        print("STEP 4: BREAKDOWN (raw)")
        print(f"{'='*60}")
        print(raw_breakdown[:500] + "..." if len(raw_breakdown) > 500 else raw_breakdown)
    
    # Parse and validate JSON
    def _try_parse(js):
        try:
            data = json.loads(js)
            if not isinstance(data, dict):
                return None
            # Check required keys
            required_keys = [
                "parties", "statute_reg_policy", "evidence_quotes",
                "climate_linkage_summary"
            ]
            for k in required_keys:
                if k not in data:
                    return None
            return json.dumps(data, ensure_ascii=False, indent=2)
        except (json.JSONDecodeError, Exception):
            return None
    
    breakdown_json = _try_parse(raw_breakdown)
    
    # Attempt repair if needed
    if breakdown_json is None:
        if verbose:
            print("⚠️  Invalid JSON, attempting repair...")
        
        repair_prompt = (
            "The previous JSON output was invalid. Please return ONLY valid JSON "
            "that matches the required schema. Fix any syntax errors or missing keys. "
            "Do not include explanations, markdown formatting, or additional text.\n\n"
            f"Previous output:\n{raw_breakdown}"
        )
        conversation_history.append({"role": "user", "content": repair_prompt})
        
        repaired = call_llm(SYSTEM_PROMPT, conversation_history, model)
        conversation_history.append({"role": "assistant", "content": repaired})
        
        breakdown_json = _try_parse(repaired)
        
        # Last resort fallback
        if breakdown_json is None:
            if verbose:
                print("⚠️  Repair failed, using empty template")
            breakdown_json = json.dumps({
                "parties": [],
                "case_title_or_docket": None,
                "forum_or_jurisdiction": None,
                "statute_reg_policy": [],
                "procedural_posture": None,
                "dates_or_timeframes": [],
                "monetary_or_quantified": [],
                "climate_linkage_summary": "",
                "climate_linkage_quotes": [],
                "checkable_elements": [],
                "who": None,
                "what": None,
                "where": None,
                "when": None,
                "under_which_rule": None,
                "sought_outcome": None,
                "evidence_quotes": []
            }, ensure_ascii=False, indent=2)
    
    # ============================================================================
    # STEP 5: Specificity Label
    # ============================================================================
    p5 = get_prompt_5(text, summary, previous_classification, breakdown_json)
    conversation_history.append({"role": "user", "content": p5})
    
    label_raw = call_llm(SYSTEM_PROMPT, conversation_history, model)
    conversation_history.append({"role": "assistant", "content": label_raw})
    
    if verbose:
        print(f"\n{'='*60}")
        print("STEP 5: SPECIFICITY")
        print(f"{'='*60}")
        print(label_raw)
    
    # Normalize specificity label
    label = label_raw.strip().lower()
    specificity = label
    
    # ============================================================================
    # Compile full message thread
    # ============================================================================
    full_messages = ""
    for i, msg in enumerate(conversation_history):
        role = msg["role"].upper()
        content = msg["content"]
        full_messages += f"\n{'='*60}\n"
        full_messages += f"{role} MESSAGE {i+1}\n"
        full_messages += f"{'='*60}\n"
        full_messages += f"{content}\n"
    
    if verbose:
        print(f"\n{'='*60}")
        print("PIPELINE COMPLETE")
        print(f"{'='*60}")
        print(f"Classification: {previous_classification}")
        print(f"Specificity: {specificity}")
    
    return {
        "summary": summary,
        "classification": previous_classification,
        "verification": verification,
        "breakdown_json": breakdown_json,
        "specificity_label": specificity,
        "conversation_history": conversation_history,
        "full_messages": full_messages,
    }

In [201]:
sentence_1 = all_results.iloc[25]['text']
classification_1 = all_results.iloc[13]['climate_litigation_binary']
if classification_1 == 1:
    classification_1 = 'yes, this is an instance of climate litigation disclosure'
else:
    classification_1 = 'no, this is not an instance of climate litigation disclosure'

In [175]:
result = run_single_text_pipeline(sentence_1, classification_1)

conversation history: [{'role': 'user', 'content': 'Summarize the following text: If we cannot find adequate sources of water for our use or we are unable to dispose of or recycle the water at a reasonable cost and within applicable environmental rules, our ability to produce natural gas economically and in commercial quantities could be impaired.\nAs part of our drilling and production in shale formations, we use hydraulic fracturing processes. These processes require access to adequate sources of water, which may not be available in proximity to our operations or at certain times of the year. To ensure that we have adequate water available for our operations, we may be required to invest substantial amounts of capital in water pipelines which are used for relatively short periods of time. Alternatively, we may be required to truck water, and we may not be able to contract for sufficient water hauling trucks to meet our needs.\nFurther, we must remove the portion of the water that flows back to the well bore, as well as drilling fluids and other wastes associated with the exploration, development or production of natural gas. This water can be either disposed of or recycled for use in other hydraulic fracturing operations. In the event we are forced to dispose of water rather than recycle water, our costs may increase. In addition, in our CBM drilling and production, coal seams frequently contain water that must be removed and disposed of in order for the natural gas to detach from the coal and flow to the well bore.\nOur inability to obtain sufficient amounts of water with respect to our shale operations, or the inability to dispose of or recycle water and other wastes used in our shale and our CBM operations, could increase our costs and delay our operations, which will adversely impact our cash flow and results of operations.\nCNX and its subsidiaries are subject to various legal proceedings, which may have an adverse effect on our business.\nWe are party to a number of legal proceedings in the normal course of business activities. Defending these actions, especially purported class actions, can be costly, and can distract management. For example, we are a defendant in three pending purported class action lawsuits dealing with claimants’ alleged entitlements to, and accounting for, natural gas royalties. There is also the possibility that we may become involved in future suits, including, for example, those being brought by coastal communities against oil, coal and other fossil fuel producers relating to climate change, which are beginning to gain prevalence in the courts.'}]

============================================================
STEP 1: SUMMARY
============================================================
The text highlights two main concerns related to the operations of a natural gas production company, specifically CNX and its subsidiaries.

Firstly, the company's ability to access and manage water resources is crucial for its hydraulic fracturing processes in shale formations. However, there are risks associated with obtaining sufficient water, disposing of or recycling water, and managing drilling fluids and other wastes. These challenges could lead to increased costs, delayed operations, and ultimately, negatively impact the company's cash flow and results of operations.

Secondly, the company is subject to various legal proceedings, including purported class action lawsuits related to natural gas royalties and potential future suits related to climate change. These legal proceedings can be costly, distracting for management, and may have an adverse effect on the company's business.

============================================================
STEP 2: CLASSIFICATION
============================================================
Based on the provided definition of climate litigation, I would assess that the text is partially related to climate litigation.

The relevant sentence that mentions climate litigation is:

"There is also the possibility that we may become involved in future suits, including, for example, those being brought by coastal communities against oil, coal and other fossil fuel producers relating to climate change, which are beginning to gain prevalence in the courts."

This sentence mentions potential future lawsuits related to climate change, which aligns with the definition of climate litigation. Specifically, it falls under the category of "Litigation seeking damages for harms caused by climate change" or "Legal actions over a company’s contribution to climate-related impacts".

However, it's worth noting that this is a brief mention of potential future lawsuits, and the majority of the text focuses on other operational and legal concerns unrelated to climate litigation.

============================================================
STEP 3: VERIFICATION
============================================================
I acknowledge that the text was previously classified as an instance of climate litigation disclosure.

============================================================
STEP 4: BREAKDOWN (raw)
============================================================
{
  "parties": ["coastal communities", "oil, coal and other fossil fuel producers"],
  "case_title_or_docket": null,
  "forum_or_jurisdiction": null,
  "statute_reg_policy": [],
  "procedural_posture": null,
  "dates_or_timeframes": [],
  "monetary_or_quantified": [],
  "climate_linkage_summary": "Potential future lawsuits related to climate change",
  "climate_linkage_quotes": ["those being brought by coastal communities against oil, coal and other fossil fuel producers relating to climate chan...

============================================================
STEP 5: SPECIFICITY
============================================================
vague disclosure

============================================================
PIPELINE COMPLETE
============================================================
Classification: yes, this is an instance of climate litigation disclosure
Specificity: vague disclosure

In [178]:
full_messages = result["full_messages"]

## Testing a pairwise comparison

In [ ]:
def pairwise (idx_1, idx_2, model = "meta-llama/llama-3.1-70b-instruct"):
    text_1 = all_results.iloc[idx_1]['text']
    text_2 = all_results.iloc[idx_2]['text']
    classification_1 = all_results.iloc[idx_1]['climate_litigation_binary']
    classification_2 = all_results.iloc[idx_2]['climate_litigation_binary']
    response_1 = run_single_text_pipeline(text_1, classification_1)
    response_2 = run_single_text_pipeline(text_2, classification_2)
    full_messages_1 = response_1["full_messages"]
    full_messages_2 = response_2["full_messages"]
    prompt_6 = get_prompt_6(full_messages_1, full_messages_2)
    pairwise_result = call_llm(SYSTEM_PROMPT, [{"role": "user", "content": prompt_6}], model)
    print(pairwise_result)
    last_prompt = get_prompt_7(pairwise_result)
    final_result = call_llm(SYSTEM_PROMPT, [{"role": "user", "content": last_prompt}], model)
    print(final_result)

    return final_result

In [203]:
pairwise(1, 2)

conversation history: [{'role': 'user', 'content': "Summarize the following text: In the event we declare a dividend, we will need to repay amounts deferred under the export credit facilities.\nCompliance and Regulatory Risks\nChanges in U.S. or other countries’ foreign travel policy have affected, and may continue to affect our results of operations.\nChanges in U.S. and other countries' foreign policy have in the past and could in the future result in the imposition of travel restrictions or travel bans on persons to certain countries or result in the imposition of travel advisories, warnings, rules, regulations or legislation exposing us to penalties or claims of monetary damages. In addition, some countries have previously adopted restrictions against U.S. travelers. The timing and scope of these changes and regulations can be unpredictable, and they could cause us to cancel scheduled sailings, possibly on short notice, or could result in litigation against us. This, in turn, could decrease our revenue, increase our operating costs and otherwise impair our profitability.\nFactors associated with climate change, including an increasing global regulatory focus, could adversely affect our business.\nThere is increasing global regulatory focus on climate change, greenhouse gas and other emissions. These regulatory efforts, both internationally and in the U.S., are still developing, including the international alignment of such efforts, and we cannot yet determine what the final regulatory programs or their impact will be on our business. However, such climate change-related regulatory activity in the future may adversely affect our business and financial results by requiring us to reduce our emissions, pay for our emissions, modify our itineraries and may increase our exposure, if any, to climate change-related litigation. Such activity may also impact us by increasing our operating costs, including fuel costs. For example, the European Union has proposed and enacted parts of a series of significant carbon reforms under its Fit for 55 package designed to meet its 2030 emission goals, which would require us, among other things, to increase the use of low carbon fuel onboard our vessels as well as connectivity to shore power. Part of the reforms that were enacted includes updates to the European Union Emission Trading System that imposes requirements on us to purchase carbon emission allowances for our qualified emissions beginning in 2024.\nIn addition, the U.S."}]

============================================================
STEP 1: SUMMARY
============================================================
Here is a summary of the text from a legal and environmental disclosure expert's perspective:

The company is disclosing several compliance and regulatory risks that could impact its business. These risks include:

1. Changes in foreign travel policies that could lead to travel restrictions, bans, or advisories, resulting in cancelled sailings, litigation, and decreased revenue.
2. Climate change-related regulatory efforts, both internationally and in the US, which could require the company to reduce emissions, pay for emissions, modify itineraries, and increase operating costs, including fuel costs.
3. Specific regulatory initiatives, such as the European Union's Fit for 55 package, which would require the company to increase the use of low-carbon fuel and connectivity to shore power, and purchase carbon emission allowances starting in 2024.

Overall, the company is highlighting the potential risks and uncertainties associated with changing regulatory landscapes, particularly with regards to climate change and foreign travel policies.

============================================================
STEP 2: CLASSIFICATION
============================================================
Based on the provided text, I would say that this is not climate litigation. The text discusses climate change-related regulatory efforts and potential risks to the company's business, but it does not mention any specific lawsuits, legal actions, or claims related to climate change.

The text mentions "climate change-related litigation" as a potential risk, but this is a general statement about the possibility of future litigation, rather than a disclosure of an actual lawsuit or legal action.

The text is more focused on disclosing the company's potential risks and uncertainties related to climate change regulations, rather than discussing any specific climate litigation. Therefore, I would classify this text as a climate-related regulatory risk disclosure, rather than climate litigation.

============================================================
STEP 3: VERIFICATION
============================================================
I acknowledge that the text was previously classified as "1", indicating that it was considered climate litigation.

============================================================
STEP 4: BREAKDOWN (raw)
============================================================
{
  "parties": [],
  "case_title_or_docket": null,
  "forum_or_jurisdiction": null,
  "statute_reg_policy": [],
  "procedural_posture": null,
  "dates_or_timeframes": [],
  "monetary_or_quantified": [],
  "climate_linkage_summary": "The company may be exposed to climate change-related litigation due to increasing global regulatory focus on climate change.",
  "climate_linkage_quotes": ["may increase our exposure, if any, to climate change-related litigation"],
  "checkable_elements": [],
  "who"...

============================================================
STEP 5: SPECIFICITY
============================================================
vague disclosure

============================================================
PIPELINE COMPLETE
============================================================
Classification: 1
Specificity: vague disclosure
conversation history: [{'role': 'user', 'content': 'Summarize the following text: However, such climate change-related regulatory activity in the future may adversely affect our business and financial results by requiring us to reduce our emissions, pay for our emissions, modify our itineraries and may increase our exposure, if any, to climate change-related litigation. Such activity may also impact us by increasing our operating costs, including fuel costs. For example, the European Union has proposed a series of significant carbon reforms under its Fit for 55 package designed to meet its 2030 emission goals, which would require us, among other things, to increase the use of low carbon fuel onboard our vessels as well as connectivity to shore power. The proposed legislation also includes updates to the European Union Emission Trading System which would impose requirements to purchase carbon emission allowances beginning in 2024. In addition, the U.S. and various state and foreign government or regulatory agencies have enacted, or may enact, environmental regulations or policies, such as requiring the use of low sulfur fuels (e.g., IMO Sulfur Limit) or the incoming carbon intensity indicator regulation, that have or could increase our direct cost to operate in certain markets, increase our cost of fuel, limit the supply of compliant fuel, cause us to incur significant expenses to purchase and/or develop new equipment and adversely impact the cruise vacation industry. If enacted, these regulations may individually or collectively have a material adverse effect on our business and results of operations due to increased costs associated with compliance and modified itineraries in the affected regions.\nThere has also been growing environmental scrutiny of the environmental impact of the cruise vacation industry, and some environmental groups are advocating for more stringent regulation of ship emissions at berth and at sea. This negative publicity of the cruise industry and any related measures may lead to changes in consumer preferences, such as methods or frequency of travel, which could adversely impact our operations and financial results and subject us to reputational impacts and costs.\nLabor, health and safety, financial responsibility and other maritime regulations and measures could affect operations and increase operating costs. We are subject to\nvarious international, national, state and local laws, regulations and treaties that govern, among other things, discharge from our ships, safety standards applicable to our ships, treatment of disabled persons, health and sanitary standards applicable to our guests, security standards on board our ships and at the ship/port interface areas, and financial responsibilities to our guests. These issues are, and we believe will continue to be, an area of focus by the relevant authorities throughout the world.'}]

============================================================
STEP 1: SUMMARY
============================================================
Here is a summary of the text:

The company is warning that future climate change-related regulations may negatively impact its business and financial results. These regulations, such as the European Union's Fit for 55 package and the US's environmental regulations, may require the company to reduce emissions, pay for emissions, and modify its itineraries, leading to increased operating costs, including fuel costs. Additionally, growing environmental scrutiny of the cruise industry may lead to negative publicity, changes in consumer preferences, and reputational impacts. The company is also subject to various international, national, and local regulations related to labor, health and safety, financial responsibility, and maritime operations, which could increase operating costs and affect operations.

============================================================
STEP 2: CLASSIFICATION
============================================================
Based on the provided text, I would say that this is not climate litigation. The text mentions "climate change-related litigation" as a potential risk, but it does not describe an actual lawsuit or legal action. Instead, it discusses the potential impact of future climate change-related regulations on the company's business and financial results.

The text does mention "growing environmental scrutiny" and "negative publicity" related to the cruise industry's environmental impact, but it does not describe a specific lawsuit or legal action. It also mentions various regulations and laws that the company is subject to, but again, this is not climate litigation.

According to the definition provided, climate litigation refers to "legal actions that materially concern climate change science, policy, or law." This text does not describe a legal action, but rather discusses the potential risks and impacts of future regulations and public scrutiny.

============================================================
STEP 3: VERIFICATION
============================================================
I acknowledge that the text was previously classified as "1", indicating that it was considered climate litigation, despite my initial assessment that it was not.

============================================================
STEP 4: BREAKDOWN (raw)
============================================================
{
  "parties": [],
  "case_title_or_docket": null,
  "forum_or_jurisdiction": null,
  "statute_reg_policy": [],
  "procedural_posture": null,
  "dates_or_timeframes": [],
  "monetary_or_quantified": [],
  "climate_linkage_summary": "The company may be exposed to climate change-related litigation.",
  "climate_linkage_quotes": ["may increase our exposure, if any, to climate change-related litigation"],
  "checkable_elements": [],
  "who": null,
  "what": null,
  "where": null,
  "when": null,
  "...

============================================================
STEP 5: SPECIFICITY
============================================================
vague disclosure

============================================================
PIPELINE COMPLETE
============================================================
Classification: 1
Specificity: vague disclosure
Both texts are classified as climate litigation, but they do not provide specific details about actual lawsuits or legal actions. However, Text 1 provides more context about the potential risks and uncertainties associated with changing regulatory landscapes, particularly with regards to climate change and foreign travel policies. Text 2 mentions climate change-related litigation as a potential risk, but it does not provide any specific details.

FINAL: text 1
text 1

'text 1'

# Testing

We are going to test by seeing which model best maintains transitivity. Because LLMs are famously bad at this, this will give us a good sense as to whether it is doing a good job. 

Transitivity can be understood as: if an LLM says text 1 is more specific than text 2, and that text 2 is more specific than text 3, then it should also say text 1 is more specific than text 3.

To do this, we will give 15 sentences to 10 models. All 15 sentences will be compared against all other sentences. We will ignore needing to test them in opposite order (ie. sentence 1 v sentence 2 and sentence 2 v sentence 1). This means we will have a total of Σ(i) from i=1 to 14 which is 105 combinations. In total, this will give us 1050 combinations. However, we do not need to recompute the single responses each time. So we will do that in isolation and then have a slimmer pairwise comparison function.

In [248]:
def slimmer_pairwise(breakdown_1, breakdown_2, model = "meta-llama/llama-3.1-70b-instruct"):
    prompt_6 = get_prompt_6(breakdown_1, breakdown_2)
    pairwise_result = call_llm(SYSTEM_PROMPT, [{"role": "user", "content": prompt_6}], model)
    print(pairwise_result)
    last_prompt = get_prompt_7(pairwise_result)
    print(last_prompt)
    final_result = call_llm(SYSTEM_PROMPT, [{"role": "user", "content": last_prompt}], model)
    print(final_result)

    return pairwise_result, final_result

In [207]:
def run_and_save_one_text(idx, folder, model): 
    text = all_results.iloc[idx]['text']
    classification = all_results.iloc[idx]['climate_litigation_binary']
    response = run_single_text_pipeline(text, classification, model)
    full_messages = response["full_messages"]
    # Sanitize model name for filename (replace / and spaces with _)
    safe_model = str(model).replace("/", "_").replace(" ", "_")
    with open(f"{folder}/full_messages_{idx}_{safe_model}.txt", "w") as f:
        f.write(full_messages)
    return full_messages

In [ ]:
model_list = [
    "meta-llama/llama-3.2-1b-instruct", #0.005/M input tokens, $0.01/M output tokens
    "liquid/lfm-7b", #$0.01/M input tokens, $0.01/M output tokens
    "meta-llama/llama-3.2-3b-instruct", #$0.01/M input tokens, $0.02/M output
    "mistralai/mistral-nemo", #$0.01/M input tokens, $0.027/M output tokens
    "liquid/lfm-3b", #$0.02/M input tokens, $0.02/M output tokens
    "meta-llama/llama-3.1-8b-instruct", #$0.019/M input tokens, $0.03/M output tokens
    "google/gemma-3-4b-it", #$0.02/M input tokens, $0.04/M output tokens
    "sao10k/l3-lunaris-8b", #$0.02/M input tokens, $0.05/M output tokens
    "nousresearch/hermes-2-pro-llama-3-8b", #$0.025/M input tokens, $0.04/M output tokens
    "mistralai/mistral-7b-instruct", # $0.028/M input tokens, $0.054/M output tokens
]

In [212]:
import os

output_folder = "../outputs"
os.makedirs(output_folder, exist_ok=True)

for model in model_list:
    print(f"Running model: {model}")
    for idx in range(15):
        print(f"Processing sentence {idx} with model {model}")
        run_and_save_one_text(idx, folder=output_folder, model=model)

Running model: meta-llama/llama-3.2-1b-instruct
Processing sentence 0 with model meta-llama/llama-3.2-1b-instruct
conversation history: [{'role': 'user', 'content': 'Summarize the following text: or other countries’ foreign travel policy have affected, and may continue to affect our results of operations.\nChanges in U.S. and other countries\' foreign policy have in the past and could in the future result in the imposition of travel restrictions or travel bans on persons to certain countries or result in the imposition of travel advisories, warnings, rules, regulations or legislation exposing us to penalties or claims of monetary damages. In addition, some countries have previously adopted restrictions against U.S. travelers. The timing and scope of these changes and regulations can be unpredictable, and they could cause us to cancel scheduled sailings, possibly on short notice, or could result in litigation against us. This, in turn, could decrease our revenue, increase our operating costs and otherwise impair our profitability.\nFactors associated with climate change, including an increasing global regulatory focus, could adversely affect our business.\nThere is increasing global regulatory focus on climate change, greenhouse gas and other emissions, and new laws and regulations are expanding mandatory disclosure, reporting and diligence requirements. These regulatory efforts, both internationally, regionally and nationally, are still developing, including the international alignment of such efforts, and we cannot yet determine what the final regulatory programs or their impact will be on our business. However, such climate change-related regulatory activity in the future may adversely affect our business and financial results by requiring us to reduce our emissions, pay for our emissions, modify our itineraries and may increase our exposure, if any, to climate change-related litigation. Such activity may also impact us by increasing our operating costs, including fuel costs. For example, the European Union has enacted parts of a series of significant carbon reforms under its Fit for 55 package designed to meet its 2030 emission goals, which would require us, among other things, to purchase emission allowances, increase the use of low carbon fuel onboard our vessels as well as connectivity to shore power.\nIn addition, various state, regional and foreign government or regulatory agencies have enacted, or may enact, environmental regulations or policies, such as requiring the use of low sulfur fuels (e.g., IMO Sulfur Limit) or the carbon intensity indicator regulation ("CII"), that have or could increase our direct cost to operate in certain markets, increase our cost of fuel, limit the supply of compliant fuel, cause us to incur significant expenses to purchase and/or develop new equipment and adversely impact the cruise vacation industry.'}]

============================================================
STEP 1: SUMMARY
============================================================
The text discusses the potential impact of changes in foreign travel policies and climate change-related regulations on the company's business operations. Specifically, it highlights the following risks:

1. Changes in foreign travel policies, including travel restrictions, bans, and advisories, which could lead to:
	* Cancellation of scheduled sailings
	* Litigation and potential monetary damages
	* Decreased revenue and increased operating costs
2. Climate change-related regulations, including:
	* Mandatory disclosure, reporting, and diligence requirements
	* Emissions reduction and reporting requirements
	* Increased fuel costs
	* Potential for litigation related to climate change
	* Need to modify itineraries and purchase emission allowances

These regulations, both internationally and domestically, may require the company to:

* Reduce emissions
* Pay for emissions
* Increase the use of low-carbon fuel
* Develop new equipment and technologies
* Incur significant expenses to comply with regulations

Overall, the text suggests that the company is vulnerable to disruptions and increased costs due to changes in foreign travel policies and climate change-related regulations, which could impact its financial results and profitability.

============================================================
STEP 2: CLASSIFICATION
============================================================
Based on the provided text, I would assess that the original text is not climate litigation. While the text does mention climate change-related regulations and the potential for litigation related to climate change, the language used is more focused on the potential impacts of these regulations on the company's business operations, rather than a specific lawsuit or legal action.

The text mentions the potential for "climate change-related litigation" as a possible consequence of the regulations, but this is not presented as a specific lawsuit or claim, but rather as a potential risk or exposure. The text also highlights the potential for increased costs, disruptions, and decreased revenue due to these regulations, but does not describe a specific legal action or lawsuit.

In contrast, climate litigation typically involves a specific lawsuit or claim that alleges a company has failed to disclose climate-related risks or impacts, or has engaged in climate-related misconduct. The original text does not meet this definition, and therefore I would not classify it as climate litigation.

============================================================
STEP 3: VERIFICATION
============================================================
The text was previously classified as Climate Litigation.

============================================================
STEP 4: BREAKDOWN (raw)
============================================================
{
  "parties": ["U.S. travelers", "the company"],
  "case_title_or_docket": null,
  "forum_or_jurisdiction": null,
  "statute_reg_policy": ["climate change-related regulations", "Fit for 55 package"],
  "procedural_posture": "potential for litigation",
  "dates_or_timeframes": null,
  "monetary_or_quantified": null,
  "climate_linkage_summary": "climate change-related litigation",
  "climate_linkage_quotes": ["may increase our exposure, if any, to climate change-related litigation"],
  "checkabl...

============================================================
STEP 5: SPECIFICITY
============================================================
detailed disclosure

============================================================
PIPELINE COMPLETE
============================================================
Classification: 1
Specificity: detailed disclosure
Processing sentence 1 with model meta-llama/llama-3.2-1b-instruct
conversation history: [{'role': 'user', 'content': "Summarize the following text: In the event we declare a dividend, we will need to repay amounts deferred under the export credit facilities.\nCompliance and Regulatory Risks\nChanges in U.S. or other countries’ foreign travel policy have affected, and may continue to affect our results of operations.\nChanges in U.S. and other countries' foreign policy have in the past and could in the future result in the imposition of travel restrictions or travel bans on persons to certain countries or result in the imposition of travel advisories, warnings, rules, regulations or legislation exposing us to penalties or claims of monetary damages. In addition, some countries have previously adopted restrictions against U.S. travelers. The timing and scope of these changes and regulations can be unpredictable, and they could cause us to cancel scheduled sailings, possibly on short notice, or could result in litigation against us. This, in turn, could decrease our revenue, increase our operating costs and otherwise impair our profitability.\nFactors associated with climate change, including an increasing global regulatory focus, could adversely affect our business.\nThere is increasing global regulatory focus on climate change, greenhouse gas and other emissions. These regulatory efforts, both internationally and in the U.S., are still developing, including the international alignment of such efforts, and we cannot yet determine what the final regulatory programs or their impact will be on our business. However, such climate change-related regulatory activity in the future may adversely affect our business and financial results by requiring us to reduce our emissions, pay for our emissions, modify our itineraries and may increase our exposure, if any, to climate change-related litigation. Such activity may also impact us by increasing our operating costs, including fuel costs. For example, the European Union has proposed and enacted parts of a series of significant carbon reforms under its Fit for 55 package designed to meet its 2030 emission goals, which would require us, among other things, to increase the use of low carbon fuel onboard our vessels as well as connectivity to shore power. Part of the reforms that were enacted includes updates to the European Union Emission Trading System that imposes requirements on us to purchase carbon emission allowances for our qualified emissions beginning in 2024.\nIn addition, the U.S."}]

============================================================
STEP 1: SUMMARY
============================================================
The text discusses potential risks and challenges that the company may face in the future. Specifically, it highlights the following:

1. Compliance and Regulatory Risks:
	* Changes in foreign travel policies and regulations could impact the company's operations and profitability.
	* The company may be subject to penalties or claims of monetary damages due to travel restrictions or bans.
2. Climate Change Risks:
	* Increasing global regulatory focus on climate change and emissions could adversely affect the company's business and financial results.
	* The company may be required to reduce emissions, pay for emissions, modify itineraries, and increase operating costs, including fuel costs.
	* The company may also face climate change-related litigation and increased exposure to climate change-related risks.

Overall, the text suggests that the company is aware of potential risks and challenges that could impact its operations and profitability, and is taking steps to mitigate these risks.

============================================================
STEP 2: CLASSIFICATION
============================================================
Based on the provided text, I would assess that the climate-related risks mentioned are not necessarily indicative of climate litigation. While the text mentions that the company may face climate change-related litigation, the specific examples provided do not necessarily fit the definition of climate litigation.

Climate litigation typically involves lawsuits that directly challenge a company's actions or policies related to climate change, such as:

* Lawsuits targeting false or misleading climate claims (e.g. greenwashing)
* Legal actions over a company's contribution to climate-related impacts
* Efforts to force climate alignment through human rights or fiduciary duty arguments

In contrast, the text mentions that the company may be required to reduce emissions, pay for emissions, modify itineraries, and increase operating costs, which are more related to regulatory compliance and risk management. The text also mentions that the company may face increased exposure to climate change-related risks, but this is not necessarily a lawsuit.

The only potentially litigious aspect mentioned in the text is the potential for litigation against the company due to travel restrictions or bans, but this is not directly related to climate change.

Therefore, I would conclude that the climate-related risks mentioned in the text are more related to regulatory compliance and risk management, rather than climate litigation.

============================================================
STEP 3: VERIFICATION
============================================================
I have taken note of the original classification of the text as Climate Litigation Risk (Classification: 1).

============================================================
STEP 4: BREAKDOWN (raw)
============================================================
{
  "parties": [
    "Company",
    "U.S.",
    "European Union"
  ],
  "case_title_or_docket": null,
  "forum_or_jurisdiction": null,
  "statute_reg_policy": [
    "U.S. regulations",
    "EU regulations"
  ],
  "procedural_posture": null,
  "dates_or_timeframes": [
    "past",
    "future"
  ],
  "monetary_or_quantified": [
    "penalties",
    "damages"
  ],
  "climate_linkage_summary": "Climate change-related regulatory activity may adversely affect business and financial results",
  "climat...
⚠️  Invalid JSON, attempting repair...

============================================================
STEP 5: SPECIFICITY
============================================================
not climate litigation

============================================================
PIPELINE COMPLETE
============================================================
Classification: 1
Specificity: not climate litigation
Processing sentence 2 with model meta-llama/llama-3.2-1b-instruct
conversation history: [{'role': 'user', 'content': 'Summarize the following text: However, such climate change-related regulatory activity in the future may adversely affect our business and financial results by requiring us to reduce our emissions, pay for our emissions, modify our itineraries and may increase our exposure, if any, to climate change-related litigation. Such activity may also impact us by increasing our operating costs, including fuel costs. For example, the European Union has proposed a series of significant carbon reforms under its Fit for 55 package designed to meet its 2030 emission goals, which would require us, among other things, to increase the use of low carbon fuel onboard our vessels as well as connectivity to shore power. The proposed legislation also includes updates to the European Union Emission Trading System which would impose requirements to purchase carbon emission allowances beginning in 2024. In addition, the U.S. and various state and foreign government or regulatory agencies have enacted, or may enact, environmental regulations or policies, such as requiring the use of low sulfur fuels (e.g., IMO Sulfur Limit) or the incoming carbon intensity indicator regulation, that have or could increase our direct cost to operate in certain markets, increase our cost of fuel, limit the supply of compliant fuel, cause us to incur significant expenses to purchase and/or develop new equipment and adversely impact the cruise vacation industry. If enacted, these regulations may individually or collectively have a material adverse effect on our business and results of operations due to increased costs associated with compliance and modified itineraries in the affected regions.\nThere has also been growing environmental scrutiny of the environmental impact of the cruise vacation industry, and some environmental groups are advocating for more stringent regulation of ship emissions at berth and at sea. This negative publicity of the cruise industry and any related measures may lead to changes in consumer preferences, such as methods or frequency of travel, which could adversely impact our operations and financial results and subject us to reputational impacts and costs.\nLabor, health and safety, financial responsibility and other maritime regulations and measures could affect operations and increase operating costs. We are subject to\nvarious international, national, state and local laws, regulations and treaties that govern, among other things, discharge from our ships, safety standards applicable to our ships, treatment of disabled persons, health and sanitary standards applicable to our guests, security standards on board our ships and at the ship/port interface areas, and financial responsibilities to our guests. These issues are, and we believe will continue to be, an area of focus by the relevant authorities throughout the world.'}]

============================================================
STEP 1: SUMMARY
============================================================
The text discusses the potential impact of climate change-related regulatory activity on the cruise industry. Specifically, it highlights the following risks:

1. Increased costs associated with reducing emissions, purchasing carbon credits, and modifying itineraries to comply with regulations such as the European Union's Fit for 55 package.
2. Potential for increased exposure to climate change-related litigation.
3. Increased operating costs, including fuel costs, due to regulations such as the IMO Sulfur Limit and the incoming carbon intensity indicator regulation.
4. Limitations on the supply of compliant fuel, which could lead to significant expenses to purchase and/or develop new equipment.
5. Negative publicity and reputational impacts due to environmental scrutiny of the industry.
6. Changes in consumer preferences, which could adversely impact operations and financial results.
7. Compliance with various international, national, state, and local laws and regulations, including maritime regulations, which could increase operating costs and subject the company to reputational impacts.

Overall, the text suggests that climate change-related regulatory activity could have a material adverse effect on the company's business and financial results.

============================================================
STEP 2: CLASSIFICATION
============================================================
Based on the provided text, I would assess that the original text is not a clear example of climate litigation. While it mentions the potential for increased exposure to climate change-related litigation, the text does not explicitly state that the company is facing a lawsuit or legal action related to climate change.

The text primarily discusses the potential regulatory and operational impacts of climate change-related activity on the company's business and financial results, such as increased costs, modified itineraries, and reputational impacts. The language used is more focused on the potential consequences of regulatory changes and environmental scrutiny, rather than a specific legal action.

However, the text does mention that the company may be subject to "climate change-related litigation" as a potential risk, but this is not a clear or direct reference to a specific lawsuit or legal action. Therefore, I would not classify the original text as a clear example of climate litigation.

============================================================
STEP 3: VERIFICATION
============================================================
I have taken note of the original classification of the text as climate litigation, specifically a 1, indicating that the text was previously classified as a clear example of climate litigation.

============================================================
STEP 4: BREAKDOWN (raw)
============================================================
{
  "parties": ["cruise industry", "environmental groups"],
  "case_title_or_docket": null,
  "forum_or_jurisdiction": null,
  "statute_reg_policy": ["Fit for 55 package", "European Union Emission Trading System", "IMO Sulfur Limit", "carbon intensity indicator regulation"],
  "procedural_posture": null,
  "dates_or_timeframes": ["2024"],
  "monetary_or_quantified": null,
  "climate_linkage_summary": "climate change-related litigation",
  "climate_linkage_quotes": ["may increase our exposure, if...

============================================================
STEP 5: SPECIFICITY

Now that we have all the slimmer outputs, we can perform the pairwise comparisons.

In [215]:
# Search in the output folder for any file name that contains the model name string

model_name = "google/gemma-3-4b-it"
matching_files = [f for f in os.listdir(output_folder) if model_name.replace("/", "_").replace(" ", "_") in f]
print("Matching files:", matching_files)
print(len(matching_files))

Matching files: ['full_messages_14_google_gemma-3-4b-it.txt', 'full_messages_10_google_gemma-3-4b-it.txt', 'full_messages_2_google_gemma-3-4b-it.txt', 'full_messages_6_google_gemma-3-4b-it.txt', 'full_messages_7_google_gemma-3-4b-it.txt', 'full_messages_3_google_gemma-3-4b-it.txt', 'full_messages_11_google_gemma-3-4b-it.txt', 'full_messages_1_google_gemma-3-4b-it.txt', 'full_messages_5_google_gemma-3-4b-it.txt', 'full_messages_9_google_gemma-3-4b-it.txt', 'full_messages_13_google_gemma-3-4b-it.txt', 'full_messages_12_google_gemma-3-4b-it.txt', 'full_messages_4_google_gemma-3-4b-it.txt', 'full_messages_0_google_gemma-3-4b-it.txt', 'full_messages_8_google_gemma-3-4b-it.txt']
15

In [ ]:
#open these matching files and save them to a dataframe where the first column is the file name and the second column is the full message

rows = []
for file in matching_files:
    with open(os.path.join(output_folder, file), "r") as f:
        rows.append({"file_name": file, "full_message": f.read()})
full_messages_df = pd.DataFrame(rows, columns=["file_name", "full_message"])

,file_name,full_message
0,full_messages_14_google_gemma-3-4b-it.txt,\n============================================...
1,full_messages_10_google_gemma-3-4b-it.txt,\n============================================...
2,full_messages_2_google_gemma-3-4b-it.txt,\n============================================...
3,full_messages_6_google_gemma-3-4b-it.txt,\n============================================...
4,full_messages_7_google_gemma-3-4b-it.txt,\n============================================...

In [381]:
#wrap this in a function 
def load_full_messages(model_name, output_folder):
    matching_files = [f for f in os.listdir(output_folder) if model_name.replace("/", "_").replace(" ", "_") in f]
    rows = []
    for file in matching_files:
        with open(os.path.join(output_folder, file), "r") as f:
            rows.append({"file_name": file, "full_message": f.read()})
    return pd.DataFrame(rows, columns=["file_name", "full_message"])

In [220]:
gemma_df = load_full_messages("google/gemma-3-4b-it")

In [243]:
# Now, within the given df, perform pairwise comparisons and save results in a dataframe

def by_model_pairwise(df):
    results = []
    pairwise_results_df = pd.DataFrame(columns=["idx_1", "idx_2", "reasoning", "result"])

    for idx_1 in range(15):
        for idx_2 in range(idx_1 + 1, 15):
            # Check if this pair has already been computed in this run
            already_done = (
                ((pairwise_results_df["idx_1"] == idx_1) & (pairwise_results_df["idx_2"] == idx_2)).any()
            )
            if already_done:
                continue
            print(f"Comparing sentence {idx_1} with sentence {idx_2}")
            # Extract the full message text for each index
            breakdown_1 = df[df['file_name'].str.contains(f'full_messages_{idx_1}_')]['full_message'].values[0]
            breakdown_2 = df[df['file_name'].str.contains(f'full_messages_{idx_2}_')]['full_message'].values[0]
            full_result, binary_result = slimmer_pairwise(breakdown_1, breakdown_2, model="google/gemma-3-4b-it")
            results.append({
                "idx_1": idx_1,
                "idx_2": idx_2,
                "reasoning" : full_result,
                "result": binary_result
            })
            # Update the dataframe after each comparison
            pairwise_results_df = pd.DataFrame(results, columns=["idx_1", "idx_2", "reasoning", "result"])
    
    return pairwise_results_df

In [245]:
pairwise_results_dfs = {}
for model in model_list:
    model_df = load_full_messages(model)
    print(f"Loaded {len(model_df)} rows for model: {model}")
    if len(model_df) != 15:
        print(f"Error: load_full_messages for model '{model}' returned {len(model_df)} rows instead of 15.")
        continue
    pairwise_results_df = by_model_pairwise(model_df)
    pairwise_results_dfs[model] = pairwise_results_df

Loaded 15 rows for model: meta-llama/llama-3.2-1b-instruct
Comparing sentence 0 with sentence 1
The provided text primarily discusses potential regulatory risks and business impacts related to foreign travel policies and climate change, rather than a specific legal action or claim. While it mentions the *possibility* of climate change-related litigation, it lacks the specific details (parties, dates, legal arguments, etc.) necessary to classify it as a concrete climate litigation case.

FINAL: text 1
text 1

Comparing sentence 0 with sentence 2
The breakdown JSON provides a detailed level of specificity, identifying key statutes, regulations, and potential parties involved in the discussion of climate-related risks. It includes specific dates (2024) and clearly outlines the potential for litigation. The climate linkage is explicitly stated, and the elements are directly traceable to climate change concerns.

FINAL: text 2
text 2

Comparing sentence 0 with sentence 3
The breakdown provides a relatively detailed level of specificity, identifying key parties involved (including the litigation itself), specific dates, and the nature of the loss contingency. While not providing precise monetary amounts or a court docket number, it does offer a clear connection to a climate-related legal matter – the Havana Docks litigation – and outlines the specific aspect of the litigation being disclosed (legal fees and costs). The inclusion of the acquiring company and the previous name of the entity involved adds to the contextual clarity.

FINAL: text 2
text 2

Comparing sentence 0 with sentence 4
The text explicitly details lawsuits filed by states and municipalities seeking damages related to climate change impacts, directly aligning with the definition of climate litigation. The breakdown accurately captures these elements, including the parties involved, the legal posture, and the sought outcome.

FINAL: text 2
text 2

Comparing sentence 0 with sentence 5
The text primarily focuses on potential risks related to regulatory changes and public perception, rather than specific legal actions or claims. While it mentions the possibility of litigation, it’s framed as a consequence of broader issues like increased regulatory scrutiny and public pressure. The details provided are largely about potential financial and operational impacts, not the specifics of a legal case.

FINAL: text 2
text 2

Comparing sentence 0 with sentence 6
The breakdown provides a detailed list of parties, forum, statutes, and procedural postures, but the core climate litigation element is encapsulated in the "climate_linkage_summary" field. This summary clearly identifies the lawsuits as a central aspect of the legal risks discussed.

FINAL: text 2
text 2

Comparing sentence 0 with sentence 7
The breakdown JSON provides a detailed level of specificity, including specific parties involved (states, municipalities, producers), the nature of the legal action (seeking money damages for remedial measures), and the underlying legal basis (environmental laws and regulations related to climate change). The inclusion of “close to two dozen lawsuits” adds a quantifiable element. The text clearly outlines a potential legal challenge directly linked to climate impacts.

FINAL: text 2
text 2

Comparing sentence 0 with sentence 8
Rationale: The text primarily discusses the potential impacts of climate regulations on a company's business, focusing on regulatory changes, potential costs, and shifts in market demand. While it mentions litigation as a *potential* outcome, it doesn't detail any specific legal action, claims, or parties involved. The disclosures are broad and descriptive of regulatory risk rather than a specific legal dispute.

FINAL: text 1
Okay, please provide the text. I’m ready to analyze it and determine the final decision as you’ve outlined.

Comparing sentence 0 with sentence 9
The breakdown JSON provides a detailed level of specificity, identifying specific parties involved (CNX, communities, fossil fuel producers), a specific type of legal action (climate change lawsuits), and the forum (courts). It also includes the relevant statute/policy (climate change) and procedural posture (defending actions). The inclusion of quotes directly from the text strengthens the claim of detailed disclosure.

FINAL: text 2
text 2

Comparing sentence 0 with sentence 10
Rationale: The text primarily focuses on financial reporting details (derivative settlements, interest rate swaps, and accruals for potential liabilities) rather than specific legal actions or claims directly related to climate change. While "climate change" is listed as a potential liability, there are no details about the nature of the claims, parties involved, or legal basis, making it a general mention rather than a detailed disclosure of climate litigation.

FINAL: text 2
Okay, I understand. Please provide the text.

Comparing sentence 0 with sentence 11
Text 2 is more specific in its discussion of climate litigation. While Text 1 mentions climate change-related regulations and potential litigation, Text 2 explicitly details the existence of over 30 lawsuits against oil and gas producers for climate-related damages, references specific legal frameworks (like Note 20), and outlines the types of liability involved (joint and several, strict liability, etc.). Text 1 is more general and focuses on the broader impacts of regulations rather than the specifics of ongoing legal action.

FINAL: text 2
text 2

Comparing sentence 0 with sentence 12
Rationale: The breakdown provides specific details regarding regulatory actions (Clean Air Act, IRA, methane emissions charge), dates, and monetary amounts related to climate change. While it doesn't present a specific legal case, it offers a level of detail beyond a general mention of climate risks, indicating a more thorough disclosure of the relevant legal and policy landscape.

FINAL: text 2
Okay, I understand. Please provide the text.

Comparing sentence 0 with sentence 13
The breakdown provides specific details regarding the company’s involvement in climate change lawsuits, the amount of its long-term debt, and the potential impact of these factors on its financial condition. The inclusion of specific monetary figures ($500 million, $500 million, $350 million) and the identification of specific legal actions (climate change lawsuits) elevates the disclosure beyond a general statement about climate risk. The breakdown also clearly identifies the parties involved (CNX, communities, fossil fuel producers) and the forum (courts).

FINAL: text 2
text 2

Comparing sentence 0 with sentence 14
The provided breakdown identifies the core climate-related elements – the EPA’s proposed regulations, the potential for increased costs due to climate policies, and the existence of lawsuits seeking to hold oil and gas producers accountable for climate damages. While the text discusses broader regulatory and ESG concerns, the focus on climate change and potential legal challenges makes “climate_linkage_summary” the most appropriate classification.

FINAL: text 2
text 2

Comparing sentence 1 with sentence 2
The breakdown provides specific details regarding potential regulatory impacts (Fit for 55, EU ETS, IMO Sulfur Limit, carbon intensity indicator) and mentions a potential for climate change-related litigation. While the text doesn't detail a specific lawsuit, the inclusion of "climate change-related litigation" as a risk factor, coupled with the specific regulations discussed, elevates the level of specificity beyond a simple mention of climate risk. The identified parties (cruise industry, environmental groups) and the regulatory frameworks (statutes/regulations) are clearly defined.

FINAL: text 2
text 2

Comparing sentence 1 with sentence 3
The breakdown provides specific parties involved (Havana Docks litigation, etc.), dates (July 9, 2020, first quarter of 2021), and a clear description of the litigation itself – a loss contingency recorded with related legal fees. While the text doesn't explicitly link the litigation to climate change, the fact that it’s identified as an ongoing legal matter with associated costs qualifies it as more than a vague disclosure.

FINAL: text 2
text 2

Comparing sentence 1 with sentence 4
The text explicitly details lawsuits filed by states and municipalities seeking damages related to climate change impacts, directly aligning with the definition of climate litigation. The breakdown accurately captures this key element.

FINAL: text 2
text 2

Comparing sentence 1 with sentence 5
The text discusses potential risks related to regulatory changes impacting derivative usage and negative public perception concerning environmental impacts. While it highlights increased regulatory scrutiny and potential litigation risks stemming from these factors, it doesn't present a specific legal action or challenge directly targeting climate change. The identified parties and potential outcomes are broad and relate to general regulatory compliance and public relations, rather than a focused climate litigation case.

FINAL: text 2
text 2

Comparing sentence 1 with sentence 6
The breakdown clearly identifies "climate change lawsuits" as a key element of the text's legal risks, directly addressing climate change. The other categories (tax risks, litigation defenses) are broader legal considerations that don't specifically focus on climate litigation.

FINAL: text 2
text 2

Comparing sentence 1 with sentence 7
The breakdown provides specific details regarding potential legal liabilities related to climate change, including lawsuits filed by states and municipalities seeking damages. It identifies the parties involved (producers of oil and gas), the type of legal action (seeking money damages), and the underlying cause (climate change consequences). The inclusion of "close to two dozen lawsuits" adds a quantifiable element.

FINAL: text 2
text 2

Comparing sentence 1 with sentence 8
Rationale: The text primarily discusses the potential impacts of climate regulations and policy changes on a company's business, particularly within the natural gas sector. While it mentions “climate change-related litigation” in the context of regulatory activity, the core content focuses on regulatory risk assessment and the potential for legal challenges arising from those regulations, rather than a specific litigation case. The details provided are broad and descriptive of regulatory trends, lacking the specific factual elements (parties, dates, monetary amounts, etc.) typically found in a litigation document.

FINAL: text 1
Okay, I understand. Please provide the text.

Comparing sentence 1 with sentence 9
detailed disclosure

The breakdown provides specific parties involved (CNX, communities, fossil fuel producers), identifies a specific type of legal action (climate change lawsuits), and points to a specific forum (courts). While the details are not exhaustive (no dates, monetary amounts, or specific statutes), the level of detail regarding the climate litigation aspect is significantly higher than in the first text, which primarily focuses on regulatory risk management. The inclusion of "four climate change lawsuits" adds a degree of falsifiability that is absent in the first text.

FINAL: text 2
text 2

Comparing sentence 1 with sentence 10
The text references "climate change" and "environmental violations" within a broader discussion of lawsuits and claims. However, there are no specific legal actions, parties involved, or quantifiable damages related to climate litigation. The references are general and lack the precision required for a more detailed disclosure.

FINAL: text 2
text 2

Comparing sentence 1 with sentence 11
Text 2 is a more specific disclosure regarding climate litigation. While Text 1 mentions climate change risks and regulatory activity, Text 2 directly references over 30 lawsuits filed against oil and gas producers for climate-related damages, citing a specific note in the company's financial statements. This provides a concrete example of climate litigation, unlike Text 1's more general discussion of potential future risks.

FINAL: text 2
text 2

Comparing sentence 1 with sentence 12
Rationale: This text provides a relatively detailed breakdown of climate-related regulatory changes, including specific regulations (Clean Air Act, IRA), dates (2013, 2024, etc.), and monetary amounts (e.g., $900 per ton of methane). It clearly links these changes to potential impacts on the natural gas market and the company's securities. The inclusion of multiple regulatory actions and their timelines demonstrates a higher level of specificity than the first text, which primarily focuses on general compliance risks.

FINAL: text 2
Okay, I understand. Please provide the text.

Comparing sentence 1 with sentence 13
The provided JSON accurately captures the key details related to potential climate litigation risks disclosed in the text. It identifies the parties involved (CNX, communities, fossil fuel producers), the forum (courts), and the relevant statute/policy (climate change). The inclusion of monetary amounts ($500 million, etc.) and the timeframe ("beginning to gain prevalence") adds to the specificity. While the checkable elements are currently empty, the structure is well-defined and suitable for further refinement.

FINAL: text 2
text 2

Comparing sentence 1 with sentence 14
The provided breakdown details regulatory actions and potential costs related to climate change mitigation efforts within the oil and gas industry. While it discusses lawsuits, these are presented as a consequence of climate-related policies rather than the core of a climate litigation case. The focus is on the *effects* of climate policy, not the legal challenge to the policy itself.

FINAL: text 2
text 2

Comparing sentence 2 with sentence 3
The breakdown provides a reasonable level of specificity, identifying key parties involved (the litigation, the holding company, the cruise line), dates, and the nature of the legal issue (a loss contingency). While it lacks precise details like a court name or specific legal claims, it does a good job of isolating the climate-related aspect within the broader financial disclosures. The inclusion of the litigation name as a key element strengthens the specificity.

FINAL: text 1
text 1

Comparing sentence 2 with sentence 4
The text explicitly details lawsuits seeking liability for climate-related damages, referencing "climate change" and "damages caused by climate change." This directly aligns with the definition of climate litigation.

FINAL: text 2
text 2

Comparing sentence 2 with sentence 5
The text primarily focuses on potential regulatory and reputational risks stemming from climate change, specifically concerning derivative instruments and public perception. While it mentions increased regulatory scrutiny and the potential for litigation, these are framed as consequences of broader environmental concerns rather than specific legal actions targeting climate change. The text lacks the precision of a true climate litigation disclosure, including details about parties involved in a lawsuit, specific statutes or regulations being challenged, or quantifiable damages sought.

FINAL: text 2
text 2

Comparing sentence 2 with sentence 6
The breakdown provides a detailed list of parties, statutes, and potential legal outcomes, but the core climate litigation element is encapsulated in the "climate_linkage_summary" field. This summary directly addresses the lawsuits and their potential impact, making it the most specific descriptor of the climate litigation aspect within the text.

FINAL: text 2
text 2

Comparing sentence 2 with sentence 7
The provided text exhibits a high degree of specificity regarding climate litigation. It identifies specific statutes (e.g., environmental laws and regulations, climate change), outlines the parties involved (producers of oil, natural gas, and coal, various states and municipalities), details the procedural posture (seeking money damages for remedial measures), and references a concrete number of lawsuits ("close to two dozen"). The text also clearly links the legal actions to the consequences of climate change.

FINAL: text 2
text 2

Comparing sentence 2 with sentence 8
Rationale: The text primarily discusses the potential impacts of climate regulations on a company's business, specifically focusing on the natural gas industry and the regulatory landscape surrounding greenhouse gas emissions. While it mentions potential litigation risks, it lacks specific details about ongoing lawsuits, legal claims, or the nature of any legal action. The disclosures are largely descriptive of regulatory trends and potential consequences rather than concrete legal proceedings.

FINAL: text 2
Okay, I understand. Please provide the text.

Comparing sentence 2 with sentence 9
The breakdown JSON provides a relatively detailed level of specificity, identifying key parties involved (CNX, communities, fossil fuel producers), a specific type of legal action (climate change lawsuits), and the relevant regulatory area (climate change). While some details are general (e.g., “courts”), the inclusion of the specific lawsuits and the parties involved elevates the specificity beyond a basic disclosure. The text also clearly links the legal proceedings to climate change.

FINAL: text 2
text 2

Comparing sentence 2 with sentence 10
The text references "climate change" and "environmental violations" within a broader discussion of pending lawsuits and claims. However, there are no specific legal actions, parties involved, or quantifiable damages related to climate litigation. The references are general and lack the precision required for a more detailed disclosure.

FINAL: text 2
text 2

Comparing sentence 2 with sentence 11
Text 2 is a more specific disclosure of climate litigation details. While Text 1 mentions the *potential* for climate litigation, Text 2 directly identifies ongoing lawsuits, specific regulations (Fit for 55, etc.), and the parties involved (states, municipalities, oil/gas companies). The breakdown of the JSON also reflects this increased specificity.

FINAL: text 2
text 2

Comparing sentence 2 with sentence 12
Rationale: The breakdown provides specific details regarding regulatory actions (Clean Air Act, EPA rules, IRA), dates, and monetary amounts (methane fees). It clearly links these elements to climate change through the discussion of greenhouse gas emissions and the stated goals of the Inflation Reduction Act. The inclusion of specific regulatory changes and their timelines demonstrates a high level of detail relevant to potential climate litigation.

FINAL: text 2
Okay, I understand. Please provide the text.

Comparing sentence 2 with sentence 13
The provided text clearly outlines potential legal risks related to climate change lawsuits and the company’s existing debt obligations. It specifically identifies “climate change lawsuits” as a significant concern and provides details about the monetary amounts associated with the company’s debt. The text also references the potential for future litigation and the associated costs. This level of specificity, including the mention of specific debt instruments and the potential for litigation, surpasses a basic disclosure.

FINAL: text 2
text 2

Comparing sentence 2 with sentence 14
The breakdown provides a detailed overview of the regulatory landscape impacting the oil and gas industry due to climate change concerns, including proposed EPA rules, state initiatives like RGGI, and growing pressure for corporate transparency. While it discusses legal challenges and potential liabilities, it doesn't present a specific legal action or claim directly related to climate litigation as defined by the provided criteria. The focus is on the *potential* for litigation and the broader regulatory context.


In [246]:
pairwise_results_dfs

{'meta-llama/llama-3.2-1b-instruct':      idx_1  idx_2                                          reasoning    result
 0        0      1  The provided text primarily discusses potentia...  text 1\n
 1        0      2  The breakdown JSON provides a detailed level o...  text 2\n
 2        0      3  The breakdown provides a relatively detailed l...  text 2\n
 3        0      4  The text explicitly details lawsuits filed by ...  text 2\n
 4        0      5  The text primarily focuses on potential risks ...  text 2\n
 ..     ...    ...                                                ...       ...
 100     11     13  The provided text explicitly details ongoing c...  text 1\n
 101     11     14  The text primarily discusses regulatory change...  text 2\n
 102     12     13  detailed disclosure\n\nThe breakdown includes ...  text 2\n
 103     12     14  The text discusses regulatory actions related ...  text 2\n
 104     13     14  The breakdown identifies the core issue as the...  text 2\n

 [105 rows x 4 columns],
 'liquid/lfm-7b':      idx_1  idx_2                                          reasoning    result
 0        0      1  The text outlines specific regulatory requirem...  text 2\n
 1        0      2  The breakdown includes specific regulatory ref...  text 2\n
 2        0      3  The text identifies a loss contingency related...  text 1\n
 3        0      4  The breakdown includes specific details regard...  text 2\n
 4        0      5  The text primarily focuses on regulatory and r...  text 2\n
 ..     ...    ...                                                ...       ...
 100     11     13  The text provides specific details regarding t...  text 2\n
 101     11     14  The breakdown includes precise information abo...  text 2\n
 102     12     13  The text provides specific details about the n...  text 2\n
 103     12     14  The breakdown meticulously identifies the key ...  text 2\n
 104     13     14  The breakdown includes precise information abo...  text 2\n

 [105 rows x 4 columns],
 'meta-llama/llama-3.2-3b-instruct':      idx_1  idx_2                                          reasoning    result
 0        0      1  The breakdown JSON provides a good level of de...  text 1\n
 1        0      2  The text explicitly mentions the *potential* f...  text 2\n
 2        0      3  The breakdown JSON provides a reasonably detai...  text 2\n
 3        0      4  The breakdown JSON provides a detailed level o...  text 2\n
 4        0      5  The breakdown JSON provides a reasonable level...  text 2\n
 ..     ...    ...                                                ...       ...
 100     11     13  The text primarily discusses the potential fin...  text 2\n
 101     11     14  The detailed breakdown captures the key elemen...  text 2\n
 102     12     13  The text primarily discusses potential legal r...  text 2\n
 103     12     14  The detailed breakdown includes specific parti...  text 2\n
 104     13     14  The breakdown captures several key elements of...  text 2\n

 [105 rows x 4 columns],
 'mistralai/mistral-nemo':      idx_1  idx_2                                          reasoning  \
 0        0      1  The text primarily discusses compliance risks ...
 1        0      2  The breakdown identifies a potential for clima...
 2        0      3  Rationale: The text primarily focuses on finan...
 3        0      4  The text primarily discusses the broader legal...
 4        0      5  The text primarily discusses risks related to ...
 ..     ...    ...                                                ...
 100     11     13  The text primarily focuses on CNX’s financial ...
 101     11     14  The text outlines ongoing lawsuits related to ...
 102     12     13  The text primarily discusses legal risks assoc...
 103     12     14  The text outlines ongoing lawsuits related to ...
 104     13     14  The disclosure includes information about clim...

                                                 result
 0                                             text 2\n
 1                                             text 2\n
 2    Okay, please provide the text. I’m ready to an...
 3                                             text 2\n
 4                                             text 2\n
 ..                                                 ...
 100                                           text 2\n
 101                                           text 2\n
 102                                           text 2\n
 103                                           text 2\n
 104                                           text 2\n

 [105 rows x 4 columns],
 'liquid/lfm-3b':      idx_1  idx_2                                          reasoning  \
 0        0      1  Rationale: The text identifies potential risks...
 1        0      2  Text 2 is more specific than Text 1 in assessi...
 2        0      3  Rationale: The provided text primarily details...
 3        0      4  Text 2 is more specific than Text 1. Text 2 di...
 4        0      5  The text primarily discusses potential risks r...
 ..     ...    ...                                                ...
 100     11     13  Rationale: The text provides a basic level of ...
 101     11     14  The breakdown provides detailed information re...
 102     12     13  Rationale: The breakdown provides a reasonable...
 103     12     14  Rationale: The breakdown provides detailed inf...
 104     13     14  Rationale: The breakdown provides a detailed a...

                                              result
 0    Okay, I understand. Please provide the text.\n
 1                                          text 2\n
 2    Okay, I understand. Please provide the text.\n
 3                                          text 2\n
 4                                          text 2\n
 ..                                              ...
 100  Okay, I understand. Please provide the text.\n
 101                                        text 2\n
 102                                        text 2\n
 103                                        text 2\n
 104  Okay, I understand. Please provide the text.\n

 [105 rows x 4 columns],
 'meta-llama/llama-3.1-8b-instruct':      idx_1  idx_2                                          reasoning  \
 0        0      1  The breakdown identifies some climate-related ...
 1        0      2  The breakdown provides a list of potential cli...
 2        0      3  Rationale: The text primarily details accounti...
 3        0      4  The text primarily discusses general environme...
 4        0      5  The text primarily discusses business risks – ...
 ..     ...    ...                                                ...
 100     11     13  The disclosure identifies CNX as a party to cl...
 101     11     14  The text primarily discusses regulatory develo...
 102     12     13  The text primarily focuses on the company's ex...
 103     12     14  Rationale: The text primarily describes regula...
 104     13     14                                      FINAL: text 2

                                                 result
 0                                             text 2\n
 1                                             text 2\n
 2       Okay, I understand. Please provide the text.\n
 3                                             text 2\n
 4                                             text 2\n
 ..                                                 ...
 100                                           text 2\n
 101                                           text 2\n
 102                                           text 2\n
 103     Okay, I understand. Please provide the text.\n
 104  Okay, I understand. Please provide the text. I...

 [105 rows x 4 columns],
 'google/gemma-3-4b-it':      idx_1  idx_2                                          reasoning    result
 0        0      1  Text 2 is more specific due to the inclusion o...  text 2\n
 1        0      2  Text 2 is more specific due to the inclusion o...  text 2\n
 2        0      3  The text primarily details accounting adjustme...  text 2\n
 3        0      4  Text 2 represents a more specific and actionab...  text 2\n
 4        0      5  The text demonstrates a significant risk of cl...  text 2\n
 ..     ...    ...                                                ...       ...
 100     11     13  The text explicitly details ongoing climate li...  text 1\n
 101     11     14  Text 2 is significantly more specific than Tex...  text 2\n
 102     12     13                            Text 2\n\nFINAL: Text 2  text 2\n
 103     12     14  Text 2 demonstrates a higher degree of specifi...  text 2\n
 104     13     14  Text 2 exhibits a significantly higher degree ...  text 2\n

 [105 rows x 4 columns],
 'sao10k/l3-lunaris-8b':      idx_1  idx_2                                          reasoning    result
 0        0      1  The text contains specific references to clima...  text 1\n
 1        0      2  The text provides a detailed discussion of pot...  text 1\n
 2        0      3  The provided text details financial adjustment...  text 2\n
 3        0      4  The breakdown JSON provides a detailed level o...  text 2\n
 4        0      5  The text primarily outlines risks related to r...  text 2\n
 ..     ...    ...                                                ...       ...
 100     11     13  The text provides a detailed breakdown of spec...  text 1\n
 101     11     14  The text contains specific details regarding l...  text 1\n
 102     12     13  The text provides a detailed disclosure of spe...  text 2\n
 103     12     14  Text 2\n\nFINAL: text 2\n\nRationale: Text 2 p...  text 2\n
 104     13     14  The text contains specific details related to ...  text 2\n

 [105 rows x 4 columns],
 'nousresearch/hermes-2-pro-llama-3-8b':      idx_1  idx_2                                          reasoning    result
 0        0      1  The breakdown for Text 2 is more specific beca...  text 2\n
 1        0      2  The breakdown JSON provides a reasonably detai...  text 2\n
 2        0      3  The breakdown provides specific details regard...  text 2\n
 3        0      4  The breakdown for Text 2 is significantly more...  text 2\n
 4        0      5  The text discusses potential risks related to ...  text 2\n
 ..     ...    ...                                                ...       ...
 100     11     13  The breakdown JSON provides a good level of de...  text 2\n
 101     11     14  The text provides a detailed breakdown of lega...  text 2\n
 102     12     13  The breakdown provides specific details regard...  text 2\n
 103     12     14  Text 2\n\nRationale: Text 2 provides a signifi...  text 2\n
 104     13     14  The text provides a detailed breakdown of lega...  text 2\n

 [105 rows x 4 columns],
 'mistralai/mistral-7b-instruct':      idx_1  idx_2                                          reasoning  \
 0        0      1  Rationale: The text discusses potential regula...
 1        0      2  The text discusses potential future climate re...
 2        0      3  Rationale: The text details financial reportin...
 3        0      4  Rationale: The text provides a relatively deta...
 4        0      5  Text 2 is more specific. While Text 1 discusse...
 ..     ...    ...                                                ...
 100     11     13  detailed disclosure\n\nThe breakdown provides ...
 101     11     14  The breakdown provides specific details regard...
 102     12     13  detailed disclosure\n\nThe breakdown provides ...
 103     12     14  detailed disclosure\n\nThe breakdown provides ...
 104     13     14  The JSON breakdown for Text 2 provides a more ...

                                              result
 0    Okay, I understand. Please provide the text.\n
 1                                          text 2\n
 2    Okay, I understand. Please provide the text.\n
 3    Okay, I understand. Please provide the text.\n
 4                                            text 2
 ..                                              ...
 100                                        text 2\n
 101                                        text 2\n
 102                                        text 2\n
 103                                        text 2\n
 104                                        text 2\n

 [105 rows x 4 columns]}

In [267]:
def check_invalid_results(df_list):
    invalid_entries = []
    for model, df in df_list.items():
        for idx, row in df.iterrows():
            result = str(row['result']).strip().lower()
            if result not in ['text 1', 'text 2', 'neither']:
                invalid_entries.append({
                    'model': model,
                    'idx_1': row['idx_1'],
                    'idx_2': row['idx_2'],
                    'result': row['result']
                })
    return invalid_entries

invalid_results = check_invalid_results(pairwise_results_dfs)

In [253]:
from collections import Counter

# Count invalid results per model
invalid_counts = Counter()
for entry in invalid_results:
    model = entry['model']
    invalid_counts[model] += 1

# Print the percentage of invalid results for each model (out of 105)
for model, count in invalid_counts.items():
    percent = (count / 105) * 100
    print(f"Model: {model}, Invalid results: {count} ({percent:.2f}%)")

Model: meta-llama/llama-3.2-1b-instruct, Invalid results: 22 (20.95%)
Model: liquid/lfm-7b, Invalid results: 2 (1.90%)
Model: meta-llama/llama-3.2-3b-instruct, Invalid results: 1 (0.95%)
Model: mistralai/mistral-nemo, Invalid results: 24 (22.86%)
Model: liquid/lfm-3b, Invalid results: 40 (38.10%)
Model: meta-llama/llama-3.1-8b-instruct, Invalid results: 23 (21.90%)
Model: google/gemma-3-4b-it, Invalid results: 8 (7.62%)
Model: sao10k/l3-lunaris-8b, Invalid results: 5 (4.76%)
Model: nousresearch/hermes-2-pro-llama-3-8b, Invalid results: 1 (0.95%)
Model: mistralai/mistral-7b-instruct, Invalid results: 24 (22.86%)

In [ ]:
# Overwrite invalid results in pairwise_results_dfs with rerun slimmer_pairwise results

for entry in invalid_results:
    model = entry['model']
    print(f"Model: {model}")
    idx_1 = entry['idx_1']
    idx_2 = entry['idx_2']
    # Get the model_df used for this model
    model_df = load_full_messages(model)
    # Get the texts for idx_1 and idx_2
    text_1 = model_df.loc[model_df.index == idx_1, 'full_message'].values[0]
    text_2 = model_df.loc[model_df.index == idx_2, 'full_message'].values[0]
    # Run slimmer_pairwise on the two texts
    result, final_result = slimmer_pairwise(text_1, text_2)
    # Overwrite the result in the pairwise_results_dfs
    pairwise_df = pairwise_results_dfs[model]
    mask = (pairwise_df['idx_1'] == idx_1) & (pairwise_df['idx_2'] == idx_2)
    # Use .at to set the value for the single row
    idxs = pairwise_df.index[mask]
    if len(idxs) == 1:
        pairwise_results_dfs[model].at[idxs[0], 'result'] = final_result
        pairwise_results_dfs[model].at[idxs[0], 'reasoning'] = result
    elif len(idxs) == 0:
        print(f"Warning: No matching row found for model={model}, idx_1={idx_1}, idx_2={idx_2}")
    else:
        print(f"Warning: Multiple matching rows found for model={model}, idx_1={idx_1}, idx_2={idx_2}")

Model: meta-llama/llama-3.2-1b-instruct
Text 1 provides more specific details about climate litigation, including the mention of civil litigation and regulatory focus on global climate change, as well as specific regulations such as the Clean Air Act and the Paris Climate Accord. In contrast, Text 2 only mentions the potential for increased exposure to climate change-related litigation, but does not provide specific details about the litigation itself.

FINAL: text 1
In the following content, extract the final decision. Return ONLY 'text 1' or 'text 2' or 'neither' (no other text). If absent, infer from the last explicit choice.

Text 1 provides more specific details about climate litigation, including the mention of civil litigation and regulatory focus on global climate change, as well as specific regulations such as the Clean Air Act and the Paris Climate Accord. In contrast, Text 2 only mentions the potential for increased exposure to climate change-related litigation, but does not provide specific details about the litigation itself.

FINAL: text 1
text 1
Model: meta-llama/llama-3.2-1b-instruct
Text 1 provides more specific details about climate litigation, including the mention of civil litigation and regulatory focus on global climate change, as well as specific dates and regulations related to climate change. In contrast, Text 2 only mentions climate change as one of the various lawsuits and claims that the company is facing, without providing any specific details.

FINAL: text 1
In the following content, extract the final decision. Return ONLY 'text 1' or 'text 2' or 'neither' (no other text). If absent, infer from the last explicit choice.

Text 1 provides more specific details about climate litigation, including the mention of civil litigation and regulatory focus on global climate change, as well as specific dates and regulations related to climate change. In contrast, Text 2 only mentions climate change as one of the various lawsuits and claims that the company is facing, without providing any specific details.

FINAL: text 1
text 1
Model: meta-llama/llama-3.2-1b-instruct
Text 1 is more specific than Text 2 because it provides more details about the regulatory focus on climate change, including the Clean Air Act, the Clean Power Plan, and the Inflation Reduction Act. Text 1 also mentions specific dates and events related to climate change regulation, such as the EPA's regulation of GHGs under the Clean Air Act in 2013 and the Biden administration's re-entry into the Paris Climate Accord. In contrast, Text 2 only mentions climate change-related litigation in a general sense and does not provide specific details about the litigation or the regulatory framework.

FINAL: text 1
In the following content, extract the final decision. Return ONLY 'text 1' or 'text 2' or 'neither' (no other text). If absent, infer from the last explicit choice.

Text 1 is more specific than Text 2 because it provides more details about the regulatory focus on climate change, including the Clean Air Act, the Clean Power Plan, and the Inflation Reduction Act. Text 1 also mentions specific dates and events related to climate change regulation, such as the EPA's regulation of GHGs under the Clean Air Act in 2013 and the Biden administration's re-entry into the Paris Climate Accord. In contrast, Text 2 only mentions climate change-related litigation in a general sense and does not provide specific details about the litigation or the regulatory framework.

FINAL: text 1
text 1
Model: meta-llama/llama-3.2-1b-instruct
Text 1 provides more specific details about climate litigation, including the number of lawsuits, the parties involved, and the forum/jurisdiction. In contrast, Text 2 does not provide any specific details about climate litigation, only mentioning the potential for increased exposure to climate change-related litigation.

FINAL: text 1
In the following content, extract the final decision. Return ONLY 'text 1' or 'text 2' or 'neither' (no other text). If absent, infer from the last explicit choice.

Text 1 provides more specific details about climate litigation, including the number of lawsuits, the parties involved, and the forum/jurisdiction. In contrast, Text 2 does not provide any specific details about climate litigation, only mentioning the potential for increased exposure to climate change-related litigation.

FINAL: text 1
text 1
Model: meta-llama/llama-3.2-1b-instruct
Text 1 is more specific because it mentions specific climate change lawsuits being pursued by communities against fossil fuel producers, whereas Text 2 only mentions the possibility of climate change-related litigation without providing specific details.

FINAL: text 1
In the following content, extract the final decision. Return ONLY 'text 1' or 'text 2' or 'neither' (no other text). If absent, infer from the last explicit choice.

Text 1 is more specific because it mentions specific climate change lawsuits being pursued by communities against fossil fuel producers, whereas Text 2 only mentions the possibility of climate change-related litigation without providing specific details.

FINAL: text 1
text 1
Model: meta-llama/llama-3.2-1b-instruct
Text 1 is more specific than Text 2 because it provides more detailed information about the climate litigation, including the number of lawsuits, the parties involved, and the potential impact on the company's financial position. In contrast, Text 2 only mentions the potential for increased exposure to climate change-related litigation without providing specific details.

FINAL: text 1
In the following content, extract the final decision. Return ONLY 'text 1' or 'text 2' or 'neither' (no other text). If absent, infer from the last explicit choice.

Text 1 is more specific than Text 2 because it provides more detailed information about the climate litigation, including the number of lawsuits, the parties involved, and the potential impact on the company's financial position. In contrast, Text 2 only mentions the potential for increased exposure to climate change-related litigation without providing specific details.

FINAL: text 1
text 1
Model: meta-llama/llama-3.2-1b-instruct
Text 2 does not meet the criteria for climate litigation as it does not mention any specific lawsuits or legal actions related to climate change. The text only discusses potential risks and challenges related to climate change and regulatory compliance.

FINAL: text 1
In the following content, extract the final decision. Return ONLY 'text 1' or 'text 2' or 'neither' (no other text). If absent, infer from the last explicit choice.

Text 2 does not meet the criteria for climate litigation as it does not mention any specific lawsuits or legal actions related to climate change. The text only discusses potential risks and challenges related to climate change and regulatory compliance.

FINAL: text 1
text 1
Model: meta-llama/llama-3.2-1b-instruct
Based on the provided breakdowns, I would rate Text 1 as "detailed disclosure" and Text 2 as "mention only". Text 1 provides more specific details about the climate litigation, including the parties involved, the procedural posture, and the climate linkage quotes. Text 2, on the other hand, only mentions the potential for climate change-related litigation without providing any specific details.

FINAL: text 1
In the following content, extract the final decision. Return ONLY 'text 1' or 'text 2' or 'neither' (no other text). If absent, infer from the last explicit choice.

Based on the provided breakdowns, I would rate Text 1 as "detailed disclosure" and Text 2 as "mention only". Text 1 provides more specific details about the climate litigation, including the parties involved, the procedural posture, and the climate linkage quotes. Text 2, on the other hand, only mentions the potential for climate change-related litigation without providing any specific details.

FINAL: text 1
text 1
Model: meta-llama/llama-3.2-1b-instruct
Text 1 provides more specific details about climate litigation, including the number of lawsuits filed, the parties involved, and the specific weather-related events being targeted. In contrast, Text 2 only mentions climate change as one of the many potential liabilities facing the company, without providing any specific details.

FINAL: text 1
In the following content, extract the final decision. Return ONLY 'text 1' or 'text 2' or 'neither' (no other text). If absent, infer from the last explicit choice.

Text 1 provides more specific details about climate litigation, including the number of lawsuits filed, the parties involved, and the specific weather-related events being targeted. In contrast, Text 2 only mentions climate change as one of the many potential liabilities facing the company, without providing any specific details.

FINAL: text 1
text 1
Model: meta-llama/llama-3.2-1b-instruct
The rationale for choosing "not climate litigation" is that the text does not mention any specific lawsuits or legal actions related to climate change, but rather discusses potential risks and challenges that the company may face in the future due to climate change-related regulatory activity.

FINAL: text 1
In the following content, extract the final decision. Return ONLY 'text 1' or 'text 2' or 'neither' (no other text). If absent, infer from the last explicit choice.

The rationale for choosing "not climate litigation" is that the text does not mention any specific lawsuits or legal actions related to climate change, but rather discusses potential risks and challenges that the company may face in the future due to climate change-related regulatory activity.

FINAL: text 1
text 1
Model: meta-llama/llama-3.2-1b-instruct
Text 1 is more specific than Text 2 because it provides more detailed information about the climate litigation, including the parties involved, the forum, and the procedural posture. Text 1 also provides more specific dates and monetary amounts related to the climate litigation. In contrast, Text 2 only mentions the potential for climate change-related litigation and provides some general information about the regulatory environment, but does not provide specific details about the litigation itself.

FINAL: text 1
In the following content, extract the final decision. Return ONLY 'text 1' or 'text 2' or 'neither' (no other text). If absent, infer from the last explicit choice.

Text 1 is more specific than Text 2 because it provides more detailed information about the climate litigation, including the parties involved, the forum, and the procedural posture. Text 1 also provides more specific dates and monetary amounts related to the climate litigation. In contrast, Text 2 only mentions the potential for climate change-related litigation and provides some general information about the regulatory environment, but does not provide specific details about the litigation itself.

FINAL: text 1
text 1
Model: meta-llama/llama-3.2-1b-instruct
The text does not provide specific details about climate litigation, such as parties, case title, forum, or procedural posture. The text only mentions the possibility of climate change-related litigation, but does not provide any concrete information about it.

FINAL: text 1
In the following content, extract the final decision. Return ONLY 'text 1' or 'text 2' or 'neither' (no other text). If absent, infer from the last explicit choice.

The text does not provide specific details about climate litigation, such as parties, case title, forum, or procedural posture. The text only mentions the possibility of climate change-related litigation, but does not provide any concrete information about it.

FINAL: text 1
text 1
Model: meta-llama/llama-3.2-1b-instruct
Text 1 is more specific than Text 2 because it provides more details about the litigation, such as the name of the litigation ("Havana Docks litigation") and the fact that it is an ongoing litigation. In contrast, Text 2 only mentions that the company is subject to various lawsuits and claims related to climate change, but does not provide any specific details about the litigation.

FINAL: text 1
In the following content, extract the final decision. Return ONLY 'text 1' or 'text 2' or 'neither' (no other text). If absent, infer from the last explicit choice.

Text 1 is more specific than Text 2 because it provides more details about the litigation, such as the name of the litigation ("Havana Docks litigation") and the fact that it is an ongoing litigation. In contrast, Text 2 only mentions that the company is subject to various lawsuits and claims related to climate change, but does not provide any specific details about the litigation.

FINAL: text 1
text 1
Model: meta-llama/llama-3.2-1b-instruct
The rationale for choosing "not climate litigation" is that the text does not mention any specific lawsuit or litigation related to climate change. While it mentions climate change-related risks and regulatory activity, it does not provide any details about a specific lawsuit or litigation.

FINAL: neither
In the following content, extract the final decision. Return ONLY 'text 1' or 'text 2' or 'neither' (no other text). If absent, infer from the last explicit choice.

The rationale for choosing "not climate litigation" is that the text does not mention any specific lawsuit or litigation related to climate change. While it mentions climate change-related risks and regulatory activity, it does not provide any details about a specific lawsuit or litigation.

FINAL: neither
neither
Model: meta-llama/llama-3.2-1b-instruct
Text 1 is more specific about climate litigation, as it provides more details about the regulatory actions, including the Clean Air Act, the Paris Climate Accord, and the Inflation Reduction Act, and their potential impact on the company's business. Text 2, on the other hand, is more focused on the company's potential risks and challenges related to climate change, but does not provide specific details about climate litigation.

FINAL: text 1
In the following content, extract the final decision. Return ONLY 'text 1' or 'text 2' or 'neither' (no other text). If absent, infer from the last explicit choice.

Text 1 is more specific about climate litigation, as it provides more details about the regulatory actions, including the Clean Air Act, the Paris Climate Accord, and the Inflation Reduction Act, and their potential impact on the company's business. Text 2, on the other hand, is more focused on the company's potential risks and challenges related to climate change, but does not provide specific details about climate litigation.

FINAL: text 1
text 1
Model: meta-llama/llama-3.2-1b-instruct
Text 1 has a specificity label of "detailed disclosure" due to its mention of specific regulatory actions, such as increased regulatory scrutiny and potential litigation related to environmental, health, and community impacts. However, Text 2 also has a specificity label of "detailed disclosure" due to its mention of specific regulations, such as the European Union's Fit for 55 package and the IMO Sulfur Limit, and its discussion of climate change-related litigation.

FINAL: neither
In the following content, extract the final decision. Return ONLY 'text 1' or 'text 2' or 'neither' (no other text). If absent, infer from the last explicit choice.

Text 1 has a specificity label of "detailed disclosure" due to its mention of specific regulatory actions, such as increased regulatory scrutiny and potential litigation related to environmental, health, and community impacts. However, Text 2 also has a specificity label of "detailed disclosure" due to its mention of specific regulations, such as the European Union's Fit for 55 package and the IMO Sulfur Limit, and its discussion of climate change-related litigation.

FINAL: neither
neither
Model: meta-llama/llama-3.2-1b-instruct
Text 1 is more specific than Text 2 because it provides more detailed information about the potential risks and challenges facing the company, including the specific risks related to climate change and energy transition. Text 1 also provides more context about the company's operations and the potential impact of climate-related risks on its financial performance.

FINAL: text 1
In the following content, extract the final decision. Return ONLY 'text 1' or 'text 2' or 'neither' (no other text). If absent, infer from the last explicit choice.

Text 1 is more specific than Text 2 because it provides more detailed information about the potential risks and challenges facing the company, including the specific risks related to climate change and energy transition. Text 1 also provides more context about the company's operations and the potential impact of climate-related risks on its financial performance.

FINAL: text 1
text 1
Model: meta-llama/llama-3.2-1b-instruct
Text 1 is more specific than Text 2 because it provides more detailed information about the potential risks and challenges facing the company, including specific examples of how climate change-related regulatory activity may impact the company's business and financial results. In contrast, Text 2 is more general and does not provide specific details about climate litigation.

FINAL: text 1
In the following content, extract the final decision. Return ONLY 'text 1' or 'text 2' or 'neither' (no other text). If absent, infer from the last explicit choice.

Text 1 is more specific than Text 2 because it provides more detailed information about the potential risks and challenges facing the company, including specific examples of how climate change-related regulatory activity may impact the company's business and financial results. In contrast, Text 2 is more general and does not provide specific details about climate litigation.

FINAL: text 1
text 1
Model: meta-llama/llama-3.2-1b-instruct
Text 1 is more specific than Text 2 because it provides more detailed information about the potential risks and challenges related to climate change, including the specific regulations and policies that may impact the company's business and financial results. Text 1 also mentions the potential for climate change-related litigation, which is a key aspect of climate litigation.

FINAL: text 1
In the following content, extract the final decision. Return ONLY 'text 1' or 'text 2' or 'neither' (no other text). If absent, infer from the last explicit choice.

Text 1 is more specific than Text 2 because it provides more detailed information about the potential risks and challenges related to climate change, including the specific regulations and policies that may impact the company's business and financial results. Text 1 also mentions the potential for climate change-related litigation, which is a key aspect of climate litigation.

FINAL: text 1
text 1
Model: meta-llama/llama-3.2-1b-instruct
Text 2 does not provide sufficient specificity about climate litigation, and the breakdown JSON does not contain enough information to support a classification as climate litigation. The text primarily discusses regulatory risks and compliance, rather than a specific lawsuit or legal action related to climate change.

FINAL: text 1
In the following content, extract the final decision. Return ONLY 'text 1' or 'text 2' or 'neither' (no other text). If absent, infer from the last explicit choice.

Text 2 does not provide sufficient specificity about climate litigation, and the breakdown JSON does not contain enough information to support a classification as climate litigation. The text primarily discusses regulatory risks and compliance, rather than a specific lawsuit or legal action related to climate change.

FINAL: text 1
text 1
Model: meta-llama/llama-3.2-1b-instruct
The text does not provide sufficient information to be classified as climate litigation. It discusses potential risks and challenges related to climate change, but does not mention any specific lawsuits or legal actions.

FINAL: neither

In [260]:
from collections import Counter

# Count invalid results per model
invalid_counts = Counter()
for entry in invalid_results:
    model = entry['model']
    invalid_counts[model] += 1

# Print the percentage of invalid results for each model (out of 105)
for model, count in invalid_counts.items():
    percent = (count / 105) * 100
    print(f"Model: {model}, Invalid results: {count} ({percent:.2f}%)")

Model: meta-llama/llama-3.2-1b-instruct, Invalid results: 22 (20.95%)
Model: liquid/lfm-7b, Invalid results: 2 (1.90%)
Model: meta-llama/llama-3.2-3b-instruct, Invalid results: 1 (0.95%)
Model: mistralai/mistral-nemo, Invalid results: 24 (22.86%)
Model: liquid/lfm-3b, Invalid results: 40 (38.10%)
Model: meta-llama/llama-3.1-8b-instruct, Invalid results: 23 (21.90%)
Model: google/gemma-3-4b-it, Invalid results: 8 (7.62%)
Model: sao10k/l3-lunaris-8b, Invalid results: 5 (4.76%)
Model: nousresearch/hermes-2-pro-llama-3-8b, Invalid results: 1 (0.95%)
Model: mistralai/mistral-7b-instruct, Invalid results: 24 (22.86%)

In [263]:
# Retroactively fix any tuples that were stored in the 'result' column
fixed_count = 0
for model, df in pairwise_results_dfs.items():
    for idx, row in df.iterrows():
        result_val = row['result']
        # Check if it's a tuple
        if isinstance(result_val, tuple):
            fixed_count += 1
            # Extract the second element (final_result) for 'result' column
            # Extract the first element (pairwise_result) for 'reasoning' column
            pairwise_result, final_result = result_val
            pairwise_results_dfs[model].at[idx, 'result'] = final_result
            pairwise_results_dfs[model].at[idx, 'reasoning'] = pairwise_result
            print(f"Fixed tuple in model {model}, row {idx}: {final_result}")

print(f"\nTotal tuples fixed: {fixed_count}")

Fixed tuple in model meta-llama/llama-3.2-1b-instruct, row 7: text 1
Fixed tuple in model meta-llama/llama-3.2-1b-instruct, row 9: text 1
Fixed tuple in model meta-llama/llama-3.2-1b-instruct, row 11: text 1
Fixed tuple in model meta-llama/llama-3.2-1b-instruct, row 20: text 1
Fixed tuple in model meta-llama/llama-3.2-1b-instruct, row 24: text 1
Fixed tuple in model meta-llama/llama-3.2-1b-instruct, row 32: text 1
Fixed tuple in model meta-llama/llama-3.2-1b-instruct, row 36: text 1
Fixed tuple in model meta-llama/llama-3.2-1b-instruct, row 43: text 1
Fixed tuple in model meta-llama/llama-3.2-1b-instruct, row 45: text 1
Fixed tuple in model meta-llama/llama-3.2-1b-instruct, row 47: text 1
Fixed tuple in model meta-llama/llama-3.2-1b-instruct, row 53: text 1
Fixed tuple in model meta-llama/llama-3.2-1b-instruct, row 57: text 1
Fixed tuple in model meta-llama/llama-3.2-1b-instruct, row 64: text 1
Fixed tuple in model meta-llama/llama-3.2-1b-instruct, row 66: neither
Fixed tuple in model meta-llama/llama-3.2-1b-instruct, row 74: text 1
Fixed tuple in model meta-llama/llama-3.2-1b-instruct, row 77: neither
Fixed tuple in model meta-llama/llama-3.2-1b-instruct, row 79: text 1
Fixed tuple in model meta-llama/llama-3.2-1b-instruct, row 81: text 1
Fixed tuple in model meta-llama/llama-3.2-1b-instruct, row 87: text 1
Fixed tuple in model meta-llama/llama-3.2-1b-instruct, row 92: text 1
Fixed tuple in model meta-llama/llama-3.2-1b-instruct, row 96: neither
Fixed tuple in model meta-llama/llama-3.2-1b-instruct, row 99: text 1
Fixed tuple in model liquid/lfm-7b, row 27: text 1
Fixed tuple in model liquid/lfm-7b, row 33: text 2
Fixed tuple in model meta-llama/llama-3.2-3b-instruct, row 49: text 1
Fixed tuple in model mistralai/mistral-nemo, row 2: neither
Fixed tuple in model mistralai/mistral-nemo, row 8: neither
Fixed tuple in model mistralai/mistral-nemo, row 9: text 1
Fixed tuple in model mistralai/mistral-nemo, row 27: neither
Fixed tuple in model mistralai/mistral-nemo, row 33: neither
Fixed tuple in model mistralai/mistral-nemo, row 34: text 2
Fixed tuple in model mistralai/mistral-nemo, row 37: text 1
Fixed tuple in model mistralai/mistral-nemo, row 38: text 1
Fixed tuple in model mistralai/mistral-nemo, row 39: text 2
Fixed tuple in model mistralai/mistral-nemo, row 42: text 1
Fixed tuple in model mistralai/mistral-nemo, row 45: text 2
Fixed tuple in model mistralai/mistral-nemo, row 49: text 1
Fixed tuple in model mistralai/mistral-nemo, row 63: text 1
Fixed tuple in model mistralai/mistral-nemo, row 69: text 1
Fixed tuple in model mistralai/mistral-nemo, row 72: text 1
Fixed tuple in model mistralai/mistral-nemo, row 73: text 1
Fixed tuple in model mistralai/mistral-nemo, row 74: text 1
Fixed tuple in model mistralai/mistral-nemo, row 76: text 1
Fixed tuple in model mistralai/mistral-nemo, row 85: text 1
Fixed tuple in model mistralai/mistral-nemo, row 90: text 2
Fixed tuple in model mistralai/mistral-nemo, row 91: text 2
Fixed tuple in model mistralai/mistral-nemo, row 92: text 2
Fixed tuple in model mistralai/mistral-nemo, row 93: text 1
Fixed tuple in model mistralai/mistral-nemo, row 98: text 1
Fixed tuple in model liquid/lfm-3b, row 0: text 1
Fixed tuple in model liquid/lfm-3b, row 2: text 2
Fixed tuple in model liquid/lfm-3b, row 8: text 2
Fixed tuple in model liquid/lfm-3b, row 12: text 1
Fixed tuple in model liquid/lfm-3b, row 14: text 2
Fixed tuple in model liquid/lfm-3b, row 17: text 2
Fixed tuple in model liquid/lfm-3b, row 22: text 2
Fixed tuple in model liquid/lfm-3b, row 23: text 2
Fixed tuple in model liquid/lfm-3b, row 26: text 2
Fixed tuple in model liquid/lfm-3b, row 27: text 1
Fixed tuple in model liquid/lfm-3b, row 30: text 2
Fixed tuple in model liquid/lfm-3b, row 33: text 1
Fixed tuple in model liquid/lfm-3b, row 37: text 1
Fixed tuple in model liquid/lfm-3b, row 40: text 1
Fixed tuple in model liquid/lfm-3b, row 41: Text 1
Fixed tuple in model liquid/lfm-3b, row 42: text 1
Fixed tuple in model liquid/lfm-3b, row 45: text 1
Fixed tuple in model liquid/lfm-3b, row 46: text 1
Fixed tuple in model liquid/lfm-3b, row 48: text 1
Fixed tuple in model liquid/lfm-3b, row 49: text 2
Fixed tuple in model liquid/lfm-3b, row 58: text 1
Fixed tuple in model liquid/lfm-3b, row 61: text 2
Fixed tuple in model liquid/lfm-3b, row 65: text 2
Fixed tuple in model liquid/lfm-3b, row 67: text 2
Fixed tuple in model liquid/lfm-3b, row 71: text 1
Fixed tuple in model liquid/lfm-3b, row 73: text 1
Fixed tuple in model liquid/lfm-3b, row 76: text 1
Fixed tuple in model liquid/lfm-3b, row 82: text 1
Fixed tuple in model liquid/lfm-3b, row 83: text 1
Fixed tuple in model liquid/lfm-3b, row 84: text 1
Fixed tuple in model liquid/lfm-3b, row 86: text 1
Fixed tuple in model liquid/lfm-3b, row 88: text 1
Fixed tuple in model liquid/lfm-3b, row 91: text 1
Fixed tuple in model liquid/lfm-3b, row 93: text 1
Fixed tuple in model liquid/lfm-3b, row 94: text 2
Fixed tuple in model liquid/lfm-3b, row 95: text 1
Fixed tuple in model liquid/lfm-3b, row 97: text 1
Fixed tuple in model liquid/lfm-3b, row 98: text 1
Fixed tuple in model liquid/lfm-3b, row 100: text 1
Fixed tuple in model liquid/lfm-3b, row 104: text 2
Fixed tuple in model meta-llama/llama-3.1-8b-instruct, row 2: text 1
Fixed tuple in model meta-llama/llama-3.1-8b-instruct, row 10: text 2
Fixed tuple in model meta-llama/llama-3.1-8b-instruct, row 13: neither
Fixed tuple in model meta-llama/llama-3.1-8b-instruct, row 23: text 1
Fixed tuple in model meta-llama/llama-3.1-8b-instruct, row 26: neither
Fixed tuple in model meta-llama/llama-3.1-8b-instruct, row 38: neither
Fixed tuple in model meta-llama/llama-3.1-8b-instruct, row 42: text 1
Fixed tuple in model meta-llama/llama-3.1-8b-instruct, row 46: text 2
Fixed tuple in model meta-llama/llama-3.1-8b-instruct, row 48: text 2
Fixed tuple in model meta-llama/llama-3.1-8b-instruct, row 49: text 1
Fixed tuple in model meta-llama/llama-3.1-8b-instruct, row 59: neither
Fixed tuple in model meta-llama/llama-3.1-8b-instruct, row 65: text 2
Fixed tuple in model meta-llama/llama-3.1-8b-instruct, row 68: neither
Fixed tuple in model meta-llama/llama-3.1-8b-instruct, row 73: text 2
Fixed tuple in model meta-llama/llama-3.1-8b-instruct, row 76: neither
Fixed tuple in model meta-llama/llama-3.1-8b-instruct, row 86: text 2
Fixed tuple in model meta-llama/llama-3.1-8b-instruct, row 89: neither
Fixed tuple in model meta-llama/llama-3.1-8b-instruct, row 91: text 1
Fixed tuple in model meta-llama/llama-3.1-8b-instruct, row 94: text 1
Fixed tuple in model meta-llama/llama-3.1-8b-instruct, row 95: text 2
Fixed tuple in model meta-llama/llama-3.1-8b-instruct, row 98: neither
Fixed tuple in model meta-llama/llama-3.1-8b-instruct, row 103: neither
Fixed tuple in model meta-llama/llama-3.1-8b-instruct, row 104: neither
Fixed tuple in model google/gemma-3-4b-it, row 8: text 2
Fixed tuple in model google/gemma-3-4b-it, row 21: text 2
Fixed tuple in model google/gemma-3-4b-it, row 33: text 2
Fixed tuple in model google/gemma-3-4b-it, row 54: text 2
Fixed tuple in model google/gemma-3-4b-it, row 63: text 2
Fixed tuple in model google/gemma-3-4b-it, row 67: text 2
Fixed tuple in model google/gemma-3-4b-it, row 78: text 2
Fixed tuple in model google/gemma-3-4b-it, row 84: text 2
Fixed tuple in model sao10k/l3-lunaris-8b, row 29: text 1
Fixed tuple in model sao10k/l3-lunaris-8b, row 58: text 1
Fixed tuple in model sao10k/l3-lunaris-8b, row 61: text 2
Fixed tuple in model sao10k/l3-lunaris-8b, row 65: neither
Fixed tuple in model sao10k/l3-lunaris-8b, row 98: text 1
Fixed tuple in model nousresearch/hermes-2-pro-llama-3-8b, row 61: text 2
Fixed tuple in model mistralai/mistral-7b-instruct, row 0: text 1
Fixed tuple in model mistralai/mistral-7b-instruct, row 2: text 1
Fixed tuple in model mistralai/mistral-7b-instruct, row 3: text 1
Fixed tuple in model mistralai/mistral-7b-instruct, row 9: text 1
Fixed tuple in model mistralai/mistral-7b-instruct, row 15: text 1
Fixed tuple in model mistralai/mistral-7b-instruct, row 16: text 1
Fixed tuple in model mistralai/mistral-7b-instruct, row 18: text 1
Fixed tuple in model mistralai/mistral-7b-instruct, row 22: text 1
Fixed tuple in model mistralai/mistral-7b-instruct, row 24: text 1
Fixed tuple in model mistralai/mistral-7b-instruct, row 27: text 1
Fixed tuple in model mistralai/mistral-7b-instruct, row 28: Text 1
Fixed tuple in model mistralai/mistral-7b-instruct, row 30: text 1
Fixed tuple in model mistralai/mistral-7b-instruct, row 34: text 1
Fixed tuple in model mistralai/mistral-7b-instruct, row 39: text 1
Fixed tuple in model mistralai/mistral-7b-instruct, row 40: text 1
Fixed tuple in model mistralai/mistral-7b-instruct, row 41: text 1
Fixed tuple in model mistralai/mistral-7b-instruct, row 51: text 1
Fixed tuple in model mistralai/mistral-7b-instruct, row 57: text 1
Fixed tuple in model mistralai/mistral-7b-instruct, row 60: text 2
Fixed tuple in model mistralai/mistral-7b-instruct, row 63: text 2
Fixed tuple in model mistralai/mistral-7b-instruct, row 64: neither
Fixed tuple in model mistralai/mistral-7b-instruct, row 85: text 1
Fixed tuple in model mistralai/mistral-7b-instruct, row 87: text 1
Fixed tuple in model mistralai/mistral-7b-instruct, row 99: text 2

Total tuples fixed: 150

In [268]:
# Recompute invalid results after the fix
invalid_results_after_fix = check_invalid_results(pairwise_results_dfs)

# Count invalid results per model
invalid_counts_after_fix = Counter()
for entry in invalid_results_after_fix:
    model = entry['model']
    invalid_counts_after_fix[model] += 1

# Print the percentage of invalid results for each model (out of 105)
print("AFTER RETROACTIVE FIX:")
print("="*60)
for model in model_list:
    count = invalid_counts_after_fix.get(model, 0)
    percent = (count / 105) * 100
    print(f"Model: {model}")
    print(f"  Invalid results: {count} ({percent:.2f}%)")
    print()

print(f"Total invalid results across all models: {len(invalid_results_after_fix)}")

AFTER RETROACTIVE FIX:
============================================================
Model: meta-llama/llama-3.2-1b-instruct
  Invalid results: 0 (0.00%)

Model: liquid/lfm-7b
  Invalid results: 0 (0.00%)

Model: meta-llama/llama-3.2-3b-instruct
  Invalid results: 0 (0.00%)

Model: mistralai/mistral-nemo
  Invalid results: 0 (0.00%)

Model: liquid/lfm-3b
  Invalid results: 0 (0.00%)

Model: meta-llama/llama-3.1-8b-instruct
  Invalid results: 0 (0.00%)

Model: google/gemma-3-4b-it
  Invalid results: 0 (0.00%)

Model: sao10k/l3-lunaris-8b
  Invalid results: 0 (0.00%)

Model: nousresearch/hermes-2-pro-llama-3-8b
  Invalid results: 0 (0.00%)

Model: mistralai/mistral-7b-instruct
  Invalid results: 0 (0.00%)

Total invalid results across all models: 0

_____

## Examining Test Results

Now we have our pairwise comparisons for 15 sentences across 10 models, all healed where they failed initially. Now we need to analyse the variety and transitivity

In [269]:
pairwise_results_dfs['mistralai/mistral-7b-instruct']

     idx_1  idx_2                                          reasoning    result
0        0      1  Text 1 provides more specific details about cl...    text 1
1        0      2  The text discusses potential future climate re...  text 2\n
2        0      3  Text 1 provides more specific details about cl...    text 1
3        0      4  Text 1 provides more specific details about th...    text 1
4        0      5  Text 2 is more specific. While Text 1 discusse...    text 2
..     ...    ...                                                ...       ...
100     11     13  detailed disclosure\n\nThe breakdown provides ...  text 2\n
101     11     14  The breakdown provides specific details regard...  text 2\n
102     12     13  detailed disclosure\n\nThe breakdown provides ...  text 2\n
103     12     14  detailed disclosure\n\nThe breakdown provides ...  text 2\n
104     13     14  The JSON breakdown for Text 2 provides a more ...  text 2\n

[105 rows x 4 columns]

In [275]:
# The result should indicate the index that won, rather than the text number.
# For example, if the result is "text 1", replace it with the value in idx_1; if "text 2", use idx_2.

def convert_result_to_index(df):
    def get_winner(row):
        if isinstance(row['result'], str):
            if 'text 1' in row['result'].lower():
                return row['idx_1']
            elif 'text 2' in row['result'].lower():
                return row['idx_2']
        return None  # or np.nan if you prefer
    df = df.copy()
    df['winner_idx'] = df.apply(get_winner, axis=1)
    return df

In [276]:
for model, df in pairwise_results_dfs.items():
    pairwise_results_dfs[model] = convert_result_to_index(df)

In [277]:
pairwise_results_dfs['mistralai/mistral-7b-instruct']

,idx_1,idx_2,reasoning,result,winner_idx
0,0,1,Text 1 provides more specific details about cl...,text 1,0.0
1,0,2,The text discusses potential future climate re...,text 2\n,2.0
2,0,3,Text 1 provides more specific details about cl...,text 1,0.0
3,0,4,Text 1 provides more specific details about th...,text 1,0.0
4,0,5,Text 2 is more specific. While Text 1 discusse...,text 2,5.0
...,...,...,...,...,...
100,11,13,detailed disclosure\n\nThe breakdown provides ...,text 2\n,13.0
101,11,14,The breakdown provides specific details regard...,text 2\n,14.0
102,12,13,detailed disclosure\n\nThe breakdown provides ...,text 2\n,13.0
103,12,14,detailed disclosure\n\nThe breakdown provides ...,text 2\n,14.0
104,13,14,The JSON breakdown for Text 2 provides a more ...,text 2\n,14.0

In [305]:
from itertools import combinations

def check_transitivity(df):
    """
    Check transitivity violations in pairwise comparison data.
    
    Args:
        df: DataFrame with columns 'idx_1', 'idx_2', and 'winner_idx'
    
    Returns:
        dict with violation statistics and details
    """
    
    # Create a dictionary to store comparison results
    # Key: (idx_a, idx_b), Value: winner_idx
    comparisons = {}
    
    for _, row in df.iterrows():
        idx_a, idx_b = row['idx_1'], row['idx_2']
        winner = row['winner_idx']
        
        comparisons[(idx_a, idx_b)] = winner
    
    # Get all unique indices
    all_indices = set(df['idx_1'].unique()) | set(df['idx_2'].unique())
    
    # Check transitivity for all triplets
    violations = []
    total_triplets = 0
    
    for a, b, c in combinations(sorted(all_indices), 3):
        # Check if all three pairwise comparisons exist
        if (a, b) not in comparisons or (a, c) not in comparisons or (b, c) not in comparisons:
            print('This happened. This did not happen in testing originally, so pay attention to it.')
            continue
        
        total_triplets += 1
        
        winner_ab = comparisons[(a, b)]
        winner_ac = comparisons[(a, c)]
        winner_bc = comparisons[(b, c)]
        
        # Skip if any comparison resulted in 'neither' (represented as NaN or string). We should only have 'neither' if one of the texts is not climate litigation.
        if pd.isna(winner_ab) or pd.isna(winner_ac) or pd.isna(winner_bc):
            continue
        
        # Check all transitivity patterns
        # If a > b and a > c, we can't infer b vs c (both valid)
        # If a > b and b > c, then a must > c
        if winner_ab == a and winner_bc == b:
            if winner_ac != a:
                violations.append({
                    'triplet': (a, b, c),
                    'pattern': f"{a}>{b}, {b}>{c}",
                    'expected': f"{a}>{c}",
                    'actual': f"{int(winner_ac)}>{c if winner_ac == c else a}"
                })
        
        # If a > b and c > a, then c must > b
        elif winner_ab == a and winner_ac == c:
            if winner_bc != c:
                violations.append({
                    'triplet': (a, b, c),
                    'pattern': f"{a}>{b}, {c}>{a}",
                    'expected': f"{c}>{b}",
                    'actual': f"{int(winner_bc)}>{b if winner_bc == b else c}"
                })
        
        # If b > a and a > c, then b must > c
        elif winner_ab == b and winner_ac == a:
            if winner_bc != b:
                violations.append({
                    'triplet': (a, b, c),
                    'pattern': f"{b}>{a}, {a}>{c}",
                    'expected': f"{b}>{c}",
                    'actual': f"{int(winner_bc)}>{c if winner_bc == c else b}"
                })
        
        # If b > a and c > b, then c must > a
        elif winner_ab == b and winner_bc == c:
            if winner_ac != c:
                violations.append({
                    'triplet': (a, b, c),
                    'pattern': f"{b}>{a}, {c}>{b}",
                    'expected': f"{c}>{a}",
                    'actual': f"{int(winner_ac)}>{a if winner_ac == a else c}"
                })
        
        # If c > a and a > b, then c must > b
        elif winner_ac == c and winner_ab == a:
            if winner_bc != c:
                violations.append({
                    'triplet': (a, b, c),
                    'pattern': f"{c}>{a}, {a}>{b}",
                    'expected': f"{c}>{b}",
                    'actual': f"{int(winner_bc)}>{b if winner_bc == b else c}"
                })
        
        # If c > a and b > c, then b must > a
        elif winner_ac == c and winner_bc == b:
            if winner_ab != b:
                violations.append({
                    'triplet': (a, b, c),
                    'pattern': f"{c}>{a}, {b}>{c}",
                    'expected': f"{b}>{a}",
                    'actual': f"{int(winner_ab)}>{a if winner_ab == a else b}"
                })
    
    return {
        'total_triplets_checked': total_triplets,
        'violations': violations,
        'num_violations': len(violations),
        'transitivity_rate': 1 - (len(violations) / total_triplets) if total_triplets > 0 else 1.0
    }

In [279]:
for model, df in pairwise_results_dfs.items():
    results = check_transitivity(df)
    print(f"Model: {model}")
    print(f"Transitivity Rate: {results['transitivity_rate']:.2%}")
    print(f"Violations: {results['num_violations']} out of {results['total_triplets_checked']} triplets")

Model: meta-llama/llama-3.2-1b-instruct
Transitivity Rate: 95.60%
Violations: 20 out of 455 triplets
Model: liquid/lfm-7b
Transitivity Rate: 94.07%
Violations: 27 out of 455 triplets
Model: meta-llama/llama-3.2-3b-instruct
Transitivity Rate: 91.87%
Violations: 37 out of 455 triplets
Model: mistralai/mistral-nemo
Transitivity Rate: 86.15%
Violations: 63 out of 455 triplets
Model: liquid/lfm-3b
Transitivity Rate: 87.25%
Violations: 58 out of 455 triplets
Model: meta-llama/llama-3.1-8b-instruct
Transitivity Rate: 91.65%
Violations: 38 out of 455 triplets
Model: google/gemma-3-4b-it
Transitivity Rate: 98.68%
Violations: 6 out of 455 triplets
Model: sao10k/l3-lunaris-8b
Transitivity Rate: 96.70%
Violations: 15 out of 455 triplets
Model: nousresearch/hermes-2-pro-llama-3-8b
Transitivity Rate: 98.68%
Violations: 6 out of 455 triplets
Model: mistralai/mistral-7b-instruct
Transitivity Rate: 93.19%
Violations: 31 out of 455 triplets

In [290]:
#now I need to run these pairwise comparisons using a SOTA model 
SOTA_MODEL = 'openai/gpt-5-chat'

output_folder = "../SOTA_outputs"
os.makedirs(output_folder, exist_ok=True)

print(f"Running model: {SOTA_MODEL}")
for idx in range(15):
    print(f"Processing sentence {idx} with model {SOTA_MODEL}")
    run_and_save_one_text(idx, folder=output_folder, model=SOTA_MODEL)

Running model: openai/gpt-5-chat
Processing sentence 0 with model openai/gpt-5-chat
conversation history: [{'role': 'user', 'content': 'Summarize the following text: or other countries’ foreign travel policy have affected, and may continue to affect our results of operations.\nChanges in U.S. and other countries\' foreign policy have in the past and could in the future result in the imposition of travel restrictions or travel bans on persons to certain countries or result in the imposition of travel advisories, warnings, rules, regulations or legislation exposing us to penalties or claims of monetary damages. In addition, some countries have previously adopted restrictions against U.S. travelers. The timing and scope of these changes and regulations can be unpredictable, and they could cause us to cancel scheduled sailings, possibly on short notice, or could result in litigation against us. This, in turn, could decrease our revenue, increase our operating costs and otherwise impair our profitability.\nFactors associated with climate change, including an increasing global regulatory focus, could adversely affect our business.\nThere is increasing global regulatory focus on climate change, greenhouse gas and other emissions, and new laws and regulations are expanding mandatory disclosure, reporting and diligence requirements. These regulatory efforts, both internationally, regionally and nationally, are still developing, including the international alignment of such efforts, and we cannot yet determine what the final regulatory programs or their impact will be on our business. However, such climate change-related regulatory activity in the future may adversely affect our business and financial results by requiring us to reduce our emissions, pay for our emissions, modify our itineraries and may increase our exposure, if any, to climate change-related litigation. Such activity may also impact us by increasing our operating costs, including fuel costs. For example, the European Union has enacted parts of a series of significant carbon reforms under its Fit for 55 package designed to meet its 2030 emission goals, which would require us, among other things, to purchase emission allowances, increase the use of low carbon fuel onboard our vessels as well as connectivity to shore power.\nIn addition, various state, regional and foreign government or regulatory agencies have enacted, or may enact, environmental regulations or policies, such as requiring the use of low sulfur fuels (e.g., IMO Sulfur Limit) or the carbon intensity indicator regulation ("CII"), that have or could increase our direct cost to operate in certain markets, increase our cost of fuel, limit the supply of compliant fuel, cause us to incur significant expenses to purchase and/or develop new equipment and adversely impact the cruise vacation industry.'}]

============================================================
STEP 1: SUMMARY
============================================================
**Summary:**

The company’s operations and financial performance may be negatively affected by changes in U.S. and foreign travel and environmental policies. Shifts in foreign policy—such as travel restrictions, bans, or advisories—can disrupt scheduled sailings, increase litigation risks, and reduce revenue.

Additionally, evolving global climate change regulations and emissions reporting requirements could raise compliance, fuel, and operational costs. New rules (such as the EU’s *Fit for 55* measures, the IMO sulfur limits, and carbon intensity regulations) may require emission allowances, cleaner fuels, new equipment, or itinerary changes. These developments increase cost uncertainty and could materially impact profitability and the broader cruise industry.

============================================================
STEP 2: CLASSIFICATION
============================================================
**Assessment:**

Yes — this text **does include a reference to climate litigation**, though it is **general and anticipatory rather than specific**.

**Reasoning:**
- The passage explicitly mentions that climate change regulatory activity "may increase our exposure, if any, to *climate change-related litigation*."
- This phrase clearly refers to potential legal actions connected to climate change policy, regulation, or impacts — falling within the definition of climate litigation, as it concerns regulatory compliance and possible claims arising from climate-related obligations.
- However, the disclosure is **non-specific**: it does not identify any ongoing, threatened, or concluded legal actions, nor specify the nature of potential claims (e.g., regulatory breaches, failure to disclose, contribution to emissions).

**Conclusion:**
✅ **Classification:** Climate litigation disclosure (general/precautionary reference)
⚖️ **Specificity Level:** Low — mentions potential exposure to climate litigation, but without citing any actual or pending cases.

============================================================
STEP 3: VERIFICATION
============================================================
Acknowledged.

============================================================
STEP 4: BREAKDOWN (raw)
============================================================
{
  "parties": [],
  "case_title_or_docket": null,
  "forum_or_jurisdiction": null,
  "statute_reg_policy": [],
  "procedural_posture": null,
  "dates_or_timeframes": [],
  "monetary_or_quantified": [],
  "climate_linkage_summary": "The text notes a general possibility of exposure to climate change-related litigation stemming from evolving climate regulations but provides no specific details about any actual or threatened cases.",
  "climate_linkage_quotes": ["may increase our exposure, if any, ...

============================================================
STEP 5: SPECIFICITY
============================================================
mention only

============================================================
PIPELINE COMPLETE
============================================================
Classification: 1
Specificity: mention only
Processing sentence 1 with model openai/gpt-5-chat
conversation history: [{'role': 'user', 'content': "Summarize the following text: In the event we declare a dividend, we will need to repay amounts deferred under the export credit facilities.\nCompliance and Regulatory Risks\nChanges in U.S. or other countries’ foreign travel policy have affected, and may continue to affect our results of operations.\nChanges in U.S. and other countries' foreign policy have in the past and could in the future result in the imposition of travel restrictions or travel bans on persons to certain countries or result in the imposition of travel advisories, warnings, rules, regulations or legislation exposing us to penalties or claims of monetary damages. In addition, some countries have previously adopted restrictions against U.S. travelers. The timing and scope of these changes and regulations can be unpredictable, and they could cause us to cancel scheduled sailings, possibly on short notice, or could result in litigation against us. This, in turn, could decrease our revenue, increase our operating costs and otherwise impair our profitability.\nFactors associated with climate change, including an increasing global regulatory focus, could adversely affect our business.\nThere is increasing global regulatory focus on climate change, greenhouse gas and other emissions. These regulatory efforts, both internationally and in the U.S., are still developing, including the international alignment of such efforts, and we cannot yet determine what the final regulatory programs or their impact will be on our business. However, such climate change-related regulatory activity in the future may adversely affect our business and financial results by requiring us to reduce our emissions, pay for our emissions, modify our itineraries and may increase our exposure, if any, to climate change-related litigation. Such activity may also impact us by increasing our operating costs, including fuel costs. For example, the European Union has proposed and enacted parts of a series of significant carbon reforms under its Fit for 55 package designed to meet its 2030 emission goals, which would require us, among other things, to increase the use of low carbon fuel onboard our vessels as well as connectivity to shore power. Part of the reforms that were enacted includes updates to the European Union Emission Trading System that imposes requirements on us to purchase carbon emission allowances for our qualified emissions beginning in 2024.\nIn addition, the U.S."}]

============================================================
STEP 1: SUMMARY
============================================================
**Summary:**

If the company declares a dividend, it must first repay amounts previously deferred under its export credit facilities.

**Compliance and Regulatory Risks:**
- Changes in U.S. or foreign travel policies can negatively affect operations by triggering travel restrictions, advisories, or bans, potentially leading to voyage cancellations, litigation, revenue loss, and higher operating costs.
- Climate change-related regulations and policies pose additional risks. Expanding global regulatory efforts targeting greenhouse gas emissions—such as the EU’s “Fit for 55” initiative and its Emissions Trading System—could require the company to cut emissions, purchase carbon allowances, use cleaner fuel, connect to shore power, and shoulder higher compliance and fuel costs.
- These evolving environmental and policy frameworks create uncertainty and could materially impact profitability and financial performance.

============================================================
STEP 2: CLASSIFICATION
============================================================
This text **does reference climate litigation but only in a conditional and non‑specific way**, rather than describing any active or threatened case.

Here’s the reasoning:

- The disclosure acknowledges that *future climate change‑related regulatory activity “may increase our exposure, if any, to climate change‑related litigation.”*
- It therefore **identifies climate litigation as a potential risk**, but **does not describe any ongoing, threatened, or historical legal action** against the company.
- The primary focus is on regulatory compliance (e.g., EU “Fit for 55,” carbon allowances, emission reductions), not on litigation proceedings or allegations of wrongdoing.

**Assessment:**
✅ Mentions climate litigation
❌ Not an instance of actual or specific climate litigation disclosure

**Conclusion:**
This passage **is not itself climate litigation**, but rather a **general risk disclosure referring to possible exposure to climate litigation in the future.**

============================================================
STEP 3: VERIFICATION
============================================================
Acknowledged.

============================================================
STEP 4: BREAKDOWN (raw)
============================================================
{
  "parties": [],
  "case_title_or_docket": null,
  "forum_or_jurisdiction": null,
  "statute_reg_policy": [],
  "procedural_posture": null,
  "dates_or_timeframes": [],
  "monetary_or_quantified": [],
  "climate_linkage_summary": "The text refers generally to potential future exposure to climate change-related litigation arising from evolving regulatory requirements on emissions but provides no details about any specific case, jurisdiction, or parties.",
  "climate_linkage_quotes": ["may incre...

============================================================
STEP 5: SPECIFICITY
============================================================
mention only

============================================================
PIPELINE COMPLETE
============================================================
Classification: 1
Specificity: mention only
Processing sentence 2 with model openai/gpt-5-chat
conversation history: [{'role': 'user', 'content': 'Summarize the following text: However, such climate change-related regulatory activity in the future may adversely affect our business and financial results by requiring us to reduce our emissions, pay for our emissions, modify our itineraries and may increase our exposure, if any, to climate change-related litigation. Such activity may also impact us by increasing our operating costs, including fuel costs. For example, the European Union has proposed a series of significant carbon reforms under its Fit for 55 package designed to meet its 2030 emission goals, which would require us, among other things, to increase the use of low carbon fuel onboard our vessels as well as connectivity to shore power. The proposed legislation also includes updates to the European Union Emission Trading System which would impose requirements to purchase carbon emission allowances beginning in 2024. In addition, the U.S. and various state and foreign government or regulatory agencies have enacted, or may enact, environmental regulations or policies, such as requiring the use of low sulfur fuels (e.g., IMO Sulfur Limit) or the incoming carbon intensity indicator regulation, that have or could increase our direct cost to operate in certain markets, increase our cost of fuel, limit the supply of compliant fuel, cause us to incur significant expenses to purchase and/or develop new equipment and adversely impact the cruise vacation industry. If enacted, these regulations may individually or collectively have a material adverse effect on our business and results of operations due to increased costs associated with compliance and modified itineraries in the affected regions.\nThere has also been growing environmental scrutiny of the environmental impact of the cruise vacation industry, and some environmental groups are advocating for more stringent regulation of ship emissions at berth and at sea. This negative publicity of the cruise industry and any related measures may lead to changes in consumer preferences, such as methods or frequency of travel, which could adversely impact our operations and financial results and subject us to reputational impacts and costs.\nLabor, health and safety, financial responsibility and other maritime regulations and measures could affect operations and increase operating costs. We are subject to\nvarious international, national, state and local laws, regulations and treaties that govern, among other things, discharge from our ships, safety standards applicable to our ships, treatment of disabled persons, health and sanitary standards applicable to our guests, security standards on board our ships and at the ship/port interface areas, and financial responsibilities to our guests. These issues are, and we believe will continue to be, an area of focus by the relevant authorities throughout the world.'}]

============================================================
STEP 1: SUMMARY
============================================================
The text outlines potential risks and impacts of evolving climate, environmental, and maritime regulations on the company’s operations and financial performance. It explains that new and proposed regulations—such as the EU’s *Fit for 55* package, updates to the EU Emissions Trading System, and other U.S. and international environmental measures—could increase operational and fuel costs, require investment in new technologies (e.g., low-carbon fuels, shore power), and potentially alter cruise itineraries. These compliance obligations may collectively have a material adverse effect on the company’s business results.

The text also highlights increased public and regulatory scrutiny of the cruise industry’s environmental footprint, which could lead to reputational damage, shifting consumer behavior, and further financial impacts. Additionally, ongoing labor, health and safety, financial responsibility, and maritime regulations impose continuing operational and cost pressures.

In essence, the passage identifies expanding environmental regulation, reputational risk, and regulatory compliance burdens as material factors that could negatively affect the company’s financial position and operations.

============================================================
STEP 2: CLASSIFICATION
============================================================
This text **does reference climate litigation**, but only **in a limited and potential sense**, rather than describing any specific legal actions or ongoing cases.

### Assessment:
- The passage includes the phrase: *“may increase our exposure, if any, to climate change-related litigation”*.
- This indicates acknowledgment of a **risk** or **possibility** of being subject to climate-related legal actions in the future, rather than disclosure of any **current or pending** climate litigation.

### Classification:
- **Yes**, the text qualifies as a **climate litigation disclosure**, because it explicitly mentions potential *climate change-related litigation*.
- **However**, it is **generic and non-specific** — it does not describe actual lawsuits, claims, or legal proceedings, only a *possible exposure* contingent upon future regulatory activity.

### Specificity level:
- **Type:** Forward-looking risk disclosure referencing potential exposure.
- **Specificity:** **Low** — no details of actual or threatened litigation, only a recognition that regulatory changes *may* increase the likelihood of such cases.

============================================================
STEP 3: VERIFICATION
============================================================
Acknowledged.

============================================================
STEP 4: BREAKDOWN (raw)
============================================================
{
  "parties": [],
  "case_title_or_docket": null,
  "forum_or_jurisdiction": null,
  "statute_reg_policy": [],
  "procedural_posture": null,
  "dates_or_timeframes": [],
  "monetary_or_quantified": [],
  "climate_linkage_summary": "The text briefly mentions the potential for future exposure to climate change-related litigation as a possible outcome of evolving climate regulations, but provides no concrete details about any actual or pending cases.",
  "climate_linkage_quotes": ["may increase ou...

============================================================
STEP 5: SPECIFICITY
============================================================
mention only

============================================================
PIPELINE COMPLETE
============================================================
Classification: 1
Specificity: mention only
Processing sentence 3 with model openai/gpt-5-chat

In [292]:
#now we need to do the pairwise comparisons for the SOTA model 
model_df = load_full_messages(SOTA_MODEL)
print(f"Loaded {len(model_df)} rows for model: {SOTA_MODEL}")
if len(model_df) != 15:
    print(f"Error: load_full_messages for model '{SOTA_MODEL}' returned {len(model_df)} rows instead of 15.")
SOTA_results = by_model_pairwise(model_df)

Loaded 15 rows for model: openai/gpt-5-chat
Comparing sentence 0 with sentence 1
The text primarily discusses potential operational and financial risks associated with changing travel and environmental policies, with a secondary mention of potential climate litigation exposure. However, the disclosure is highly anticipatory and lacks specific details regarding any actual or threatened legal actions.

FINAL: text 1
In the following content, extract the final decision. Return ONLY 'text 1' or 'text 2' or 'neither' (no other text). If absent, infer from the last explicit choice.

The text primarily discusses potential operational and financial risks associated with changing travel and environmental policies, with a secondary mention of potential climate litigation exposure. However, the disclosure is highly anticipatory and lacks specific details regarding any actual or threatened legal actions.

FINAL: text 1
text 1

Comparing sentence 0 with sentence 2
The text primarily focuses on the *potential* for future litigation stemming from evolving climate regulations, rather than detailing any existing or planned legal actions. It lacks specifics regarding parties involved, jurisdictions, statutes, or quantifiable impacts.

FINAL: text 1
In the following content, extract the final decision. Return ONLY 'text 1' or 'text 2' or 'neither' (no other text). If absent, infer from the last explicit choice.

The text primarily focuses on the *potential* for future litigation stemming from evolving climate regulations, rather than detailing any existing or planned legal actions. It lacks specifics regarding parties involved, jurisdictions, statutes, or quantifiable impacts.

FINAL: text 1
text 1

Comparing sentence 0 with sentence 3
Rationale: The text details financial accounting adjustments and disclosures, focusing on transactions like asset amortization, sale gains, and legal contingencies (the Havana Docks litigation). While the Havana Docks litigation *is* mentioned, it pertains to a property dispute and doesn't involve climate change claims, policy challenges, or any other elements characteristic of climate litigation. The other items are purely financial and lack any connection to climate-related issues.

FINAL: text 2
In the following content, extract the final decision. Return ONLY 'text 1' or 'text 2' or 'neither' (no other text). If absent, infer from the last explicit choice.

Rationale: The text details financial accounting adjustments and disclosures, focusing on transactions like asset amortization, sale gains, and legal contingencies (the Havana Docks litigation). While the Havana Docks litigation *is* mentioned, it pertains to a property dispute and doesn't involve climate change claims, policy challenges, or any other elements characteristic of climate litigation. The other items are purely financial and lack any connection to climate-related issues.

FINAL: text 2
Okay, I understand. Please provide the text.

Comparing sentence 0 with sentence 4
Rationale: The text primarily discusses general environmental liability and regulatory compliance, with only a brief, anticipatory reference to potential climate litigation. It lacks specific details about ongoing cases, parties involved, or the nature of the claims. The disclosure is broad and doesn't delve into the specifics of climate-related legal actions.

FINAL: text 2
In the following content, extract the final decision. Return ONLY 'text 1' or 'text 2' or 'neither' (no other text). If absent, infer from the last explicit choice.

Rationale: The text primarily discusses general environmental liability and regulatory compliance, with only a brief, anticipatory reference to potential climate litigation. It lacks specific details about ongoing cases, parties involved, or the nature of the claims. The disclosure is broad and doesn't delve into the specifics of climate-related legal actions.

FINAL: text 2
Okay, I understand. Please provide the text.

Comparing sentence 0 with sentence 5
Rationale: The text primarily discusses general business and regulatory risks, including potential litigation related to environmental and community impacts, but it lacks specific details about any ongoing or threatened climate litigation cases, legal claims, or regulatory challenges directly tied to climate change. It’s a broad discussion of risk, not a disclosure of specific climate litigation.

FINAL: text 1
In the following content, extract the final decision. Return ONLY 'text 1' or 'text 2' or 'neither' (no other text). If absent, infer from the last explicit choice.

Rationale: The text primarily discusses general business and regulatory risks, including potential litigation related to environmental and community impacts, but it lacks specific details about any ongoing or threatened climate litigation cases, legal claims, or regulatory challenges directly tied to climate change. It’s a broad discussion of risk, not a disclosure of specific climate litigation.

FINAL: text 1
Okay, please provide the text. I’m ready to analyze it and determine the final decision as you’ve outlined.

Comparing sentence 0 with sentence 6
Rationale: The text identifies CNX as a party to climate change lawsuits, which is a relevant detail for climate litigation disclosure. However, it lacks specific details about the nature of the lawsuits, the legal arguments involved, or any associated monetary claims or regulatory frameworks. It’s a mention of litigation, but not a detailed disclosure.

FINAL: text 2
In the following content, extract the final decision. Return ONLY 'text 1' or 'text 2' or 'neither' (no other text). If absent, infer from the last explicit choice.

Rationale: The text identifies CNX as a party to climate change lawsuits, which is a relevant detail for climate litigation disclosure. However, it lacks specific details about the nature of the lawsuits, the legal arguments involved, or any associated monetary claims or regulatory frameworks. It’s a mention of litigation, but not a detailed disclosure.

FINAL: text 2
Okay, I understand. Please provide the text.

Comparing sentence 0 with sentence 7
Rationale: The text mentions potential litigation risk and lawsuits related to climate-related damages, but it lacks specific details about the cases, parties involved, or the nature of the claims. It’s a general statement of exposure rather than a concrete disclosure of ongoing or threatened litigation.

FINAL: text 2
In the following content, extract the final decision. Return ONLY 'text 1' or 'text 2' or 'neither' (no other text). If absent, infer from the last explicit choice.

Rationale: The text mentions potential litigation risk and lawsuits related to climate-related damages, but it lacks specific details about the cases, parties involved, or the nature of the claims. It’s a general statement of exposure rather than a concrete disclosure of ongoing or threatened litigation.

FINAL: text 2
Okay, I understand. Please provide the text.

Comparing sentence 0 with sentence 8
The text primarily discusses regulatory risks and potential impacts related to climate change, rather than specific legal actions or litigation. It outlines evolving regulations and policies, but lacks details about any ongoing or threatened lawsuits.

FINAL: text 2
In the following content, extract the final decision. Return ONLY 'text 1' or 'text 2' or 'neither' (no other text). If absent, infer from the last explicit choice.

The text primarily discusses regulatory risks and potential impacts related to climate change, rather than specific legal actions or litigation. It outlines evolving regulations and policies, but lacks details about any ongoing or threatened lawsuits.

FINAL: text 2
text 2

Comparing sentence 0 with sentence 9
The breakdown provides a general overview of legal proceedings and investigations, but lacks specific details about the nature of the climate-related lawsuits, the parties involved beyond broad categories, and the potential outcomes. It’s a mention of climate litigation rather than a detailed disclosure.

FINAL: text 2
In the following content, extract the final decision. Return ONLY 'text 1' or 'text 2' or 'neither' (no other text). If absent, infer from the last explicit choice.

The breakdown provides a general overview of legal proceedings and investigations, but lacks specific details about the nature of the climate-related lawsuits, the parties involved beyond broad categories, and the potential outcomes. It’s a mention of climate litigation rather than a detailed disclosure.

FINAL: text 2
text 2

Comparing sentence 0 with sentence 10
The text references climate change as one of several types of legal claims CNX faces, but lacks specific details about any particular climate-related litigation. It’s a general acknowledgment of potential exposure.

FINAL: text 1
In the following content, extract the final decision. Return ONLY 'text 1' or 'text 2' or 'neither' (no other text). If absent, infer from the last explicit choice.

The text references climate change as one of several types of legal claims CNX faces, but lacks specific details about any particular climate-related litigation. It’s a general acknowledgment of potential exposure.

FINAL: text 1
text 1

Comparing sentence 0 with sentence 11
Rationale: The text primarily discusses general regulatory pressures and market trends related to the oil and gas industry, including emission programs and ESG considerations. While it mentions lawsuits, it lacks specific details about the cases – parties involved, legal claims, or monetary amounts – making it a vague disclosure of potential climate litigation risk rather than a detailed one.

FINAL: text 2
In the following content, extract the final decision. Return ONLY 'text 1' or 'text 2' or 'neither' (no other text). If absent, infer from the last explicit choice.

Rationale: The text primarily discusses general regulatory pressures and market trends related to the oil and gas industry, including emission programs and ESG considerations. While it mentions lawsuits, it lacks specific details about the cases – parties involved, legal claims, or monetary amounts – making it a vague disclosure of potential climate litigation risk rather than a detailed one.

FINAL: text 2
Okay, please provide the text. I’m ready to analyze it and determine the final decision as you’ve outlined.

Comparing sentence 0 with sentence 12
The text primarily discusses regulatory developments and policy shifts related to greenhouse gas (GHG) emissions, rather than specific legal actions or claims. It identifies a trend of increasing civil litigation and regulatory focus on climate change, but lacks details about any particular cases or legal proceedings.

FINAL: text 2
In the following content, extract the final decision. Return ONLY 'text 1' or 'text 2' or 'neither' (no other text). If absent, infer from the last explicit choice.

The text primarily discusses regulatory developments and policy shifts related to greenhouse gas (GHG) emissions, rather than specific legal actions or claims. It identifies a trend of increasing civil litigation and regulatory focus on climate change, but lacks details about any particular cases or legal proceedings.

FINAL: text 2
text 2

Comparing sentence 0 with sentence 13
Rationale: The disclosure identifies potential climate litigation exposure but lacks specific details regarding the lawsuits themselves – no case names, jurisdictions, or legal claims are provided. It’s a general statement of risk rather than a concrete description of ongoing legal actions.

FINAL: text 1
In the following content, extract the final decision. Return ONLY 'text 1' or 'text 2' or 'neither' (no other text). If absent, infer from the last explicit choice.

Rationale: The disclosure identifies potential climate litigation exposure but lacks specific details regarding the lawsuits themselves – no case names, jurisdictions, or legal claims are provided. It’s a general statement of risk rather than a concrete description of ongoing legal actions.

FINAL: text 1
Okay, please provide the text. I’m ready to analyze it and determine the final decision as you’ve outlined.

Comparing sentence 0 with sentence 14
Rationale: The text identifies potential future regulatory changes and their possible impacts on operations, but it lacks specific details about any existing or threatened legal actions related to climate change. It’s a general discussion of potential risks rather than a concrete disclosure of litigation.

FINAL: text 2
In the following content, extract the final decision. Return ONLY 'text 1' or 'text 2' or 'neither' (no other text). If absent, infer from the last explicit choice.

Rationale: The text identifies potential future regulatory changes and their possible impacts on operations, but it lacks specific details about any existing or threatened legal actions related to climate change. It’s a general discussion of potential risks rather than a concrete disclosure of litigation.

FINAL: text 2
Okay, I understand. Please provide the text.

Comparing sentence 1 with sentence 2
The text primarily discusses potential future regulatory risks related to climate change and environmental compliance, rather than detailing any specific ongoing or threatened legal actions. It acknowledges a *possibility* of litigation but lacks specifics regarding parties, jurisdictions, statutes, or any quantifiable elements.

FINAL: text 1
In the following content, extract the final decision. Return ONLY 'text 1' or 'text 2' or 'neither' (no other text). If absent, infer from the last explicit choice.

The text primarily discusses potential future regulatory risks related to climate change and environmental compliance, rather than detailing any specific ongoing or threatened legal actions. It acknowledges a *possibility* of litigation but lacks specifics regarding parties, jurisdictions, statutes, or any quantifiable elements.

FINAL: text 1
text 1

Comparing sentence 1 with sentence 3
Rationale: The text describes financial reporting adjustments and disclosures, with only a single mention of a litigation case (the Havana Docks litigation) that does not relate to climate change. The details provided are purely accounting and legal, lacking any specific information about climate-related claims, impacts, or policy.

FINAL: text 2
In the following content, extract the final decision. Return ONLY 'text 1' or 'text 2' or 'neither' (no other text). If absent, infer from the last explicit choice.

Rationale: The text describes financial reporting adjustments and disclosures, with only a single mention of a litigation case (the Havana Docks litigation) that does not relate to climate change. The details provided are purely accounting and legal, lacking any specific information about climate-related claims, impacts, or policy.

FINAL: text 2
Okay, I understand. Please provide the text.

Comparing sentence 1 with sentence 4
The text provides a general overview of potential climate-related litigation risks, but lacks specific details about any ongoing or threatened cases. It describes a *possibility* of litigation rather than detailing actual legal proceedings.

FINAL: text 2
In the following content, extract the final decision. Return ONLY 'text 1' or 'text 2' or 'neither' (no other text). If absent, infer from the last explicit choice.

The text provides a general overview of potential climate-related litigation risks, but lacks specific details about any ongoing or threatened cases. It describes a *possibility* of litigation rather than detailing actual legal proceedings.

FINAL: text 2
text 2

Comparing sentence 1 with sentence 5
The text discusses general business and regulatory risks, including potential litigation related to environmental concerns and public perception, but it lacks the specific details—such as parties involved, legal claims, or regulatory citations—required to be considered a disclosure of climate litigation. It’s a broad risk assessment, not a description of an actual or threatened legal action.

FINAL: text 1
In the following content, extract the final decision. Return ONLY 'text 1' or 'text 2' or 'neither' (no other text). If absent, infer from the last explicit choice.

The text discusses general business and regulatory risks, including potential litigation related to environmental concerns and public perception, but it lacks the specific details—such as parties involved, legal claims, or regulatory citations—required to be considered a disclosure of climate litigation. It’s a broad risk assessment, not a description of an actual or threatened legal action.

FINAL: text 1
text 1

Comparing sentence 1 with sentence 6
Rationale: The text identifies the existence of climate change lawsuits but lacks specific details regarding the cases, parties involved, or legal claims. It’s a general statement of involvement rather than a detailed disclosure of litigation.

FINAL: text 2
In the following content, extract the final decision. Return ONLY 'text 1' or 'text 2' or 'neither' (no other text). If absent, infer from the last explicit choice.

Rationale: The text identifies the existence of climate change lawsuits but lacks specific details regarding the cases, parties involved, or legal claims. It’s a general statement of involvement rather than a detailed disclosure of litigation.

FINAL: text 2
Okay, I understand. Please provide the text.

Comparing sentence 1 with sentence 7
The disclosure mentions potential future litigation risk related to climate change, but it lacks specific details about any ongoing or threatened legal actions. It describes a general concern rather than a concrete case or legal strategy.

FINAL: text 2
In the following content, extract the final decision. Return ONLY 'text 1' or 'text 2' or 'neither' (no other text). If absent, infer from the last explicit choice.

The disclosure mentions potential future litigation risk related to climate change, but it lacks specific details about any ongoing or threatened legal actions. It describes a general concern rather than a concrete case or legal strategy.

FINAL: text 2
text 2

Comparing sentence 1 with sentence 8
Text 2

FINAL: text 2
In the following content, extract the final decision. Return ONLY 'text 1' or 'text 2' or 'neither' (no other text). If absent, infer from the last explicit choice.

Text 2

FINAL: text 2
text 2

Comparing sentence 1 with sentence 9
The breakdown provides some details about the lawsuits (parties involved), but lacks specific information about the legal claims, the jurisdictions involved, or the potential remedies being sought. It’s a general mention of litigation rather than a detailed disclosure.

FINAL: text 2
In the following content, extract the final decision. Return ONLY 'text 1' or 'text 2' or 'neither' (no other text). If absent, infer from the last explicit choice.

The breakdown provides some details about the lawsuits (parties involved), but lacks specific information about the legal claims, the jurisdictions involved, or the potential remedies being sought. It’s a general mention of litigation rather than a detailed disclosure.

FINAL: text 2
text 2

Comparing sentence 1 with sentence 10
The text primarily details financial reporting and risk disclosures, including derivative settlements and potential litigation accruals. While it mentions “climate change” as a factor in potential litigation, it lacks specific details about any ongoing or threatened legal actions, case names, jurisdictions, or quantifiable damages. It’s a general acknowledgment of potential exposure rather than a description of a specific climate litigation case.

FINAL: text 1
In the following content, extract the final decision. Return ONLY 'text 1' or 'text 2' or 'neither' (no other text). If absent, infer from the last explicit choice.


In [296]:
# Let's see if there are any invalid responses for the SOTA results.
def check_invalid_results_single(df):
    """
    Checks for invalid results in a single pairwise results DataFrame.
    Returns a dictionary with counts and indices of invalid results.
    """
    invalid_indices = []
    for idx, row in df.iterrows():
        result = str(row.get('result', '')).strip().lower()
        if result not in ['text 1', 'text 2']:
            invalid_indices.append(idx)
    return {
        'num_invalid': len(invalid_indices),
        'invalid_indices': invalid_indices
    }

invalid_results = check_invalid_results_single(SOTA_results)
print(invalid_results)

#let's see these invalid results 
# Show the rows in SOTA_results where the result is invalid
invalid_indices = invalid_results['invalid_indices']
if invalid_indices:
    print("Invalid result rows:")
    display(SOTA_results.loc[invalid_indices])
else:
    print("No invalid result rows found.")

{'num_invalid': 26, 'invalid_indices': [2, 3, 4, 5, 6, 10, 12, 13, 15, 18, 23, 26, 27, 28, 29, 30, 31, 35, 37, 38, 60, 63, 69, 86, 95, 98]}
Invalid result rows:

,idx_1,idx_2,reasoning,result
2,0,3,Rationale: The text details financial accounti...,"Okay, I understand. Please provide the text.\n"
3,0,4,Rationale: The text primarily discusses genera...,"Okay, I understand. Please provide the text.\n"
4,0,5,Rationale: The text primarily discusses genera...,"Okay, please provide the text. I’m ready to an..."
5,0,6,Rationale: The text identifies CNX as a party ...,"Okay, I understand. Please provide the text.\n"
6,0,7,Rationale: The text mentions potential litigat...,"Okay, I understand. Please provide the text.\n"
10,0,11,Rationale: The text primarily discusses genera...,"Okay, please provide the text. I’m ready to an..."
12,0,13,Rationale: The disclosure identifies potential...,"Okay, please provide the text. I’m ready to an..."
13,0,14,Rationale: The text identifies potential futur...,"Okay, I understand. Please provide the text.\n"
15,1,3,Rationale: The text describes financial report...,"Okay, I understand. Please provide the text.\n"
18,1,6,Rationale: The text identifies the existence o...,"Okay, I understand. Please provide the text.\n"
23,1,11,Rationale: The text primarily discusses genera...,"Okay, I understand. Please provide the text.\n"
26,1,14,Rationale: The text describes potential regula...,"Okay, I understand. Please provide the text.\n"
27,2,3,Rationale: The text details financial accounti...,"Okay, I understand. Please provide the text.\n"
28,2,4,Rationale: The text primarily focuses on broad...,"Okay, I understand. Please provide the text.\n"
29,2,5,Rationale: The text primarily discusses genera...,"Okay, please provide the text. I’m ready to an..."
30,2,6,Rationale: The text identifies the existence o...,"Okay, I understand. Please provide the text.\n"
31,2,7,Rationale: The text identifies a *potential* r...,"Okay, I understand. Please provide the text.\n"
35,2,11,Rationale: The text primarily focuses on the r...,"Okay, I understand. Please provide the text.\n"
37,2,13,Rationale: The text identifies a potential ris...,"Okay, please provide the text. I’m ready to an..."
38,2,14,Rationale: The text primarily describes regula...,"Okay, I understand. Please provide the text.\n"
60,5,6,Rationale: The text identifies the existence o...,"Okay, I understand. Please provide the text.\n"
63,5,9,Rationale: The disclosure identifies legal pro...,"Okay, I understand. Please provide the text.\n"
69,6,7,Rationale: The disclosure mentions litigation ...,"Okay, I understand. Please provide the text.\n"
86,8,11,Rationale: The text primarily describes regula...,"Okay, I understand. Please provide the text.\n"
95,10,11,Rationale: The text primarily describes genera...,"Okay, I understand. Please provide the text.\n"
98,10,14,Rationale: The text primarily describes regula...,"Okay, I understand. Please provide the text.\n"

In [300]:
#for the invalid results, search within the reasoning column and see if it says FINAL: text 1 or FINAL: text 2. If it does, replace the result with the correct text.
for idx, row in SOTA_results.iterrows():
    if idx in invalid_indices:
        reasoning = row['reasoning']
        if 'FINAL: text 1' in reasoning:
            SOTA_results.at[idx, 'result'] = 'text 1'
        elif 'FINAL: text 2' in reasoning:
            SOTA_results.at[idx, 'result'] = 'text 2'

In [301]:
invalid_results = check_invalid_results_single(SOTA_results)

In [302]:
invalid_results

{'num_invalid': 0, 'invalid_indices': []}

In [307]:
#ok now let's check the transitivity 
SOTA_results = convert_result_to_index(SOTA_results)
results = check_transitivity(SOTA_results)
print(f"Model: {SOTA_MODEL}")
print(f"Transitivity Rate: {results['transitivity_rate']:.2%}")
print(f"Violations: {results['num_violations']} out of {results['total_triplets_checked']} triplets")

Model: openai/gpt-5-chat
Transitivity Rate: 89.89%
Violations: 46 out of 455 triplets

Since this actually underperformed the cheaper models, we are not going to use this as a test comparison

Isntead, we are going to take the top three performers from the cheaper models and test their variability

____

In [310]:
three_models = ['google/gemma-3-4b-it', 'nousresearch/hermes-2-pro-llama-3-8b', 'sao10k/l3-lunaris-8b']

# For each model, treat it as the "gold standard" and compare the other two to it
for i, gold_model in enumerate(three_models):
    gold_df = pairwise_results_dfs[gold_model].reset_index(drop=True)
    print(f"\nUsing {gold_model} as the gold standard:")
    for j, compare_model in enumerate(three_models):
        if gold_model == compare_model:
            continue
        compare_df = pairwise_results_dfs[compare_model].reset_index(drop=True)
        # Compare the 'winner_idx' columns
        if len(gold_df) != len(compare_df):
            print(f"  WARNING: {compare_model} has {len(compare_df)} rows, but {gold_model} has {len(gold_df)} rows.")
            min_len = min(len(gold_df), len(compare_df))
            gold_winners = gold_df['winner_idx'][:min_len]
            compare_winners = compare_df['winner_idx'][:min_len]
        else:
            gold_winners = gold_df['winner_idx']
            compare_winners = compare_df['winner_idx']
        agreement = (gold_winners == compare_winners).mean()
        print(f"  Agreement with {compare_model}: {agreement:.2%} ({(gold_winners == compare_winners).sum()}/{len(gold_winners)})")

Using google/gemma-3-4b-it as the gold standard:
  Agreement with nousresearch/hermes-2-pro-llama-3-8b: 96.19% (101/105)
  Agreement with sao10k/l3-lunaris-8b: 90.48% (95/105)

Using nousresearch/hermes-2-pro-llama-3-8b as the gold standard:
  Agreement with google/gemma-3-4b-it: 96.19% (101/105)
  Agreement with sao10k/l3-lunaris-8b: 88.57% (93/105)

Using sao10k/l3-lunaris-8b as the gold standard:
  Agreement with google/gemma-3-4b-it: 90.48% (95/105)
  Agreement with nousresearch/hermes-2-pro-llama-3-8b: 88.57% (93/105)

So, from that, I see that gemma and nousresearch largely agree.

In [348]:
output_folder = "../outputs"

**This is really bad!! I need to fix this so output folder isn't hard coded in any of my functions because I have two output functions**

In [397]:
#for gemma and nousresearch, let's do a test of inverse comparisons
def by_model_pairwise_reversed(existing_results_df, model):
    import json
    reversed_results = []
    df = load_full_messages(model, output_folder = '../outputs/single/')
    # Get all unique pairs from existing results
    for _, row in existing_results_df.iterrows():
        idx_1 = row['idx_1']
        idx_2 = row['idx_2']
        
        print(f"Comparing sentence {idx_2} with sentence {idx_1} (reversed)")
        
        try:
            # Extract the full message text - NOTE THE REVERSED ORDER
            breakdown_1 = df[df['file_name'].str.contains(f'full_messages_{idx_2}_')]['full_message'].values[0]
            breakdown_2 = df[df['file_name'].str.contains(f'full_messages_{idx_1}_')]['full_message'].values[0]
            
            full_result, binary_result = slimmer_pairwise(breakdown_1, breakdown_2, model=model)
            reversed_results.append({
                "idx_1": idx_2,  # Reversed
                "idx_2": idx_1,  # Reversed
                "reasoning": full_result,
                "result": binary_result,
                "model": model
            })
        except json.JSONDecodeError as e:
            print(f"  Skipping pair ({idx_2}, {idx_1}) due to JSON error: {e}")
            continue
        except Exception as e:
            # Optionally, you can skip any other error as well, or re-raise
            print(f"  Skipping pair ({idx_2}, {idx_1}) due to error: {e}")
            continue
    
    return pd.DataFrame(reversed_results)

In [352]:
gemma_reversed = by_model_pairwise_reversed(pairwise_results_dfs['google/gemma-3-4b-it'], 'google/gemma-3-4b-it')

Comparing sentence 1 with sentence 0 (reversed)
Text 2 is more specific due to its detailed discussion of specific regulations (EU Fit for 55, CII, IMO Sulfur Limit) and their potential financial impacts. Text 1 primarily focuses on broader risks and lacks the granular detail necessary to be considered highly specific.

FINAL: text 2
In the following content, extract the final decision. Return ONLY 'text 1' or 'text 2' or 'neither' (no other text). If absent, infer from the last explicit choice.

Text 2 is more specific due to its detailed discussion of specific regulations (EU Fit for 55, CII, IMO Sulfur Limit) and their potential financial impacts. Text 1 primarily focuses on broader risks and lacks the granular detail necessary to be considered highly specific.

FINAL: text 2
text 2

Comparing sentence 2 with sentence 0 (reversed)
The text primarily focuses on geopolitical risks related to foreign travel policy and the increasing regulatory pressure from climate change, specifically highlighting the potential for litigation arising from inadequate disclosure of climate-related risks. While it touches upon climate regulations, the core concern is the *potential for legal action* stemming from the company's failure to adequately address these risks.

FINAL: text 2
In the following content, extract the final decision. Return ONLY 'text 1' or 'text 2' or 'neither' (no other text). If absent, infer from the last explicit choice.

The text primarily focuses on geopolitical risks related to foreign travel policy and the increasing regulatory pressure from climate change, specifically highlighting the potential for litigation arising from inadequate disclosure of climate-related risks. While it touches upon climate regulations, the core concern is the *potential for legal action* stemming from the company's failure to adequately address these risks.

FINAL: text 2
text 2

Comparing sentence 3 with sentence 0 (reversed)
The text primarily discusses geopolitical risks related to foreign travel policy and the increasing regulatory focus on climate change, specifically referencing regulations like the CII and the EU’s Fit for 55 package. While the potential for litigation is mentioned, the core concern revolves around the *failure to adequately disclose* these risks and the potential financial consequences. The discussion of regulatory compliance and the need for adaptation aligns strongly with the definition of “Failure to disclose climate-related risks or impacts” within the context of climate litigation.

FINAL: text 2
In the following content, extract the final decision. Return ONLY 'text 1' or 'text 2' or 'neither' (no other text). If absent, infer from the last explicit choice.

The text primarily discusses geopolitical risks related to foreign travel policy and the increasing regulatory focus on climate change, specifically referencing regulations like the CII and the EU’s Fit for 55 package. While the potential for litigation is mentioned, the core concern revolves around the *failure to adequately disclose* these risks and the potential financial consequences. The discussion of regulatory compliance and the need for adaptation aligns strongly with the definition of “Failure to disclose climate-related risks or impacts” within the context of climate litigation.

FINAL: text 2
text 2

Comparing sentence 4 with sentence 0 (reversed)
The text primarily focuses on geopolitical risks and environmental regulations, specifically concerning cruise operations and the potential for litigation arising from these factors. While the climate change discussion is present, the core concern is the *risk of litigation related to regulatory non-compliance and travel disruptions*, rather than direct climate change impacts. The text highlights potential financial consequences (penalties, lost revenue) stemming from these risks.

FINAL: text 2
In the following content, extract the final decision. Return ONLY 'text 1' or 'text 2' or 'neither' (no other text). If absent, infer from the last explicit choice.

The text primarily focuses on geopolitical risks and environmental regulations, specifically concerning cruise operations and the potential for litigation arising from these factors. While the climate change discussion is present, the core concern is the *risk of litigation related to regulatory non-compliance and travel disruptions*, rather than direct climate change impacts. The text highlights potential financial consequences (penalties, lost revenue) stemming from these risks.

FINAL: text 2
text 2

Comparing sentence 5 with sentence 0 (reversed)
The text primarily focuses on geopolitical risks (foreign travel policy) and regulatory risks (climate change and environmental regulations), rather than directly addressing legal actions specifically related to climate change. While the potential for litigation is mentioned, the core of the disclosure revolves around the *risk* of disruption due to external factors, not a specific climate lawsuit.

FINAL: text 2
In the following content, extract the final decision. Return ONLY 'text 1' or 'text 2' or 'neither' (no other text). If absent, infer from the last explicit choice.

The text primarily focuses on geopolitical risks (foreign travel policy) and regulatory risks (climate change and environmental regulations), rather than directly addressing legal actions specifically related to climate change. While the potential for litigation is mentioned, the core of the disclosure revolves around the *risk* of disruption due to external factors, not a specific climate lawsuit.

FINAL: text 2
text 2

Comparing sentence 6 with sentence 0 (reversed)
The text primarily discusses geopolitical risks related to foreign travel policy and the increasing regulatory focus on climate change. While the potential for litigation is mentioned, the core concern revolves around the *failure to adequately disclose* these risks and the potential financial consequences. The text highlights specific regulations (IMO Sulfur Limit, CII) and the uncertainty surrounding future climate policies, indicating a vulnerability to legal challenges if these risks aren't transparently communicated.

FINAL: text 2
In the following content, extract the final decision. Return ONLY 'text 1' or 'text 2' or 'neither' (no other text). If absent, infer from the last explicit choice.

The text primarily discusses geopolitical risks related to foreign travel policy and the increasing regulatory focus on climate change. While the potential for litigation is mentioned, the core concern revolves around the *failure to adequately disclose* these risks and the potential financial consequences. The text highlights specific regulations (IMO Sulfur Limit, CII) and the uncertainty surrounding future climate policies, indicating a vulnerability to legal challenges if these risks aren't transparently communicated.

FINAL: text 2
text 2

Comparing sentence 7 with sentence 0 (reversed)
The text explicitly discusses the potential for litigation arising from climate change-related regulatory actions, particularly concerning emissions and travel restrictions. While it doesn't detail specific lawsuits or legal claims, it acknowledges the risk of financial penalties and legal challenges, making it a clear example of a climate litigation concern. The discussion of the EU’s “Fit for 55” package and the CII regulation provides concrete examples of the regulatory landscape that could lead to litigation.

FINAL: text 2
In the following content, extract the final decision. Return ONLY 'text 1' or 'text 2' or 'neither' (no other text). If absent, infer from the last explicit choice.

The text explicitly discusses the potential for litigation arising from climate change-related regulatory actions, particularly concerning emissions and travel restrictions. While it doesn't detail specific lawsuits or legal claims, it acknowledges the risk of financial penalties and legal challenges, making it a clear example of a climate litigation concern. The discussion of the EU’s “Fit for 55” package and the CII regulation provides concrete examples of the regulatory landscape that could lead to litigation.

FINAL: text 2
text 2

Comparing sentence 8 with sentence 0 (reversed)
Text 2 represents a more specific disclosure regarding climate litigation risk. While text 1 mentions “climate change risk” and “litigation,” text 2 explicitly details the regulatory pressures stemming from the EU’s “Fit for 55” package and the CII, providing concrete examples of potential legal challenges and the specific actions required to comply. The discussion of potential monetary damages (fines) further strengthens the specificity.

FINAL: text 2
In the following content, extract the final decision. Return ONLY 'text 1' or 'text 2' or 'neither' (no other text). If absent, infer from the last explicit choice.

Text 2 represents a more specific disclosure regarding climate litigation risk. While text 1 mentions “climate change risk” and “litigation,” text 2 explicitly details the regulatory pressures stemming from the EU’s “Fit for 55” package and the CII, providing concrete examples of potential legal challenges and the specific actions required to comply. The discussion of potential monetary damages (fines) further strengthens the specificity.

FINAL: text 2
text 2
Comparing sentence 9 with sentence 0 (reversed)
The text clearly outlines potential legal risks stemming from geopolitical instability and evolving environmental regulations. While it doesn't detail specific lawsuits or legal claims, it explicitly acknowledges the *potential* for litigation related to travel restrictions and non-compliance with environmental standards. The discussion of regulatory changes like the CII and the EU’s Fit for 55 package, coupled with the company’s acknowledgement of uncertainty and potential financial impact, demonstrates a level of detail and concern that goes beyond a simple “mention only” disclosure. The proactive identification of these risks and the company’s awareness of potential liabilities elevate the disclosure to a “detailed disclosure” level.

FINAL: text 2
In the following content, extract the final decision. Return ONLY 'text 1' or 'text 2' or 'neither' (no other text). If absent, infer from the last explicit choice.

The text clearly outlines potential legal risks stemming from geopolitical instability and evolving environmental regulations. While it doesn't detail specific lawsuits or legal claims, it explicitly acknowledges the *potential* for litigation related to travel restrictions and non-compliance with environmental standards. The discussion of regulatory changes like the CII and the EU’s Fit for 55 package, coupled with the company’s acknowledgement of uncertainty and potential financial impact, demonstrates a level of detail and concern that goes beyond a simple “mention only” disclosure. The proactive identification of these risks and the company’s awareness of potential liabilities elevate the disclosure to a “detailed disclosure” level.

FINAL: text 2
text 2

Comparing sentence 10 with sentence 0 (reversed)
The text presents a significant risk related to potential legal action stemming from the company’s failure to adequately disclose climate-related risks. The discussion of travel restrictions, regulatory changes (like the CII and IMO Sulfur Limit), and the potential for litigation directly addresses the “Failure to disclose climate-related risks or impacts” category of climate litigation. While the text doesn't detail specific legal claims or parties, it clearly identifies a vulnerability that could lead to legal action.

FINAL: text 2
In the following content, extract the final decision. Return ONLY 'text 1' or 'text 2' or 'neither' (no other text). If absent, infer from the last explicit choice.

The text presents a significant risk related to potential legal action stemming from the company’s failure to adequately disclose climate-related risks. The discussion of travel restrictions, regulatory changes (like the CII and IMO Sulfur Limit), and the potential for litigation directly addresses the “Failure to disclose climate-related risks or impacts” category of climate litigation. While the text doesn't detail specific legal claims or parties, it clearly identifies a vulnerability that could lead to legal action.

FINAL: text 2
text 2

Comparing sentence 11 with sentence 0 (reversed)
The text explicitly discusses the potential for litigation arising from climate change-related regulatory activity, particularly concerning the EU’s “Fit for 55” package and the CII regulation. It details the potential financial consequences (penalties, increased costs) and the company’s acknowledgment of uncertainty surrounding future regulations. This level of detail regarding potential legal risks and financial impacts, coupled with the specific regulatory examples, elevates the disclosure beyond a simple mention of climate risk.

FINAL: text 2
In the following content, extract the final decision. Return ONLY 'text 1' or 'text 2' or 'neither' (no other text). If absent, infer from the last explicit choice.

The text explicitly discusses the potential for litigation arising from climate change-related regulatory activity, particularly concerning the EU’s “Fit for 55” package and the CII regulation. It details the potential financial consequences (penalties, increased costs) and the company’s acknowledgment of uncertainty surrounding future regulations. This level of detail regarding potential legal risks and financial impacts, coupled with the specific regulatory examples, elevates the disclosure beyond a simple mention of climate risk.

FINAL: text 2
text 2

Comparing sentence 12 with sentence 0 (reversed)
The text primarily focuses on geopolitical risks and regulatory changes impacting a cruise line's operations, specifically related to travel restrictions and environmental regulations. While the discussion of climate change and regulatory responses is present, the core concern revolves around the *potential for litigation arising from disruptions to operations due to external policy changes*, rather than direct climate-related claims. The text highlights the uncertainty surrounding future regulations and their potential financial impact, which is a key element of a failure to disclose climate risks.

FINAL: text 2
In the following content, extract the final decision. Return ONLY 'text 1' or 'text 2' or 'neither' (no other text). If absent, infer from the last explicit choice.

The text primarily focuses on geopolitical risks and regulatory changes impacting a cruise line's operations, specifically related to travel restrictions and environmental regulations. While the discussion of climate change and regulatory responses is present, the core concern revolves around the *potential for litigation arising from disruptions to operations due to external policy changes*, rather than direct climate-related claims. The text highlights the uncertainty surrounding future regulations and their potential financial impact, which is a key element of a failure to disclose climate risks.

FINAL: text 2
text 2

Comparing sentence 13 with sentence 0 (reversed)
The text primarily discusses geopolitical risks related to foreign travel policy and the increasing regulatory focus on climate change. While the potential for litigation is mentioned, the core concern revolves around the *failure to adequately disclose* these risks, aligning with the definition of “Failure to disclose climate-related risks or impacts.” The discussion of specific regulations (IMO Sulfur Limit, CII) and the potential financial consequences demonstrates a direct link to climate litigation.

FINAL: text 2
In the following content, extract the final decision. Return ONLY 'text 1' or 'text 2' or 'neither' (no other text). If absent, infer from the last explicit choice.

The text primarily discusses geopolitical risks related to foreign travel policy and the increasing regulatory focus on climate change. While the potential for litigation is mentioned, the core concern revolves around the *failure to adequately disclose* these risks, aligning with the definition of “Failure to disclose climate-related risks or impacts.” The discussion of specific regulations (IMO Sulfur Limit, CII) and the potential financial consequences demonstrates a direct link to climate litigation.

FINAL: text 2
text 2

Comparing sentence 14 with sentence 0 (reversed)
The text primarily focuses on the *risk* of climate-related regulations and geopolitical events impacting the company's operations, rather than presenting a specific legal claim or action. While it acknowledges the *potential* for litigation, it doesn't detail any existing or anticipated legal proceedings. The disclosure is detailed in outlining the various regulatory pressures and potential disruptions, but it lacks the specific elements (e.g., a named case, a quantified monetary claim) that would classify it as a concrete instance of climate litigation.

FINAL: text 2
In the following content, extract the final decision. Return ONLY 'text 1' or 'text 2' or 'neither' (no other text). If absent, infer from the last explicit choice.

The text primarily focuses on the *risk* of climate-related regulations and geopolitical events impacting the company's operations, rather than presenting a specific legal claim or action. While it acknowledges the *potential* for litigation, it doesn't detail any existing or anticipated legal proceedings. The disclosure is detailed in outlining the various regulatory pressures and potential disruptions, but it lacks the specific elements (e.g., a named case, a quantified monetary claim) that would classify it as a concrete instance of climate litigation.

FINAL: text 2
text 2

Comparing sentence 2 with sentence 1 (reversed)
Text 2

FINAL: text 2
In the following content, extract the final decision. Return ONLY 'text 1' or 'text 2' or 'neither' (no other text). If absent, infer from the last explicit choice.

Text 2

FINAL: text 2
text 2

Comparing sentence 3 with sentence 1 (reversed)
Text 2

FINAL: Text 2
In the following content, extract the final decision. Return ONLY 'text 1' or 'text 2' or 'neither' (no other text). If absent, infer from the last explicit choice.

Text 2

FINAL: Text 2
text 2

Comparing sentence 4 with sentence 1 (reversed)
Text 2

FINAL: text 2
In the following content, extract the final decision. Return ONLY 'text 1' or 'text 2' or 'neither' (no other text). If absent, infer from the last explicit choice.

Text 2

FINAL: text 2
text 2

Comparing sentence 5 with sentence 1 (reversed)
Text 2 demonstrates a higher level of specificity regarding climate litigation risks. While text 1 touches on environmental risks, text 2 directly addresses the potential for litigation stemming from climate change regulations (specifically the EU’s Fit for 55 package and the EU ETS), outlines concrete actions required for compliance (increased low-carbon fuel use, shore power connectivity), and quantifies a specific financial obligation (carbon emission allowance purchases). Text 1 is more general and lacks these specific details.

FINAL: text 2
In the following content, extract the final decision. Return ONLY 'text 1' or 'text 2' or 'neither' (no other text). If absent, infer from the last explicit choice.

Text 2 demonstrates a higher level of specificity regarding climate litigation risks. While text 1 touches on environmental risks, text 2 directly addresses the potential for litigation stemming from climate change regulations (specifically the EU’s Fit for 55 package and the EU ETS), outlines concrete actions required for compliance (increased low-carbon fuel use, shore power connectivity), and quantifies a specific financial obligation (carbon emission allowance purchases). Text 1 is more general and lacks these specific details.

FINAL: text 2
text 2

In [353]:
gemma_reversed = convert_result_to_index(gemma_reversed)
gemma_reversed

,idx_1,idx_2,reasoning,result,model,winner_idx
0,1,0,Text 2 is more specific due to its detailed di...,text 2\n,google/gemma-3-4b-it,0.0
1,2,0,The text primarily focuses on geopolitical ris...,text 2\n,google/gemma-3-4b-it,0.0
2,3,0,The text primarily discusses geopolitical risk...,text 2\n,google/gemma-3-4b-it,0.0
3,4,0,The text primarily focuses on geopolitical ris...,text 2\n,google/gemma-3-4b-it,0.0
4,5,0,The text primarily focuses on geopolitical ris...,text 2\n,google/gemma-3-4b-it,0.0
...,...,...,...,...,...,...
100,13,11,"```json\n{\n ""parties"": [\n ""various state...",text 2\n,google/gemma-3-4b-it,11.0
101,14,11,Text 2 is significantly more specific than Tex...,text 2\n,google/gemma-3-4b-it,11.0
102,13,12,Text 2 demonstrates a significantly higher lev...,text 2\n,google/gemma-3-4b-it,12.0
103,14,12,The text exhibits a high degree of specificity...,text 2\n,google/gemma-3-4b-it,12.0
104,14,13,Text 2\n\nFINAL: text 2\n,text 2\n,google/gemma-3-4b-it,13.0

In [319]:
gemma_forward = pairwise_results_dfs['google/gemma-3-4b-it']

In [354]:
# Compare gemma_forward and gemma_reversed: see how often winner_idx is the same, give a percentage

# Merge on (idx_1, idx_2) <-> (idx_2, idx_1) to align forward and reversed
merged = pd.merge(
    gemma_forward,
    gemma_reversed,
    left_on=['idx_1', 'idx_2'],
    right_on=['idx_2', 'idx_1'],
    suffixes=('_forward', '_reversed')
)

# Compare winner_idx
same_winner = merged['winner_idx_forward'] == merged['winner_idx_reversed']
percent_same = same_winner.mean() * 100

print(f"Percentage of pairs where winner_idx is the same in forward and reversed: {percent_same:.2f}%")

Percentage of pairs where winner_idx is the same in forward and reversed: 3.81%

This is terrible!! It is basically just choosing #2 every time, and we are not seeing any agreement between the forward and reverse. 

I think I need to do this for all the models

In [355]:
# Count the percentage of times each original model predicts "text 1", "text 2", or "neither"
model_percentages = {}
for model, df in pairwise_results_dfs.items():
    # Normalize result column to strip whitespace and lowercase
    results = df['result'].astype(str).str.strip().str.lower()
    total = len(results)
    text1_count = ((results == 'text 1') | (results == 'text 1\n')).sum()
    text2_count = ((results == 'text 2') | (results == 'text 2\n')).sum()
    neither_count = total - text1_count - text2_count
    model_percentages[model] = {
        'text 1': round(100 * text1_count / total, 2) if total > 0 else 0,
        'text 2': round(100 * text2_count / total, 2) if total > 0 else 0,
        'neither': round(100 * neither_count / total, 2) if total > 0 else 0
    }

model_counts_df = pd.DataFrame.from_dict(model_percentages, orient='index').reset_index().rename(columns={'index': 'Model'})

In [337]:
model_counts_df

                                  Model  text 1  text 2  neither
0      meta-llama/llama-3.2-1b-instruct   24.76   72.38     2.86
1                         liquid/lfm-7b    9.52   90.48     0.00
2      meta-llama/llama-3.2-3b-instruct   15.24   84.76     0.00
3                mistralai/mistral-nemo   17.14   79.05     3.81
4                         liquid/lfm-3b   35.24   64.76     0.00
5      meta-llama/llama-3.1-8b-instruct   11.43   79.05     9.52
6                  google/gemma-3-4b-it    2.86   97.14     0.00
7                  sao10k/l3-lunaris-8b    7.62   91.43     0.95
8  nousresearch/hermes-2-pro-llama-3-8b    2.86   97.14     0.00
9         mistralai/mistral-7b-instruct   23.81   75.24     0.95

_____

## Working with reversed results

In [395]:
import glob

# Dictionary to hold reversed dataframes
pairwise_results_dfs_reversed = {}

# Get all reversed CSV files in the output directory
reversed_files = glob.glob("../outputs/reversed/pairwise_results_dfs_*_reversed.csv")

for fpath in reversed_files:
    # Extract model name from the filename
    fname = fpath.split('/')[-1]
    model_name = fname.replace('pairwise_results_dfs_', '').replace('_reversed.csv', '').replace('_', '/')
    # Some models may use underscores instead of slashes or dashes, revert what was done in save path
    # If your model naming scheme is more complex, improve this part
    model_name = model_name.replace('//', '/').replace('--', '-')
    try:
        df = pd.read_csv(fpath)
        pairwise_results_dfs_reversed[model_name] = df
    except Exception as e:
        print(f"Error loading {fname}: {e}")

Error loading pairwise_results_dfs_sao10k_l3_lunaris_8b_reversed.csv: No columns to parse from file
Error loading pairwise_results_dfs_mistralai_mistral_7b_instruct_reversed.csv: No columns to parse from file
Error loading pairwise_results_dfs_google_gemma_3_4b_it_reversed.csv: No columns to parse from file
Error loading pairwise_results_dfs_meta_llama_llama_3.1_8b_instruct_reversed.csv: No columns to parse from file

In [403]:
# Run for all models in pairwise_results_dfs, but skip models that already have 105 rows in their reversed dataframe

for model, df in pairwise_results_dfs.items():
    # If already processed and has 105 rows, skip
    reversed_df = pairwise_results_dfs_reversed.get(model)
    if reversed_df is not None and len(reversed_df) == 105:
        print(f"Skipping {model} as reversed results already have 105 rows.")
        continue
    if 'nous' in model: 
        print("skipping nous model")
        continue
    print(f"Processing {model}")
    try:
        pairwise_results_dfs_reversed[model] = by_model_pairwise_reversed(df, model)
    except Exception as e:
        print(f"Skipping model {model} due to error: {e}")
        continue

pairwise_results_dfs_reversed

Skipping meta-llama/llama-3.2-1b-instruct as reversed results already have 105 rows.
Skipping liquid/lfm-7b as reversed results already have 105 rows.
Skipping meta-llama/llama-3.2-3b-instruct as reversed results already have 105 rows.
Skipping mistralai/mistral-nemo as reversed results already have 105 rows.
Skipping liquid/lfm-3b as reversed results already have 105 rows.
Skipping meta-llama/llama-3.1-8b-instruct as reversed results already have 105 rows.
Skipping google/gemma-3-4b-it as reversed results already have 105 rows.
Skipping sao10k/l3-lunaris-8b as reversed results already have 105 rows.
skipping nous model
Processing mistralai/mistral-7b-instruct
Comparing sentence 1 with sentence 0 (reversed)
 The text does not provide specific details about a particular climate litigation case, parties involved, court or jurisdiction, statute or regulation, posture, dates, monetary amounts, or sought outcome. It only mentions the potential exposure to climate change-related litigation due to increasing global regulatory focus on climate change.

FINAL: mention only (Text 1 is more specific about climate litigation details)
In the following content, extract the final decision. Return ONLY 'text 1' or 'text 2' or 'neither' (no other text). If absent, infer from the last explicit choice.

 The text does not provide specific details about a particular climate litigation case, parties involved, court or jurisdiction, statute or regulation, posture, dates, monetary amounts, or sought outcome. It only mentions the potential exposure to climate change-related litigation due to increasing global regulatory focus on climate change.

FINAL: mention only (Text 1 is more specific about climate litigation details)

Comparing sentence 2 with sentence 0 (reversed)
 [/INST] Both texts are classified as "mention only" for climate litigation specificity, as they only vaguely reference potential exposure to climate change-related litigation without providing any specific details about ongoing or past cases, parties, jurisdictions, or statutes. However, Text 1 includes a slightly more detailed reference to the European Union's Fit for 55 package and its specific carbon reforms, which provides a bit more contextual clarity about the regulatory environment that could lead to litigation. Therefore, Text 1 is marginally more specific.

FINAL: text 1
In the following content, extract the final decision. Return ONLY 'text 1' or 'text 2' or 'neither' (no other text). If absent, infer from the last explicit choice.

 [/INST] Both texts are classified as "mention only" for climate litigation specificity, as they only vaguely reference potential exposure to climate change-related litigation without providing any specific details about ongoing or past cases, parties, jurisdictions, or statutes. However, Text 1 includes a slightly more detailed reference to the European Union's Fit for 55 package and its specific carbon reforms, which provides a bit more contextual clarity about the regulatory environment that could lead to litigation. Therefore, Text 1 is marginally more specific.

FINAL: text 1

Comparing sentence 3 with sentence 0 (reversed)
 The rationale is as follows:

Text 1 is not climate litigation, as it discusses financial adjustments and legal contingencies unrelated to climate change. Text 2, while mentioning potential exposure to climate change-related litigation, lacks specific details about the litigation (e.g., parties, case title, jurisdiction, statute, or procedural posture). It only vaguely references the possibility of such litigation without providing any concrete details. Therefore, Text 2 is a "mention only" disclosure, while Text 1 is not climate litigation at all.

FINAL: text 2
In the following content, extract the final decision. Return ONLY 'text 1' or 'text 2' or 'neither' (no other text). If absent, infer from the last explicit choice.

 The rationale is as follows:

Text 1 is not climate litigation, as it discusses financial adjustments and legal contingencies unrelated to climate change. Text 2, while mentioning potential exposure to climate change-related litigation, lacks specific details about the litigation (e.g., parties, case title, jurisdiction, statute, or procedural posture). It only vaguely references the possibility of such litigation without providing any concrete details. Therefore, Text 2 is a "mention only" disclosure, while Text 1 is not climate litigation at all.

FINAL: text 2

Comparing sentence 4 with sentence 0 (reversed)
 The first text provides detailed information about specific climate litigation cases, including the parties involved (states and municipalities vs. oil, natural gas, and coal producers), the nature of the claims (liability for climate-related weather events), and the sought outcome (monetary damages for remedial measures). This level of detail makes it a "detailed disclosure."

The second text, while mentioning potential exposure to climate change-related litigation, lacks specific details about the parties, cases, or sought outcomes, making it only a "mention only" disclosure.

FINAL: text 1
In the following content, extract the final decision. Return ONLY 'text 1' or 'text 2' or 'neither' (no other text). If absent, infer from the last explicit choice.

 The first text provides detailed information about specific climate litigation cases, including the parties involved (states and municipalities vs. oil, natural gas, and coal producers), the nature of the claims (liability for climate-related weather events), and the sought outcome (monetary damages for remedial measures). This level of detail makes it a "detailed disclosure."

The second text, while mentioning potential exposure to climate change-related litigation, lacks specific details about the parties, cases, or sought outcomes, making it only a "mention only" disclosure.

FINAL: text 1

Comparing sentence 5 with sentence 0 (reversed)
 The text does not provide specific details about a particular climate litigation case, court, or statute. It mentions potential exposure to climate change-related litigation, but the context is more about regulatory focus and potential impacts on business operations. Therefore, the text can be classified as 'mention only'.

FINAL: text 1
In the following content, extract the final decision. Return ONLY 'text 1' or 'text 2' or 'neither' (no other text). If absent, infer from the last explicit choice.

 The text does not provide specific details about a particular climate litigation case, court, or statute. It mentions potential exposure to climate change-related litigation, but the context is more about regulatory focus and potential impacts on business operations. Therefore, the text can be classified as 'mention only'.

FINAL: text 1
 Neither (the text does not provide a specific final decision)
Comparing sentence 6 with sentence 0 (reversed)
 [/INST] Text 1 provides specific details about climate litigation, including the number of lawsuits (four), the parties involved (communities against fossil fuel producers), and the procedural posture (defendant). Text 2 only mentions potential exposure to climate change-related litigation without any specific details. Therefore, Text 1 is more specific.

FINAL: text 1
In the following content, extract the final decision. Return ONLY 'text 1' or 'text 2' or 'neither' (no other text). If absent, infer from the last explicit choice.

 [/INST] Text 1 provides specific details about climate litigation, including the number of lawsuits (four), the parties involved (communities against fossil fuel producers), and the procedural posture (defendant). Text 2 only mentions potential exposure to climate change-related litigation without any specific details. Therefore, Text 1 is more specific.

FINAL: text 1

Comparing sentence 7 with sentence 0 (reversed)
 The text does not provide specific details about climate litigation, such as parties involved, case titles, jurisdictions, statutes, procedural postures, dates, or monetary amounts. It only mentions a potential exposure to climate change-related litigation without any concrete details. Therefore, it qualifies as a "mention only" disclosure.

FINAL: text 1
In the following content, extract the final decision. Return ONLY 'text 1' or 'text 2' or 'neither' (no other text). If absent, infer from the last explicit choice.

 The text does not provide specific details about climate litigation, such as parties involved, case titles, jurisdictions, statutes, procedural postures, dates, or monetary amounts. It only mentions a potential exposure to climate change-related litigation without any concrete details. Therefore, it qualifies as a "mention only" disclosure.

FINAL: text 1
 Neither (since the text does not provide a specific final decision)
Comparing sentence 8 with sentence 0 (reversed)

In the following content, extract the final decision. Return ONLY 'text 1' or 'text 2' or 'neither' (no other text). If absent, infer from the last explicit choice.




The following is a text:

The court considered the arguments presented by both parties. After careful deliberation, the judge ruled in favor of the defendant, stating that the plaintiff had failed to provide sufficient evidence to support their claims. The defendant's legal team successfully argued that the evidence presented was inconclusive and did not meet the burden of proof required under the law. The judge concluded that the plaintiff's case lacked merit and dismissed the case.

Based on the text, the final decision is:

text 2
Comparing sentence 9 with sentence 0 (reversed)
 The rationale is as follows:

Text 1 provides specific details about climate litigation, including the number of lawsuits (four), the parties involved (CNX and communities), and the nature of the claims (relating to climate change). It also mentions the procedural posture ("being pursued") and a timeframe ("beginning to gain prevalence in the courts"). These details make it a detailed disclosure.

Text 2, on the other hand, only mentions the potential for climate change-related litigation in a vague and general manner, without providing any specific details about the parties, cases, or procedural posture. It is a mention only.

FINAL: text 1
In the following content, extract the final decision. Return ONLY 'text 1' or 'text 2' or 'neither' (no other text). If absent, infer from the last explicit choice.

 The rationale is as follows:

Text 1 provides specific details about climate litigation, including the number of lawsuits (four), the parties involved (CNX and communities), and the nature of the claims (relating to climate change). It also mentions the procedural posture ("being pursued") and a timeframe ("beginning to gain prevalence in the courts"). These details make it a detailed disclosure.

Text 2, on the other hand, only mentions the potential for climate change-related litigation in a vague and general manner, without providing any specific details about the parties, cases, or procedural posture. It is a mention only.

FINAL: text 1

Comparing sentence 10 with sentence 0 (reversed)
 The rationale is that Text 1 explicitly mentions "climate change" in the context of lawsuits and claims, providing a direct linkage to climate litigation, whereas Text 2 only mentions potential exposure to climate change-related litigation without any specific details. Text 1 also includes more specific financial details and timeframes, making it more specific in terms of climate litigation. Therefore, Text 1 is the more specific text.

FINAL: text 1
In the following content, extract the final decision. Return ONLY 'text 1' or 'text 2' or 'neither' (no other text). If absent, infer from the last explicit choice.

 The rationale is that Text 1 explicitly mentions "climate change" in the context of lawsuits and claims, providing a direct linkage to climate litigation, whereas Text 2 only mentions potential exposure to climate change-related litigation without any specific details. Text 1 also includes more specific financial details and timeframes, making it more specific in terms of climate litigation. Therefore, Text 1 is the more specific text.

FINAL: text 1

Comparing sentence 11 with sentence 0 (reversed)
 The first text provides specific details about ongoing climate litigation, including the parties involved (states and municipalities), the nature of the claims (liability for climate-related events and damages), and the sought outcome (money damages for remedial measures). It also includes checkable elements such as the number of lawsuits ("close to two dozen") and the specific climate-related events mentioned (rising sea levels, severe storms, and heatwaves). In contrast, the second text only vaguely mentions potential exposure to climate change-related litigation without providing any specific details about the parties, cases, or sought outcomes. Therefore, the first text is more specific in its disclosure of climate litigation.

FINAL: text 1
In the following content, extract the final decision. Return ONLY 'text 1' or 'text 2' or 'neither' (no other text). If absent, infer from the last explicit choice.

 The first text provides specific details about ongoing climate litigation, including the parties involved (states and municipalities), the nature of the claims (liability for climate-related events and damages), and the sought outcome (money damages for remedial measures). It also includes checkable elements such as the number of lawsuits ("close to two dozen") and the specific climate-related events mentioned (rising sea levels, severe storms, and heatwaves). In contrast, the second text only vaguely mentions potential exposure to climate change-related litigation without providing any specific details about the parties, cases, or sought outcomes. Therefore, the first text is more specific in its disclosure of climate litigation.

FINAL: text 1

Comparing sentence 12 with sentence 0 (reversed)
 The rationale is that Text 1 provides more specific details about climate litigation, including references to specific regulations (e.g., Clean Air Act, Clean Power Plan, Affordable Clean Energy Rule), regulatory actions by different administrations, and a court decision (United States Court of Appeals for the D.C. Circuit). In contrast, Text 2 only mentions potential exposure to climate change-related litigation without providing any specific details about cases, parties, or legal actions. Therefore, Text 1 is more specific in its disclosure of climate litigation.

FINAL: text 1
In the following content, extract the final decision. Return ONLY 'text 1' or 'text 2' or 'neither' (no other text). If absent, infer from the last explicit choice.

 The rationale is that Text 1 provides more specific details about climate litigation, including references to specific regulations (e.g., Clean Air Act, Clean Power Plan, Affordable Clean Energy Rule), regulatory actions by different administrations, and a court decision (United States Court of Appeals for the D.C. Circuit). In contrast, Text 2 only mentions potential exposure to climate change-related litigation without providing any specific details about cases, parties, or legal actions. Therefore, Text 1 is more specific in its disclosure of climate litigation.

FINAL: text 1
 Based on the provided analysis, the final decision is 'text 1'.
Comparing sentence 13 with sentence 0 (reversed)
 The text does not provide specific details about climate litigation, such as the parties involved, the forum or jurisdiction, the statute or policy in question, the posture of the litigation, dates or timeframes, monetary amounts, or the sought outcome. It only mentions the potential for increased exposure to climate change-related litigation due to regulatory activity.

FINAL: neither
In the following content, extract the final decision. Return ONLY 'text 1' or 'text 2' or 'neither' (no other text). If absent, infer from the last explicit choice.

 The text does not provide specific details about climate litigation, such as the parties involved, the forum or jurisdiction, the statute or policy in question, the posture of the litigation, dates or timeframes, monetary amounts, or the sought outcome. It only mentions the potential for increased exposure to climate change-related litigation due to regulatory activity.

FINAL: neither

Comparing sentence 14 with sentence 0 (reversed)

In the following content, extract the final decision. Return ONLY 'text 1' or 'text 2' or 'neither' (no other text). If absent, infer from the last explicit choice.




The following is a text:

The court considered the arguments presented by both parties. After careful deliberation, the judge ruled in favor of the defendant, stating that the plaintiff had not provided sufficient evidence to support their claims. The defendant's motion for summary judgment was granted, and the case was dismissed.

Based on the text, the final decision is:

text 2
Comparing sentence 2 with sentence 1 (reversed)
 [/INST] Text 2 provides more specific details about climate litigation, including references to the European Union's Fit for 55 package and the European Union Emission Trading System, as well as a specific timeline (beginning in 2024) for regulatory requirements. This makes it more specific than Text 1, which only mentions potential exposure to climate change-related litigation without providing any additional details.

FINAL: text 2
In the following content, extract the final decision. Return ONLY 'text 1' or 'text 2' or 'neither' (no other text). If absent, infer from the last explicit choice.

 [/INST] Text 2 provides more specific details about climate litigation, including references to the European Union's Fit for 55 package and the European Union Emission Trading System, as well as a specific timeline (beginning in 2024) for regulatory requirements. This makes it more specific than Text 1, which only mentions potential exposure to climate change-related litigation without providing any additional details.

FINAL: text 2

Comparing sentence 3 with sentence 1 (reversed)
 The rationale is as follows:

Text 1 is not climate litigation, as it does not mention any climate-related legal actions or regulatory breaches. It only discusses financial adjustments and general litigation (Havana Docks) without any climate linkage.

Text 2, while mentioning potential exposure to climate change-related litigation, lacks specific details about the litigation itself (e.g., parties, case title, forum, or procedural posture). It provides some regulatory context (e.g., EU's Fit for 55 package and Emission Trading System) and a timeframe (beginning in 2024), but these are not tied to a specific litigation case. Thus, it qualifies as a "vague disclosure" of climate litigation risk.

Since Text 1 is not climate litigation, it is automatically chosen over Text 2, which is a vague disclosure.

FINAL: text 1
In the following content, extract the final decision. Return ONLY 'text 1' or 'text 2' or 'neither' (no other text). If absent, infer from the last explicit choice.

 The rationale is as follows:

Text 1 is not climate litigation, as it does not mention any climate-related legal actions or regulatory breaches. It only discusses financial adjustments and general litigation (Havana Docks) without any climate linkage.

Text 2, while mentioning potential exposure to climate change-related litigation, lacks specific details about the litigation itself (e.g., parties, case title, forum, or procedural posture). It provides some regulatory context (e.g., EU's Fit for 55 package and Emission Trading System) and a timeframe (beginning in 2024), but these are not tied to a specific litigation case. Thus, it qualifies as a "vague disclosure" of climate litigation risk.

Since Text 1 is not climate litigation, it is automatically chosen over Text 2, which is a vague disclosure.

FINAL: text 1


{'mistralai/mistral/nemo':      idx_1  idx_2                                          reasoning   result  \
 0        1      0  The text mentions potential exposure to climat...   text 2
 1        2      0  **Rationale:** While the text mentions potenti...  neither
 2        3      0  **Rationale:** The text mentions potential exp...  neither
 3        4      0  Text 1 provides more specific details about cl...   text 1
 4        5      0  The text mentions potential exposure to climat...  neither
 ..     ...    ...                                                ...      ...
 100     13     11  **Rationale:** Both texts mention climate chan...   text 1
 101     14     11  Text 1 does not relate to climate litigation, ...   text 2
 102     13     12  **Rationale:** The text discusses regulatory a...  neither
 103     14     12  **Rationale:** The text discusses regulatory a...  neither
 104     14     13  **Rationale:** The text provides some details ...   text 2

                       model
 0    mistralai/mistral-nemo
 1    mistralai/mistral-nemo
 2    mistralai/mistral-nemo
 3    mistralai/mistral-nemo
 4    mistralai/mistral-nemo
 ..                      ...
 100  mistralai/mistral-nemo
 101  mistralai/mistral-nemo
 102  mistralai/mistral-nemo
 103  mistralai/mistral-nemo
 104  mistralai/mistral-nemo

 [105 rows x 5 columns],
 'meta/llama/llama/3.2/3b/instruct':      idx_1  idx_2                                          reasoning   result  \
 0        1      0  Based on the breakdown, I would choose "detail...   text 2
 1        2      0  Based on the provided breakdown, I choose "det...   text 1
 2        3      0  Based on the breakdown, I choose "detailed dis...   text 2
 3        4      0  Based on the breakdown, I choose "detailed dis...   text 1
 4        5      0  Based on the breakdown, I chose "detailed disc...  neither
 ..     ...    ...                                                ...      ...
 100     13     11  Text 1 provides more specific details about cl...   text 1
 101     14     11  Text 1 is more specific than Text 2 because it...   Text 1
 102     13     12  Text 2 provides more specific details about cl...   text 2
 103     14     12  The breakdown provides a detailed and specific...   text 2
 104     14     13  The breakdown provides a detailed and specific...   text 2

                                 model
 0    meta-llama/llama-3.2-3b-instruct
 1    meta-llama/llama-3.2-3b-instruct
 2    meta-llama/llama-3.2-3b-instruct
 3    meta-llama/llama-3.2-3b-instruct
 4    meta-llama/llama-3.2-3b-instruct
 ..                                ...
 100  meta-llama/llama-3.2-3b-instruct
 101  meta-llama/llama-3.2-3b-instruct
 102  meta-llama/llama-3.2-3b-instruct
 103  meta-llama/llama-3.2-3b-instruct
 104  meta-llama/llama-3.2-3b-instruct

 [105 rows x 5 columns],
 'liquid/lfm/7b':      idx_1  idx_2                                          reasoning   result  \
 0        1      0  The text provides a general overview of potent...   text 1
 1        2      0  The text provides a general discussion on pote...   text 1
 2        3      0  The text provides a general discussion on pote...  neither
 3        4      0  The text provides a general overview of potent...   text 1
 4        5      0  Text 1 provides more specific details about cl...   text 1
 ..     ...    ...                                                ...      ...
 100     13     11  The text provides specific and checkable detai...   text 1
 101     14     11  The text provides specific and checkable detai...   text 1
 102     13     12  Text 1 is more specific in terms of climate li...   text 1
 103     14     12  The breakdown provides specific details direct...   text 1
 104     14     13  Text 1 and Text 2 both discuss climate litigat...  neither

              model
 0    liquid/lfm-7b
 1    liquid/lfm-7b
 2    liquid/lfm-7b
 3    liquid/lfm-7b
 4    liquid/lfm-7b
 ..             ...
 100  liquid/lfm-7b
 101  liquid/lfm-7b
 102  liquid/lfm-7b
 103  liquid/lfm-7b
 104  liquid/lfm-7b

 [105 rows x 5 columns],
 'meta/llama/llama/3.2/1b/instruct':      idx_1  idx_2                                          reasoning   result  \
 0        1      0  The structured breakdown provides a detailed a...   text 2
 1        2      0  Based on the structured breakdown, I would cho...   text 1
 2        3      0  Based on the breakdown, I choose "detailed dis...  neither
 3        4      0  The structured breakdown provides specific det...   text 2
 4        5      0  Based on the provided breakdowns, I would choo...   text 2
 ..     ...    ...                                                ...      ...
 100     13     11  Based on the breakdown, I choose "detailed dis...   text 1
 101     14     11  Text 1 has more specific details about the cli...   text 1
 102     13     12  Based on the provided text, I will choose the ...  neither
 103     14     12  The breakdown provides a detailed and specific...   text 2
 104     14     13  The breakdown of Text 2 is more detailed and s...   text 2

                                 model
 0    meta-llama/llama-3.2-1b-instruct
 1    meta-llama/llama-3.2-1b-instruct
 2    meta-llama/llama-3.2-1b-instruct
 3    meta-llama/llama-3.2-1b-instruct
 4    meta-llama/llama-3.2-1b-instruct
 ..                                ...
 100  meta-llama/llama-3.2-1b-instruct
 101  meta-llama/llama-3.2-1b-instruct
 102  meta-llama/llama-3.2-1b-instruct
 103  meta-llama/llama-3.2-1b-instruct
 104  meta-llama/llama-3.2-1b-instruct

 [105 rows x 5 columns],
 'liquid/lfm/3b':      idx_1  idx_2                                          reasoning   result  \
 0        1      0  Text 2 is more specific than Text 1 because it...   text 2
 1        2      0  ==============================================...  neither
 2        3      0                                      FINAL: text 1   text 1
 3        4      0  ==============================================...  neither
 4        5      0  Text 2 is more specific than Text 1 because it...   text 2
 ..     ...    ...                                                ...      ...
 100     13     11  {\n  "classification": "detailed disclosure",\...  neither
 101     14     11  ==============================================...  neither
 102     13     12  Final: The original text and the breakdown pro...  neither
 103     14     12  The rationale for choosing "basic disclosure" ...   text 1
 104     14     13  The specificity label chosen is "basic disclos...   text 1

              model
 0    liquid/lfm-3b
 1    liquid/lfm-3b
 2    liquid/lfm-3b
 3    liquid/lfm-3b
 4    liquid/lfm-3b
 ..             ...
 100  liquid/lfm-3b
 101  liquid/lfm-3b
 102  liquid/lfm-3b
 103  liquid/lfm-3b
 104  liquid/lfm-3b

 [105 rows x 5 columns],
 'meta-llama/llama-3.2-1b-instruct':      idx_1  idx_2                                          reasoning  \
 0        1      0  The structured breakdown provides a clear and ...
 1        2      0  Based on the structured breakdown, I would cho...
 2        3      0  Based on the breakdown, I choose "detailed dis...
 3        4      0  The structured breakdown provides specific det...
 4        5      0  Based on the provided breakdowns, I would choo...
 ..     ...    ...                                                ...
 100     13     11  Based on the breakdowns, I would choose "text ...
 101     14     11  Based on the provided breakdown, I choose:\n\n...
 102     13     12  The detailed disclosure label is chosen becaus...
 103     14     12  The breakdown provides a detailed and specific...
 104     14     13  The breakdown of Text 2 is more detailed and s...

                                                 result  \
 0                                               text 2
 1                                               text 1
 2                                              neither
 3                                               text 2
 4                                               text 2
 ..                                                 ...
 100                                             text 1
 101  **text 1**\n\nThe text does not provide any in...
 102                                             text 2
 103                                             text 2
 104                                             text 2

                                 model
 0    meta-llama/llama-3.2-1b-instruct
 1    meta-llama/llama-3.2-1b-instruct
 2    meta-llama/llama-3.2-1b-instruct
 3    meta-llama/llama-3.2-1b-instruct
 4    meta-llama/llama-3.2-1b-instruct
 ..                                ...
 100  meta-llama/llama-3.2-1b-instruct
 101  meta-llama/llama-3.2-1b-instruct
 102  meta-llama/llama-3.2-1b-instruct
 103  meta-llama/llama-3.2-1b-instruct
 104  meta-llama/llama-3.2-1b-instruct

 [105 rows x 5 columns],
 'liquid/lfm-7b':      idx_1  idx_2                                          reasoning  \
 0        1      0  The text provides a general overview of potent...
 1        2      0  The text provides a general discussion on pote...
 2        3      0  The text provides a general discussion on pote...
 3        4      0  The text provides a general overview of potent...
 4        5      0  The text broadly discusses potential impacts a...
 ..     ...    ...                                                ...
 100     13     11  The text provides specific and checkable detai...
 101     14     11  The text provides specific and checkable detai...
 102     13     12  The breakdown provides specific details direct...
 103     14     12  The breakdown provides specific details direct...
 104     14     13  The breakdown provides specific monetary amoun...

                                                 result          model
 0                                               text 1  liquid/lfm-7b
 1                                               text 1  liquid/lfm-7b
 2                                              neither  liquid/lfm-7b
 3                                               text 1  liquid/lfm-7b
 4    To adhere strictly to the instruction and the ...  liquid/lfm-7b
 ..                                                 ...            ...
 100  To infer the final decision based on the provi...  liquid/lfm-7b
 101                                             text 1  liquid/lfm-7b
 102  To determine the final decision, let's analyze...  liquid/lfm-7b
 103                                             text 1  liquid/lfm-7b
 104  To determine the final decision based on the p...  liquid/lfm-7b

 [105 rows x 5 columns],
 'meta-llama/llama-3.2-3b-instruct':      idx_1  idx_2                                          reasoning  \
 0        1      0  Based on the breakdown, I would choose "detail...
 1        2      0  Based on the breakdown, I would choose "detail...
 2        3      0  Based on the breakdown, I choose "detailed dis...
 3        4      0  Based on the breakdown, I choose "detailed dis...
 4        5      0  Based on the breakdown, I chose "detailed disc...
 ..     ...    ...                                                ...
 100     13     11  Based on the breakdown, I would choose "detail...
 101     14     11  The breakdown provides a high level of specifi...
 102     13     12
 103     14     12  The breakdown provides a detailed and specific...
 104     14     13  The breakdown provides a detailed and specific...

                                      result                             model
 0                                            meta-llama/llama-3.2-3b-instruct
 1                                    text 1  meta-llama/llama-3.2-3b-instruct
 2                                    text 2  meta-llama/llama-3.2-3b-instruct
 3                                    text 2  meta-llama/llama-3.2-3b-instruct
 4                                    text 2  meta-llama/llama-3.2-3b-instruct
 ..                                      ...                               ...
 100                                  text 2  meta-llama/llama-3.2-3b-instruct
 101                                  text 1  meta-llama/llama-3.2-3b-instruct
 102  I'm ready to assist. What is the text?  meta-llama/llama-3.2-3b-instruct
 103                                  text 2  meta-llama/llama-3.2-3b-instruct
 104                                  text 2  meta-llama/llama-3.2-3b-instruct

 [105 rows x 5 columns],
 'mistralai/mistral-nemo':      idx_1  idx_2                                          reasoning  \
 0        1      0  **Rationale:** The text mentions potential exp...
 1        2      0  **Rationale:** While the text mentions potenti...
 2        3      0  The text mentions potential exposure to climat...
 3        4      0  The text mentions potential exposure to climat...
 4        5      0  **Rationale:** The text mentions potential exp...
 ..     ...    ...                                                ...
 100     13     11  Rationale: Both texts mention climate change l...
 101     14     11  **Rationale:** Both texts mention climate chan...
 102     13     12  **Rationale:** Text 2 discusses regulatory act...
 103     14     12  The text discusses regulatory actions related ...
 104     14     13  **Rationale:** The text provides some details ...

                                                 result                   model
 0    **Text 1:** "The company is currently facing a...  mistralai/mistral-nemo
 1                                              neither  mistralai/mistral-nemo
 2                                              neither  mistralai/mistral-nemo
 3                                               text 2  mistralai/mistral-nemo
 4    **Text 1:** "The company has been sued for vio...  mistralai/mistral-nemo
 ..                                                 ...                     ...
 100                                            neither  mistralai/mistral-nemo
 101  **Text 1:** "Several cities and states have fi...  mistralai/mistral-nemo
 102                                            neither  mistralai/mistral-nemo
 103                                            neither  mistralai/mistral-nemo
 104                                             text 2  mistralai/mistral-nemo

 [105 rows x 5 columns],
 'liquid/lfm-3b':      idx_1  idx_2                                          reasoning  \
 0        1      0  ==============================================...
 1        2      0  ==============================================...
 2        3      0  The provided text offers a detailed disclosure...
 3        4      0  ==============================================...
 4        5      0  The provided text includes specific details ab...
 ..     ...    ...                                                ...
 100     13     11  {\n  "classification": "detailed disclosure",\...
 101     14     11  ==============================================...
 102     13     12  Final: The original text and the breakdown pro...
 103     14     12  {"classification": "detailed disclosure"}\n\nR...
 104     14     13  The specificity label chosen is "basic disclos...

                                                 result          model
 0    The final decision, based on the provided text...  liquid/lfm-3b
 1                                              neither  liquid/lfm-3b
 2                                              neither  liquid/lfm-3b
 3                                              neither  liquid/lfm-3b
 4                                              neither  liquid/lfm-3b
 ..                                                 ...            ...
 100                                            neither  liquid/lfm-3b
 101                                            neither  liquid/lfm-3b
 102                                            neither  liquid/lfm-3b
 103  The provided text does not contain a clear fin...  liquid/lfm-3b
 104                                             text 1  liquid/lfm-3b

 [105 rows x 5 columns],
 'meta-llama/llama-3.1-8b-instruct':      idx_1  idx_2                                          reasoning  \
 0        1      0  Based on the two texts, I would choose Text 1 ...
 1        2      0  Based on the breakdown of specificity for clim...
 2        3      0  Based on the two texts, I would choose Text 2 ...
 3        4      0                                      FINAL: text 1
 4        5      0                                      FINAL: text 2
 ..     ...    ...                                                ...
 100     13     11                                      FINAL: text 2
 101     14     11  Based on the breakdown of specificity for clim...
 102     13     12  The text provides some information about the e...
 103     14     12  Based on the breakdown, the text does not prov...
 104     14     13  Based on the breakdown of specificity for clim...

             result                             model
 0           text 1  meta-llama/llama-3.1-8b-instruct
 1    FINAL: text 1  meta-llama/llama-3.1-8b-instruct
 2           text 2  meta-llama/llama-3.1-8b-instruct
 3           text 1  meta-llama/llama-3.1-8b-instruct
 4           text 2  meta-llama/llama-3.1-8b-instruct
 ..             ...                               ...
 100         text 2  meta-llama/llama-3.1-8b-instruct
 101         text 1  meta-llama/llama-3.1-8b-instruct
 102         text 1  meta-llama/llama-3.1-8b-instruct
 103        neither  meta-llama/llama-3.1-8b-instruct
 104         text 1  meta-llama/llama-3.1-8b-instruct

 [105 rows x 5 columns],
 'google/gemma-3-4b-it':      idx_1  idx_2                                          reasoning  \
 0        1      0  Text 2 is more specific due to its detailed di...
 1        2      0  The text primarily focuses on geopolitical ris...
 2        3      0  The text primarily discusses geopolitical risk...
 3        4      0  The text primarily focuses on geopolitical ris...
 4        5      0  The text primarily focuses on geopolitical ris...
 ..     ...    ...                                                ...
 100     13     11  ```json\n{\n  "parties": [\n    "various state...
 101     14     11  Text 2 is significantly more specific than Tex...
 102     13     12  Text 2 demonstrates a significantly higher lev...
 103     14     12  The text exhibits a high degree of specificity...
 104     14     13                            Text 2\n\nFINAL: text 2

        result                 model
 0    text 2\n  google/gemma-3-4b-it
 1    text 2\n  google/gemma-3-4b-it
 2    text 2\n  google/gemma-3-4b-it
 3    text 2\n  google/gemma-3-4b-it
 4    text 2\n  google/gemma-3-4b-it
 ..        ...                   ...
 100  text 2\n  google/gemma-3-4b-it
 101  text 2\n  google/gemma-3-4b-it
 102  text 2\n  google/gemma-3-4b-it
 103  text 2\n  google/gemma-3-4b-it
 104  text 2\n  google/gemma-3-4b-it

 [105 rows x 5 columns],
 'sao10k/l3-lunaris-8b':      idx_1  idx_2                                          reasoning   result  \
 0        1      0  Rationale: The provided text is highly specifi...   text 1
 1        2      0  Rationale: Text 2 provides more specific detai...   text 2
 2        3      0  Rationale: The provided text is highly specifi...   text 2
 3        4      0  Rationale: Text 2 provides more specific detai...   text 2
 4        5      0  Rationale: Text 2 provides more specific detai...   text 2
 ..     ...    ...                                                ...      ...
 100     13     11  Rationale: The provided text offers a detailed...   text 2
 101     14     11  Rationale: The provided text offers a detailed...   text 2
 102     13     12  Rationale: The text provides some basic inform...  neither
 103     14     12  Rationale: The text provides a general overvie...  neither
 104     14     13  Rationale: The provided text offers a detailed...   text 2

                     model
 0    sao10k/l3-lunaris-8b
 1    sao10k/l3-lunaris-8b
 2    sao10k/l3-lunaris-8b
 3    sao10k/l3-lunaris-8b

In [404]:
#check if all the dfs have 105 rows
for model in pairwise_results_dfs_reversed.keys():
    print(model)
    if len(pairwise_results_dfs_reversed[model]) != 105:
        print(f"Model {model} has {len(pairwise_results_dfs_reversed[model])} rows instead of 105.")

mistralai/mistral/nemo
meta/llama/llama/3.2/3b/instruct
liquid/lfm/7b
meta/llama/llama/3.2/1b/instruct
liquid/lfm/3b
meta-llama/llama-3.2-1b-instruct
liquid/lfm-7b
meta-llama/llama-3.2-3b-instruct
mistralai/mistral-nemo
liquid/lfm-3b
meta-llama/llama-3.1-8b-instruct
google/gemma-3-4b-it
sao10k/l3-lunaris-8b
mistralai/mistral-7b-instruct

In [410]:
# Save both the forward and reversed results to local storage for all models, in separate folders
import os

forward_dir = '../outputs/forward'
reversed_dir = '../outputs/reversed'
os.makedirs(forward_dir, exist_ok=True)
os.makedirs(reversed_dir, exist_ok=True)

for model in pairwise_results_dfs.keys():
    safe_model_name = model.replace("/", "_").replace("-", "_")
    forward_path = os.path.join(forward_dir, f'pairwise_results_dfs_{safe_model_name}_forward.csv')
    reversed_path = os.path.join(reversed_dir, f'pairwise_results_dfs_{safe_model_name}_reversed.csv')
    if model in pairwise_results_dfs:
        pairwise_results_dfs[model].to_csv(forward_path, index=False)
    if model in pairwise_results_dfs_reversed:
        pairwise_results_dfs_reversed[model].to_csv(reversed_path, index=False)

In [406]:
invalid_results = check_invalid_results(pairwise_results_dfs_reversed)
invalid_counts = Counter()
for entry in invalid_results:
    model = entry['model']
    invalid_counts[model] += 1

# Print the percentage of invalid results for each model (out of 105)
for model in pairwise_results_dfs_reversed.keys():
    count = invalid_counts.get(model, 0)
    percent = (count / 105) * 100
    print(f"Model: {model}, Invalid results: {count} ({percent:.2f}%)")

Model: mistralai/mistral/nemo, Invalid results: 0 (0.00%)
Model: meta/llama/llama/3.2/3b/instruct, Invalid results: 0 (0.00%)
Model: liquid/lfm/7b, Invalid results: 0 (0.00%)
Model: meta/llama/llama/3.2/1b/instruct, Invalid results: 0 (0.00%)
Model: liquid/lfm/3b, Invalid results: 0 (0.00%)
Model: meta-llama/llama-3.2-1b-instruct, Invalid results: 18 (17.14%)
Model: liquid/lfm-7b, Invalid results: 32 (30.48%)
Model: meta-llama/llama-3.2-3b-instruct, Invalid results: 18 (17.14%)
Model: mistralai/mistral-nemo, Invalid results: 38 (36.19%)
Model: liquid/lfm-3b, Invalid results: 11 (10.48%)
Model: meta-llama/llama-3.1-8b-instruct, Invalid results: 1 (0.95%)
Model: google/gemma-3-4b-it, Invalid results: 6 (5.71%)
Model: sao10k/l3-lunaris-8b, Invalid results: 0 (0.00%)
Model: mistralai/mistral-7b-instruct, Invalid results: 103 (98.10%)

In [407]:
# Overwrite invalid results in pairwise_results_dfs with rerun slimmer_pairwise results
output_folder = "../outputs/single/"
for entry in invalid_results:
    model = entry['model']
    print(f"Model: {model}")
    idx_1 = entry['idx_1']
    idx_2 = entry['idx_2']
    # Get the model_df used for this model
    model_df = load_full_messages(model, output_folder)
    # Get the texts for idx_1 and idx_2
    text_1 = model_df.loc[model_df.index == idx_1, 'full_message'].values[0]
    text_2 = model_df.loc[model_df.index == idx_2, 'full_message'].values[0]
    # Run slimmer_pairwise on the two texts
    result, final_result = slimmer_pairwise(text_1, text_2)
    # Overwrite the result in the pairwise_results_dfs_reversed
    pairwise_df = pairwise_results_dfs_reversed[model]
    mask = (pairwise_df['idx_1'] == idx_1) & (pairwise_df['idx_2'] == idx_2)
    # Use .at to set the value for the single row
    idxs = pairwise_df.index[mask]
    if len(idxs) == 1:
        pairwise_results_dfs_reversed[model].at[idxs[0], 'result'] = final_result
        pairwise_results_dfs_reversed[model].at[idxs[0], 'reasoning'] = result
    elif len(idxs) == 0:
        print(f"Warning: No matching row found for model={model}, idx_1={idx_1}, idx_2={idx_2}")
    else:
        print(f"Warning: Multiple matching rows found for model={model}, idx_1={idx_1}, idx_2={idx_2}")

Model: meta-llama/llama-3.2-1b-instruct
Text 1 is more specific than Text 2 because it provides more details about the potential impact of climate change-related regulatory activity on the company's business, including specific regulations such as the European Union's Fit for 55 package and the IMO Sulfur Limit. Text 2, on the other hand, provides more general information about the company's concerns regarding climate change regulations and their potential impact on the natural gas industry.

FINAL: text 1
In the following content, extract the final decision. Return ONLY 'text 1' or 'text 2' or 'neither' (no other text). If absent, infer from the last explicit choice.

Text 1 is more specific than Text 2 because it provides more details about the potential impact of climate change-related regulatory activity on the company's business, including specific regulations such as the European Union's Fit for 55 package and the IMO Sulfur Limit. Text 2, on the other hand, provides more general information about the company's concerns regarding climate change regulations and their potential impact on the natural gas industry.

FINAL: text 1
text 1
Model: meta-llama/llama-3.2-1b-instruct
Text 1 is more specific about climate litigation, mentioning specific lawsuits and regulatory actions, whereas Text 2 is more focused on the company's concerns about climate change regulations and their potential impact on the business.

FINAL: text 1
In the following content, extract the final decision. Return ONLY 'text 1' or 'text 2' or 'neither' (no other text). If absent, infer from the last explicit choice.

Text 1 is more specific about climate litigation, mentioning specific lawsuits and regulatory actions, whereas Text 2 is more focused on the company's concerns about climate change regulations and their potential impact on the business.

FINAL: text 1
text 1
Model: meta-llama/llama-3.2-1b-instruct
Text 1 is more specific than Text 2 because it provides more details about the climate litigation, such as the parties involved, the type of lawsuit, and the potential impact on the company's business. Text 2, on the other hand, is more focused on the regulatory environment and the potential impact of climate change on the company's business, but it does not provide specific details about climate litigation.

FINAL: text 1
In the following content, extract the final decision. Return ONLY 'text 1' or 'text 2' or 'neither' (no other text). If absent, infer from the last explicit choice.

Text 1 is more specific than Text 2 because it provides more details about the climate litigation, such as the parties involved, the type of lawsuit, and the potential impact on the company's business. Text 2, on the other hand, is more focused on the regulatory environment and the potential impact of climate change on the company's business, but it does not provide specific details about climate litigation.

FINAL: text 1
text 1
Model: meta-llama/llama-3.2-1b-instruct
Text 1 has a more detailed breakdown of the regulatory landscape and the potential impact of climate change on the oil and gas industry, including specific mentions of EPA proposed revisions, state-level regulations, and lawsuits filed against oil and gas producers. Text 2, on the other hand, provides more general information about CNX's involvement in climate change lawsuits, but lacks specific details about the lawsuits themselves.

FINAL: text 1
In the following content, extract the final decision. Return ONLY 'text 1' or 'text 2' or 'neither' (no other text). If absent, infer from the last explicit choice.

Text 1 has a more detailed breakdown of the regulatory landscape and the potential impact of climate change on the oil and gas industry, including specific mentions of EPA proposed revisions, state-level regulations, and lawsuits filed against oil and gas producers. Text 2, on the other hand, provides more general information about CNX's involvement in climate change lawsuits, but lacks specific details about the lawsuits themselves.

FINAL: text 1
text 1
Model: meta-llama/llama-3.2-1b-instruct
Text 2 is more specific than Text 1 because it provides more details about the climate litigation, such as the number of lawsuits (four), the parties involved (CNX, communities, and fossil fuel producers), and the forum (courts). Additionally, Text 2 mentions that the lawsuits are "beginning to gain prevalence in the courts", which suggests a higher level of specificity and detail.

FINAL: text 2
In the following content, extract the final decision. Return ONLY 'text 1' or 'text 2' or 'neither' (no other text). If absent, infer from the last explicit choice.

Text 2 is more specific than Text 1 because it provides more details about the climate litigation, such as the number of lawsuits (four), the parties involved (CNX, communities, and fossil fuel producers), and the forum (courts). Additionally, Text 2 mentions that the lawsuits are "beginning to gain prevalence in the courts", which suggests a higher level of specificity and detail.

FINAL: text 2
text 2
Model: meta-llama/llama-3.2-1b-instruct
Text 2 is more specific than Text 1 because it provides more details about the climate litigation, such as the number of lawsuits, the parties involved, and the forum. Text 1 only mentions the possibility of climate change-related litigation without providing any specific details.

FINAL: text 2
In the following content, extract the final decision. Return ONLY 'text 1' or 'text 2' or 'neither' (no other text). If absent, infer from the last explicit choice.

Text 2 is more specific than Text 1 because it provides more details about the climate litigation, such as the number of lawsuits, the parties involved, and the forum. Text 1 only mentions the possibility of climate change-related litigation without providing any specific details.

FINAL: text 2
text 2
Model: meta-llama/llama-3.2-1b-instruct
Text 1 has more specific details about the climate litigation, including the number of lawsuits (four) and the fact that they are being pursued by communities against fossil fuel producers. Text 2 also mentions four climate change lawsuits, but lacks the specificity of Text 1 in terms of the parties involved and the context of the lawsuits.

FINAL: text 1
In the following content, extract the final decision. Return ONLY 'text 1' or 'text 2' or 'neither' (no other text). If absent, infer from the last explicit choice.

Text 1 has more specific details about the climate litigation, including the number of lawsuits (four) and the fact that they are being pursued by communities against fossil fuel producers. Text 2 also mentions four climate change lawsuits, but lacks the specificity of Text 1 in terms of the parties involved and the context of the lawsuits.

FINAL: text 1
text 1
Model: meta-llama/llama-3.2-1b-instruct
Text 2 provides more specific details about the climate litigation, including the number of lawsuits (four), the parties involved (CNX, communities, and fossil fuel producers), and the forum (courts). Additionally, Text 2 mentions the potential risks and costs associated with defending litigation, which provides more context about the climate litigation.

FINAL: text 2
In the following content, extract the final decision. Return ONLY 'text 1' or 'text 2' or 'neither' (no other text). If absent, infer from the last explicit choice.

Text 2 provides more specific details about the climate litigation, including the number of lawsuits (four), the parties involved (CNX, communities, and fossil fuel producers), and the forum (courts). Additionally, Text 2 mentions the potential risks and costs associated with defending litigation, which provides more context about the climate litigation.

FINAL: text 2
text 2
Model: meta-llama/llama-3.2-1b-instruct
Text 2 is more specific than Text 1 because it provides more details about the climate litigation, including the number of lawsuits, the parties involved, and the potential impact on the company's financial position. Text 1, on the other hand, only mentions a loss contingency related to the Havana Docks litigation without providing any further details.

FINAL: text 2
In the following content, extract the final decision. Return ONLY 'text 1' or 'text 2' or 'neither' (no other text). If absent, infer from the last explicit choice.

Text 2 is more specific than Text 1 because it provides more details about the climate litigation, including the number of lawsuits, the parties involved, and the potential impact on the company's financial position. Text 1, on the other hand, only mentions a loss contingency related to the Havana Docks litigation without providing any further details.

FINAL: text 2
text 2
Model: meta-llama/llama-3.2-1b-instruct
Text 2 is more specific than Text 1 because it provides more precise information about the climate litigation, including the number of lawsuits, the parties involved, and the potential impact on the company's financial position. Text 1, on the other hand, is more general and only mentions the potential risks and challenges related to climate change.

FINAL: text 2
In the following content, extract the final decision. Return ONLY 'text 1' or 'text 2' or 'neither' (no other text). If absent, infer from the last explicit choice.

Text 2 is more specific than Text 1 because it provides more precise information about the climate litigation, including the number of lawsuits, the parties involved, and the potential impact on the company's financial position. Text 1, on the other hand, is more general and only mentions the potential risks and challenges related to climate change.

FINAL: text 2
text 2
Model: meta-llama/llama-3.2-1b-instruct
Text 2 is more specific than Text 1 because it provides more detailed information about the climate litigation, including the parties involved, the forum, and the procedural posture. Text 2 also mentions specific lawsuits and the potential costs of defending them, which adds to its specificity.

FINAL: text 2
In the following content, extract the final decision. Return ONLY 'text 1' or 'text 2' or 'neither' (no other text). If absent, infer from the last explicit choice.

Text 2 is more specific than Text 1 because it provides more detailed information about the climate litigation, including the parties involved, the forum, and the procedural posture. Text 2 also mentions specific lawsuits and the potential costs of defending them, which adds to its specificity.

FINAL: text 2
text 2
Model: meta-llama/llama-3.2-1b-instruct
Text 1 has more specific details about climate litigation, including the mention of specific regulations, laws, and policies related to climate change, such as the Clean Air Act and the Paris Climate Accord. Additionally, Text 1 provides more context about the procedural posture and the sought outcome of the litigation. In contrast, Text 2 provides more general information about climate litigation and does not offer the same level of specificity as Text 1.

FINAL: text 1
In the following content, extract the final decision. Return ONLY 'text 1' or 'text 2' or 'neither' (no other text). If absent, infer from the last explicit choice.

Text 1 has more specific details about climate litigation, including the mention of specific regulations, laws, and policies related to climate change, such as the Clean Air Act and the Paris Climate Accord. Additionally, Text 1 provides more context about the procedural posture and the sought outcome of the litigation. In contrast, Text 2 provides more general information about climate litigation and does not offer the same level of specificity as Text 1.

FINAL: text 1
text 1
Model: meta-llama/llama-3.2-1b-instruct
Text 1 is more specific because it provides more detailed information about the regulatory actions related to climate change, including the Clean Air Act, the Paris Climate Accord, and the Inflation Reduction Act. It also mentions specific dates, monetary amounts, and the parties involved.

FINAL: text 1
In the following content, extract the final decision. Return ONLY 'text 1' or 'text 2' or 'neither' (no other text). If absent, infer from the last explicit choice.

Text 1 is more specific because it provides more detailed information about the regulatory actions related to climate change, including the Clean Air Act, the Paris Climate Accord, and the Inflation Reduction Act. It also mentions specific dates, monetary amounts, and the parties involved.

FINAL: text 1
text 1
Model: meta-llama/llama-3.2-1b-instruct
The text provides a detailed breakdown of the company's potential risks and challenges related to climate change and energy transition, including specific examples of regulatory scrutiny, public perception, and potential litigation. However, the text does not provide exact details on the parties involved, case title or docket, or specific dates.

FINAL: text 2
In the following content, extract the final decision. Return ONLY 'text 1' or 'text 2' or 'neither' (no other text). If absent, infer from the last explicit choice.

The text provides a detailed breakdown of the company's potential risks and challenges related to climate change and energy transition, including specific examples of regulatory scrutiny, public perception, and potential litigation. However, the text does not provide exact details on the parties involved, case title or docket, or specific dates.

FINAL: text 2
text 2
Model: meta-llama/llama-3.2-1b-instruct
Text 1 is more specific than Text 2 because it provides more detailed information about the climate change lawsuits, including the fact that CNX is a defendant in four such lawsuits and that they are being pursued by communities against fossil fuel producers. In contrast, Text 2 does not provide any specific information about climate litigation, but rather discusses general risks and challenges related to environmental issues.

FINAL: text 1
In the following content, extract the final decision. Return ONLY 'text 1' or 'text 2' or 'neither' (no other text). If absent, infer from the last explicit choice.

Text 1 is more specific than Text 2 because it provides more detailed information about the climate change lawsuits, including the fact that CNX is a defendant in four such lawsuits and that they are being pursued by communities against fossil fuel producers. In contrast, Text 2 does not provide any specific information about climate litigation, but rather discusses general risks and challenges related to environmental issues.

FINAL: text 1
text 1
Model: meta-llama/llama-3.2-1b-instruct
Text 2 is more specific than Text 1 because it provides more detailed information about the potential risks and challenges related to climate change, including specific regulations and policies that may impact the company's business and financial results. Additionally, Text 2 mentions the potential for increased exposure to climate change-related litigation, which is a more specific and concrete risk than the general mention of climate change-related risks in Text 1.

FINAL: text 2
In the following content, extract the final decision. Return ONLY 'text 1' or 'text 2' or 'neither' (no other text). If absent, infer from the last explicit choice.

Text 2 is more specific than Text 1 because it provides more detailed information about the potential risks and challenges related to climate change, including specific regulations and policies that may impact the company's business and financial results. Additionally, Text 2 mentions the potential for increased exposure to climate change-related litigation, which is a more specific and concrete risk than the general mention of climate change-related risks in Text 1.

FINAL: text 2
text 2
Model: meta-llama/llama-3.2-1b-instruct
Text 1 is more specific than Text 2 because it provides more details about the potential risks and challenges related to climate change, including the increasing global regulatory focus on climate change and emissions, and the potential impact on the company's business and financial results. In contrast, Text 2 only mentions climate change as one of the various lawsuits and claims that the company is facing, without providing any further details.

FINAL: text 1
In the following content, extract the final decision. Return ONLY 'text 1' or 'text 2' or 'neither' (no other text). If absent, infer from the last explicit choice.

Text 1 is more specific than Text 2 because it provides more details about the potential risks and challenges related to climate change, including the increasing global regulatory focus on climate change and emissions, and the potential impact on the company's business and financial results. In contrast, Text 2 only mentions climate change as one of the various lawsuits and claims that the company is facing, without providing any further details.

FINAL: text 1
text 1
Model: meta-llama/llama-3.2-1b-instruct
Text 1 is more specific than Text 2 because it provides more detailed information about the climate change lawsuits, including the number of lawsuits (four) and the fact that they are being pursued by communities against fossil fuel producers. In contrast, Text 2 only mentions that there are "close to two dozen lawsuits" filed on behalf of various states and municipalities, but does not provide further details.

FINAL: text 1
In the following content, extract the final decision. Return ONLY 'text 1' or 'text 2' or 'neither' (no other text). If absent, infer from the last explicit choice.

Text 1 is more specific than Text 2 because it provides more detailed information about the climate change lawsuits, including the number of lawsuits (four) and the fact that they are being pursued by communities against fossil fuel producers. In contrast, Text 2 only mentions that there are "close to two dozen lawsuits" filed on behalf of various states and municipalities, but does not provide further details.

FINAL: text 1
text 1
Model: liquid/lfm-7b
Text 1 provides more specific details about climate litigation, including the parties involved, the forum, and the specific claims being made. In contrast, Text 2 does not provide specific details about climate litigation, but rather discusses regulatory changes and risks related to climate change.

FINAL: text 1
In the following content, extract the final decision. Return ONLY 'text 1' or 'text 2' or 'neither' (no other text). If absent, infer from the last explicit choice.

Text 1 provides more specific details about climate litigation, including the parties involved, the forum, and the specific claims being made. In contrast, Text 2 does not provide specific details about climate litigation, but rather discusses regulatory changes and risks related to climate change.

FINAL: text 1
text 1
Model: liquid/lfm-7b
Text 1 provides more specific details about climate litigation, including the potential for climate change-related litigation and the impact of regulatory activity on the company's business and financial results. In contrast, Text 2 does not specifically describe climate litigation, focusing instead on regulatory changes and their potential impact on the natural gas industry.

FINAL: text 1
In the following content, extract the final decision. Return ONLY 'text 1' or 'text 2' or 'neither' (no other text). If absent, infer from the last explicit choice.

Text 1 provides more specific details about climate litigation, including the potential for climate change-related litigation and the impact of regulatory activity on the company's business and financial results. In contrast, Text 2 does not specifically describe climate litigation, focusing instead on regulatory changes and their potential impact on the natural gas industry.

FINAL: text 1
text 1
Model: liquid/lfm-7b

In [408]:
#check if all the dfs have 105 rows
for model in pairwise_results_dfs_reversed.keys():
    print(model)
    if len(pairwise_results_dfs_reversed[model]) != 105:
        print(f"Model {model} has {len(pairwise_results_dfs_reversed[model])} rows instead of 105.")

mistralai/mistral/nemo
meta/llama/llama/3.2/3b/instruct
liquid/lfm/7b
meta/llama/llama/3.2/1b/instruct
liquid/lfm/3b
meta-llama/llama-3.2-1b-instruct
liquid/lfm-7b
meta-llama/llama-3.2-3b-instruct
mistralai/mistral-nemo
liquid/lfm-3b
meta-llama/llama-3.1-8b-instruct
google/gemma-3-4b-it
sao10k/l3-lunaris-8b
mistralai/mistral-7b-instruct

In [409]:
invalid_results = check_invalid_results(pairwise_results_dfs_reversed)
invalid_counts = Counter()
for entry in invalid_results:
    model = entry['model']
    invalid_counts[model] += 1

# Print the percentage of invalid results for each model (out of 105)
for model in pairwise_results_dfs_reversed.keys():
    count = invalid_counts.get(model, 0)
    percent = (count / 105) * 100
    print(f"Model: {model}, Invalid results: {count} ({percent:.2f}%)")

Model: mistralai/mistral/nemo, Invalid results: 0 (0.00%)
Model: meta/llama/llama/3.2/3b/instruct, Invalid results: 0 (0.00%)
Model: liquid/lfm/7b, Invalid results: 0 (0.00%)
Model: meta/llama/llama/3.2/1b/instruct, Invalid results: 0 (0.00%)
Model: liquid/lfm/3b, Invalid results: 0 (0.00%)
Model: meta-llama/llama-3.2-1b-instruct, Invalid results: 0 (0.00%)
Model: liquid/lfm-7b, Invalid results: 0 (0.00%)
Model: meta-llama/llama-3.2-3b-instruct, Invalid results: 0 (0.00%)
Model: mistralai/mistral-nemo, Invalid results: 0 (0.00%)
Model: liquid/lfm-3b, Invalid results: 0 (0.00%)
Model: meta-llama/llama-3.1-8b-instruct, Invalid results: 0 (0.00%)
Model: google/gemma-3-4b-it, Invalid results: 0 (0.00%)
Model: sao10k/l3-lunaris-8b, Invalid results: 0 (0.00%)
Model: mistralai/mistral-7b-instruct, Invalid results: 0 (0.00%)

In [411]:
for model in pairwise_results_dfs_reversed:
    pairwise_results_dfs_reversed[model] = convert_result_to_index(pairwise_results_dfs_reversed[model])

In [412]:
# Count the percentage of times each original model predicts "text 1", "text 2", or "neither"
model_percentages = {}
for model, df in pairwise_results_dfs_reversed.items():
    # Normalize result column to strip whitespace and lowercase
    results = df['result'].astype(str).str.strip().str.lower()
    total = len(results)
    text1_count = ((results == 'text 1') | (results == 'text 1\n')).sum()
    text2_count = ((results == 'text 2') | (results == 'text 2\n')).sum()
    neither_count = total - text1_count - text2_count
    model_percentages[model] = {
        'text 1': round(100 * text1_count / total, 2) if total > 0 else 0,
        'text 2': round(100 * text2_count / total, 2) if total > 0 else 0,
        'neither': round(100 * neither_count / total, 2) if total > 0 else 0
    }

model_counts_df = pd.DataFrame.from_dict(model_percentages, orient='index').reset_index().rename(columns={'index': 'Model'})

In [413]:
model_counts_df

                               Model  text 1  text 2  neither
0             mistralai/mistral/nemo   25.71   26.67    47.62
1   meta/llama/llama/3.2/3b/instruct   32.38   54.29    13.33
2                      liquid/lfm/7b   84.76   12.38     2.86
3   meta/llama/llama/3.2/1b/instruct   44.76   29.52    25.71
4                      liquid/lfm/3b   22.86    8.57    68.57
5   meta-llama/llama-3.2-1b-instruct   31.43   45.71    22.86
6                      liquid/lfm-7b   88.57    6.67     4.76
7   meta-llama/llama-3.2-3b-instruct   37.14   56.19     6.67
8             mistralai/mistral-nemo   23.81   19.05    57.14
9                      liquid/lfm-3b   22.86   10.48    66.67
10  meta-llama/llama-3.1-8b-instruct   34.29   64.76     0.95
11              google/gemma-3-4b-it    0.95   99.05     0.00
12              sao10k/l3-lunaris-8b   23.81   67.62     8.57
13     mistralai/mistral-7b-instruct   56.19   42.86     0.95

In [414]:
# Compare forward and reversed results per model: compute, for each model, the percentage of pairs where the forward and reversed winner_idx are the same for that model only

percent_same_by_model = {}

for model in pairwise_results_dfs.keys():
    if model not in pairwise_results_dfs or model not in pairwise_results_dfs_reversed:
        continue  # Only process if present in both sets

    df_forward = pairwise_results_dfs[model]
    df_reversed = pairwise_results_dfs_reversed[model]

    # To compare, align each pair: (idx_1, idx_2) forward with (idx_2, idx_1) reversed
    merged = pd.merge(
        df_forward,
        df_reversed,
        left_on=['idx_1', 'idx_2'],
        right_on=['idx_2', 'idx_1'],
        suffixes=('_forward', '_reversed')
    )

    # Compare winner_idx for each model only
    if 'winner_idx_forward' in merged.columns and 'winner_idx_reversed' in merged.columns:
        model_total = merged.shape[0]
        model_same_winner = (merged['winner_idx_forward'] == merged['winner_idx_reversed']).sum()
        percent_same = (model_same_winner / model_total * 100) if model_total > 0 else 0.0
        percent_same_by_model[model] = percent_same
        print(f"[{model}] Forward vs. reversed winner_idx SAME for {model_same_winner}/{model_total} ({percent_same:.2f}%)")
    else:
        print(f"[{model}] Columns for winner_idx not found, skipping.")

# The dictionary percent_same_by_model can be accessed for further per-model comparison or plotting.

[meta-llama/llama-3.2-1b-instruct] Forward vs. reversed winner_idx SAME for 42/105 (40.00%)
[liquid/lfm-7b] Forward vs. reversed winner_idx SAME for 84/105 (80.00%)
[meta-llama/llama-3.2-3b-instruct] Forward vs. reversed winner_idx SAME for 39/105 (37.14%)
[mistralai/mistral-nemo] Forward vs. reversed winner_idx SAME for 23/105 (21.90%)
[liquid/lfm-3b] Forward vs. reversed winner_idx SAME for 14/105 (13.33%)
[meta-llama/llama-3.1-8b-instruct] Forward vs. reversed winner_idx SAME for 36/105 (34.29%)
[google/gemma-3-4b-it] Forward vs. reversed winner_idx SAME for 4/105 (3.81%)
[sao10k/l3-lunaris-8b] Forward vs. reversed winner_idx SAME for 26/105 (24.76%)
[mistralai/mistral-7b-instruct] Forward vs. reversed winner_idx SAME for 65/105 (61.90%)

_____

Ok, so for now, it looks like liquidlfm is the best but this has gotten messy. I am going to restart, iterating the prompt a little bit, and doing forward and reverse in the same run, in another notebook called pairwise_comparisons.ipynb